// ============================================================
// 考研英语核心词库
// 高频词汇 2500+ 词 - 基于考研真题词频统计
// ============================================================

import type { Word } from './types';
import { WORDS_H076_H175 } from './words_h076_h175';
import { WORDS_M021_M120 } from './words_m021_m120';
import { WORDS_L011_L110 } from './words_l011_l110';
import { WORDS_H176_H275 } from './words_h176_h275';
import { WORDS_H276_H375 } from './words_h276_h375';
import { WORDS_M121_M220 } from './words_m121_m220';
import { WORDS_M221_M320 } from './words_m221_m320';
import { WORDS_L111_L210 } from './words_l111_l210';
import { WORDS_H376_H500 } from './words_h376_h500';
import { WORDS_M321_M420 } from './words_m321_m420';
import { WORDS_M421_M550 } from './words_m421_m550';
import { WORDS_L211_L310 } from './words_l211_l310';
import { WORDS_L311_L410 } from './words_l311_l411';
import { WORDS_L411_L450 } from './words_l411_l450';
import { WORDS_H501_H540 } from './words_h501_h540';
import { WORDS_H541_H600 } from './words_h541_h600';
import { WORDS_H601_H670 } from './words_h601_h670';
import { WORDS_M551_M650 } from './words_m551_m650';
import { WORDS_M651_M730 } from './words_m651_m730';
import { WORDS_L451_L550 } from './words_l451_l550';
import { WORDS_L551_L600 } from './words_l551_l600';
import { WORDS_H671_H750 } from './words_h671_h750';
import { WORDS_H751_H840 } from './words_h751_h840';
import { WORDS_M731_M820 } from './words_m731_m820';
import { WORDS_M821_M910 } from './words_m821_m910';
import { WORDS_L601_L700 } from './words_l601_l700';
import { WORDS_L701_L750 } from './words_l701_l750';
import { WORDS_H841_H930 } from './words_h841_h930';
import { WORDS_H931_H1022 } from './words_h931_h1022';
import { WORDS_M911_M1000 } from './words_m911_m1000';
import { WORDS_M1001_M1092 } from './words_m1001_m1092';
import { WORDS_L750_L840 } from './words_l750_l840';
import { WORDS_L841_L932 } from './words_l841_l932';
import { WORDS_H1023_H1114 } from './words_h1023_h1114';
import { WORDS_H1115_H1230 } from './words_h1115_h1230';
import { WORDS_NEW_01 } from './words_new_01';
import { WORDS_NEW_02 } from './words_new_02';
import { WORDS_NEW_03 } from './words_new_03';
import { WORDS_NEW_04 } from './words_new_04';
import { WORDS_NEW_05 } from './words_new_05';
import { WORDS_NEW_06 } from './words_new_06';
import { WORDS_NEW_07 } from './words_new_07';
import { WORDS_NEW_08 } from './words_new_08';
import { WORDS_NEW_09 } from './words_new_09';
import { WORDS_NEW_10 } from './words_new_10';
import { WORDS_NEW_11 } from './words_new_11';
import { WORDS_NEW_12 } from './words_new_12';
import { WORDS_NEW_13 } from './words_new_13';

const _BASE_WORDS: Word[] = [
  // ==================== 高频词汇 (high) ====================
  { id: 'h001', word: 'abandon', phonetic: '/əˈbændən/', partOfSpeech: 'v.', meanings: ['放弃；遗弃；沉溺于'], englishDef: 'to leave completely and forever; to give up', example: 'Young people should not abandon themselves to despair when facing setbacks.', exampleTranslation: '年轻人在面对挫折时不应沉溺于绝望之中。', exampleSource: '2019年翻译', level: 'high', root: 'ban', affix: 'a-', synonyms: ['desert', 'forsake', 'quit'], antonyms: ['maintain', 'retain'], collocations: ['abandon hope', 'abandon the plan', 'abandon oneself to'] },
  { id: 'h002', word: 'abstract', phonetic: '/ˈæbstrækt/', partOfSpeech: 'adj./n./v.', meanings: ['抽象的；摘要；提取'], englishDef: 'existing in thought or as an idea but not having a physical reality', example: 'The concept of justice is too abstract for young children to understand.', exampleTranslation: '正义这个概念对年幼的孩子来说太过抽象，难以理解。', exampleSource: '2020年阅读理解', level: 'high', root: 'tract', affix: 'abs-', synonyms: ['theoretical', 'conceptual'], antonyms: ['concrete', 'specific'], collocations: ['abstract concept', 'abstract thinking', 'abstract art'] },
  { id: 'h003', word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', partOfSpeech: 'v.', meanings: ['承认；确认；表示感谢'], englishDef: 'to accept or recognize something; to admit the existence or truth of', example: 'It is generally acknowledged that education plays a vital role in personal development.', exampleTranslation: '人们普遍承认，教育在个人发展中起着至关重要的作用。', exampleSource: '2021年阅读理解', level: 'high', root: 'know', affix: 'ac-', synonyms: ['admit', 'recognize', 'confess'], antonyms: ['deny', 'dispute'], collocations: ['acknowledge the fact', 'acknowledge receipt', 'be widely acknowledged'] },
  { id: 'h004', word: 'acquire', phonetic: '/əˈkwaɪər/', partOfSpeech: 'v.', meanings: ['获得；习得'], englishDef: 'to obtain or get something; to learn or develop a skill', example: 'Students acquire knowledge not only from textbooks but also from practical experience.', exampleTranslation: '学生不仅从课本中获取知识，还从实践经验中习得技能。', exampleSource: '2018年阅读理解', level: 'high', root: 'quire', affix: 'ac-', synonyms: ['obtain', 'gain', 'attain'], antonyms: ['lose', 'forfeit'], collocations: ['acquire knowledge', 'acquire skills', 'acquire a company'] },
  { id: 'h005', word: 'adapt', phonetic: '/əˈdæpt/', partOfSpeech: 'v.', meanings: ['适应；改编'], englishDef: 'to change or adjust to new conditions; to modify for a different use', example: 'The ability to adapt to changing environments is crucial for survival in the modern world.', exampleTranslation: '适应不断变化的环境的能力对于在现代世界中生存至关重要。', exampleSource: '2022年完形填空', level: 'high', root: 'apt', affix: 'ad-', synonyms: ['adjust', 'accommodate', 'modify'], antonyms: ['resist', 'maintain'], collocations: ['adapt to', 'adapt oneself to', 'adapt for'] },
  { id: 'h006', word: 'adequate', phonetic: '/ˈædɪkwət/', partOfSpeech: 'adj.', meanings: ['充足的；适当的'], englishDef: 'enough in quantity or good enough in quality for a particular purpose', example: 'The government should ensure that adequate resources are allocated to education.', exampleTranslation: '政府应确保为教育分配充足的资源。', exampleSource: '2020年翻译', level: 'high', root: 'equ', synonyms: ['sufficient', 'enough', 'ample'], antonyms: ['inadequate', 'insufficient'], collocations: ['adequate resources', 'adequate preparation', 'adequate attention'] },
  { id: 'h007', word: 'advocate', phonetic: '/ˈædvəkeɪt/', partOfSpeech: 'v./n.', meanings: ['提倡；拥护者'], englishDef: 'to publicly support or recommend something; a person who supports something', example: 'Many educators advocate a more student-centered approach to learning.', exampleTranslation: '许多教育工作者提倡更加以学生为中心的学习方法。', exampleSource: '2019年阅读理解', level: 'high', root: 'voc', affix: 'ad-', synonyms: ['promote', 'support', 'champion'], antonyms: ['oppose', 'object'], collocations: ['advocate for', 'strongly advocate', 'advocate change'] },
  { id: 'h008', word: 'allocate', phonetic: '/ˈæləkeɪt/', partOfSpeech: 'v.', meanings: ['分配；拨出'], englishDef: 'to give something officially to someone for a particular purpose', example: 'The government allocated substantial funds to infrastructure development.', exampleTranslation: '政府拨出大量资金用于基础设施建设。', exampleSource: '2021年完形填空', level: 'high', root: 'loc', affix: 'al-', synonyms: ['distribute', 'assign', 'allot'], antonyms: ['withhold', 'retain'], collocations: ['allocate resources', 'allocate funds', 'allocate time'] },
  { id: 'h009', word: 'alternative', phonetic: '/ɔːlˈtɜːnətɪv/', partOfSpeech: 'n./adj.', meanings: ['替代方案；替代的'], englishDef: 'one of two or more available possibilities; available as another possibility', example: 'Renewable energy sources provide a viable alternative to fossil fuels.', exampleTranslation: '可再生能源为化石燃料提供了可行的替代方案。', exampleSource: '2022年阅读理解', level: 'high', root: 'alter', affix: '-ative', synonyms: ['substitute', 'option', 'replacement'], antonyms: ['standard', 'conventional'], collocations: ['alternative approach', 'viable alternative', 'alternative energy'] },
  { id: 'h010', word: 'analyze', phonetic: '/ˈænəlaɪz/', partOfSpeech: 'v.', meanings: ['分析；解析'], englishDef: 'to study or examine something in detail to discover more about it', example: 'Researchers analyzed the data collected from over 10,000 participants.', exampleTranslation: '研究人员分析了从一万多名参与者那里收集的数据。', exampleSource: '2020年阅读理解', level: 'high', root: 'lyz', affix: 'ana-', synonyms: ['examine', 'study', 'investigate'], antonyms: ['ignore', 'overlook'], collocations: ['analyze data', 'analyze the impact', 'carefully analyze'] },
  { id: 'h011', word: 'approach', phonetic: '/əˈprəʊtʃ/', partOfSpeech: 'v./n.', meanings: ['接近；方法；途径'], englishDef: 'to come near or nearer to; a way of dealing with something', example: 'A multidisciplinary approach is needed to solve complex social problems.', exampleTranslation: '解决复杂的社会问题需要多学科的方法。', exampleSource: '2018年翻译', level: 'high', root: 'proach', affix: 'ap-', synonyms: ['method', 'strategy', 'technique'], antonyms: ['retreat', 'withdraw'], collocations: ['approach to', 'innovative approach', 'systematic approach'] },
  { id: 'h012', word: 'appropriate', phonetic: '/əˈprəʊpriət/', partOfSpeech: 'adj.', meanings: ['适当的；恰当的'], englishDef: 'suitable or right for a particular situation or occasion', example: 'It is essential to choose appropriate research methods for each study.', exampleTranslation: '为每项研究选择适当的研究方法是至关重要的。', exampleSource: '2021年阅读理解', level: 'high', root: 'propri', affix: 'ap-', synonyms: ['suitable', 'proper', 'fitting'], antonyms: ['inappropriate', 'unsuitable'], collocations: ['appropriate measures', 'deem appropriate', 'appropriate response'] },
  { id: 'h013', word: 'assume', phonetic: '/əˈsjuːm/', partOfSpeech: 'v.', meanings: ['假设；承担；呈现'], englishDef: 'to think or accept that something is true but without having proof', example: 'It would be wrong to assume that technology alone can solve all our problems.', exampleTranslation: '认为单靠技术就能解决我们所有的问题是错误的。', exampleSource: '2020年阅读理解', level: 'high', root: 'sum', affix: 'as-', synonyms: ['presume', 'suppose', 'hypothesize'], antonyms: ['prove', 'verify'], collocations: ['assume responsibility', 'assume that', 'safely assume'] },
  { id: 'h014', word: 'authority', phonetic: '/ɔːˈθɒrəti/', partOfSpeech: 'n.', meanings: ['权威；当局；权力'], englishDef: 'the power or right to give orders or make decisions; an expert', example: 'Local authorities should take measures to improve public transportation.', exampleTranslation: '地方当局应采取措施改善公共交通。', exampleSource: '2019年完形填空', level: 'high', root: 'auth', affix: '-ity', synonyms: ['power', 'control', 'expert'], antonyms: ['subordinate', 'follower'], collocations: ['local authority', 'have authority over', 'academic authority'] },
  { id: 'h015', word: 'available', phonetic: '/əˈveɪləbl/', partOfSpeech: 'adj.', meanings: ['可获得的；有空的'], englishDef: 'able to be obtained or used; free to be contacted', example: 'More information is available on the university website.', exampleTranslation: '更多信息可在大学网站上获取。', exampleSource: '2022年阅读理解', level: 'high', root: 'avail', affix: '-able', synonyms: ['accessible', 'obtainable', 'ready'], antonyms: ['unavailable', 'scarce'], collocations: ['readily available', 'available resources', 'make available'] },
  { id: 'h016', word: 'benefit', phonetic: '/ˈbenɪfɪt/', partOfSpeech: 'n./v.', meanings: ['利益；好处；受益'], englishDef: 'an advantage or profit gained from something', example: 'Regular exercise benefits both physical and mental health.', exampleTranslation: '经常锻炼有益于身心健康。', exampleSource: '2018年完形填空', level: 'high', root: 'bene', synonyms: ['advantage', 'profit', 'gain'], antonyms: ['drawback', 'disadvantage'], collocations: ['benefit from', 'mutual benefit', 'health benefits'] },
  { id: 'h017', word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', partOfSpeech: 'n./v.', meanings: ['挑战；质疑'], englishDef: 'a difficult task or situation that tests someone\'s abilities', example: 'Climate change poses a significant challenge to global food security.', exampleTranslation: '气候变化对全球粮食安全构成了重大挑战。', exampleSource: '2021年阅读理解', level: 'high', synonyms: ['test', 'confront', 'question'], antonyms: ['accept', 'support'], collocations: ['pose a challenge', 'face the challenge', 'take up the challenge'] },
  { id: 'h018', word: 'circumstance', phonetic: '/ˈsɜːkəmstəns/', partOfSpeech: 'n.', meanings: ['环境；情况；条件'], englishDef: 'a fact or event that makes a situation the way it is', example: 'Under no circumstances should we compromise on the quality of education.', exampleTranslation: '在任何情况下，我们都不应在教育质量上妥协。', exampleSource: '2020年翻译', level: 'high', root: 'circum', affix: '-stance', synonyms: ['situation', 'condition', 'context'], antonyms: [], collocations: ['under circumstances', 'no circumstances', 'difficult circumstances'] },
  { id: 'h019', word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', partOfSpeech: 'adj.', meanings: ['综合的；全面的；有理解力的'], englishDef: 'including all or nearly all elements or aspects of something', example: 'A comprehensive study reveals the impact of urbanization on local ecosystems.', exampleTranslation: '一项综合研究揭示了城市化对当地生态系统的影响。', exampleSource: '2019年阅读理解', level: 'high', root: 'prehens', affix: 'com-', synonyms: ['extensive', 'thorough', 'complete'], antonyms: ['partial', 'limited'], collocations: ['comprehensive study', 'comprehensive approach', 'comprehensive review'] },
  { id: 'h020', word: 'concept', phonetic: '/ˈkɒnsept/', partOfSpeech: 'n.', meanings: ['概念；观念'], englishDef: 'an abstract idea or general notion', example: 'The concept of sustainable development has gained widespread acceptance in recent decades.', exampleTranslation: '可持续发展的概念近几十年来获得了广泛认同。', exampleSource: '2021年翻译', level: 'high', root: 'cept', affix: 'con-', synonyms: ['idea', 'notion', 'theory'], antonyms: [], collocations: ['core concept', 'concept of', 'abstract concept'] },
  { id: 'h021', word: 'conscious', phonetic: '/ˈkɒnʃəs/', partOfSpeech: 'adj.', meanings: ['有意识的；自觉的'], englishDef: 'aware of and responding to one\'s surroundings; deliberate', example: 'People are becoming increasingly conscious of the environmental impact of their choices.', exampleTranslation: '人们越来越意识到自己的选择对环境的影响。', exampleSource: '2020年阅读理解', level: 'high', root: 'sci', affix: 'con-', synonyms: ['aware', 'mindful', 'alert'], antonyms: ['unconscious', 'unaware'], collocations: ['conscious of', 'conscious effort', 'become conscious'] },
  { id: 'h022', word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', partOfSpeech: 'v.', meanings: ['贡献；捐献；投稿'], englishDef: 'to give something, especially money or goods, to help achieve a purpose', example: 'Each member of the team contributed to the success of the project.', exampleTranslation: '团队的每个成员都为项目的成功做出了贡献。', exampleSource: '2018年完形填空', level: 'high', root: 'tribut', affix: 'con-', synonyms: ['donate', 'provide', 'supply'], antonyms: ['withhold', 'take away'], collocations: ['contribute to', 'contribute significantly', 'contribute money'] },
  { id: 'h023', word: 'crucial', phonetic: '/ˈkruːʃəl/', partOfSpeech: 'adj.', meanings: ['至关重要的；决定性的'], englishDef: 'extremely important because it affects the result of something', example: 'Early childhood education is crucial for cognitive development.', exampleTranslation: '早期儿童教育对认知发展至关重要。', exampleSource: '2022年阅读理解', level: 'high', root: 'cruc', affix: '-ial', synonyms: ['essential', 'vital', 'critical'], antonyms: ['trivial', 'insignificant'], collocations: ['play a crucial role', 'crucial to', 'absolutely crucial'] },
  { id: 'h024', word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', partOfSpeech: 'v.', meanings: ['证明；展示；示威'], englishDef: 'to show clearly that something is true or exists; to show how something works', example: 'The research demonstrates that bilingual children outperform monolingual peers in certain cognitive tasks.', exampleTranslation: '研究表明，双语儿童在某些认知任务上优于单语同龄人。', exampleSource: '2021年阅读理解', level: 'high', root: 'monstr', affix: 'de-', synonyms: ['show', 'prove', 'illustrate'], antonyms: ['conceal', 'hide'], collocations: ['demonstrate that', 'clearly demonstrate', 'demonstrate ability'] },
  { id: 'h025', word: 'derive', phonetic: '/dɪˈraɪv/', partOfSpeech: 'v.', meanings: ['获得；源于；推导'], englishDef: 'to get something from a particular source; to originate from', example: 'Many English words are derived from Latin and Greek roots.', exampleTranslation: '许多英语单词源于拉丁语和希腊语词根。', exampleSource: '2019年翻译', level: 'high', root: 'riv', affix: 'de-', synonyms: ['obtain', 'originate', 'extract'], antonyms: [], collocations: ['derive from', 'derive benefit', 'be derived from'] },
  { id: 'h026', word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/', partOfSpeech: 'v.', meanings: ['区分；辨别；使杰出'], englishDef: 'to recognize or treat someone or something as different', example: 'It is important to distinguish between correlation and causation in scientific research.', exampleTranslation: '在科学研究中，区分相关性和因果关系很重要。', exampleSource: '2020年阅读理解', level: 'high', root: 'sting', affix: 'di-', synonyms: ['differentiate', 'discriminate', 'discern'], antonyms: ['confuse', 'mix up'], collocations: ['distinguish between', 'distinguish from', 'clearly distinguish'] },
  { id: 'h027', word: 'domestic', phonetic: '/dəˈmestɪk/', partOfSpeech: 'adj.', meanings: ['国内的；家庭的'], englishDef: 'relating to or happening in one particular country; of the home or family', example: 'The government needs to balance domestic needs with international commitments.', exampleTranslation: '政府需要在国内需求和国际承诺之间取得平衡。', exampleSource: '2021年完形填空', level: 'high', root: 'dom', synonyms: ['national', 'internal', 'home'], antonyms: ['foreign', 'international'], collocations: ['domestic market', 'domestic policy', 'domestic violence'] },
  { id: 'h028', word: 'dominant', phonetic: '/ˈdɒmɪnənt/', partOfSpeech: 'adj.', meanings: ['占主导地位的；支配的'], englishDef: 'more important, strong, or noticeable than anything else of the same type', example: 'English has become the dominant language in international communication.', exampleTranslation: '英语已成为国际交流中的主导语言。', exampleSource: '2018年阅读理解', level: 'high', root: 'dom', affix: '-ant', synonyms: ['prevailing', 'predominant', 'chief'], antonyms: ['subordinate', 'minor'], collocations: ['dominant position', 'dominant role', 'dominant culture'] },
  { id: 'h029', word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', partOfSpeech: 'v.', meanings: ['消除；淘汰；排除'], englishDef: 'to completely remove or get rid of something', example: 'Efforts to eliminate poverty require coordinated action from multiple sectors.', exampleTranslation: '消除贫困的努力需要多个部门的协调行动。', exampleSource: '2022年翻译', level: 'high', root: 'limin', affix: 'e-', synonyms: ['remove', 'eradicate', 'abolish'], antonyms: ['include', 'add'], collocations: ['eliminate poverty', 'eliminate risk', 'completely eliminate'] },
  { id: 'h030', word: 'emerge', phonetic: '/ɪˈmɜːdʒ/', partOfSpeech: 'v.', meanings: ['出现；浮现；兴起'], englishDef: 'to come out of a dark or hidden place; to become known', example: 'New evidence has emerged that challenges the traditional view of the subject.', exampleTranslation: '出现了新的证据，挑战了对该问题的传统观点。', exampleSource: '2019年阅读理解', level: 'high', root: 'merg', affix: 'e-', synonyms: ['appear', 'arise', 'surface'], antonyms: ['disappear', 'submerge'], collocations: ['emerge from', 'new evidence emerged', 'emerging markets'] },
  { id: 'h031', word: 'emphasis', phonetic: '/ˈemfəsɪs/', partOfSpeech: 'n.', meanings: ['强调；重点'], englishDef: 'special importance or attention given to something', example: 'The report places special emphasis on the need for sustainable urban planning.', exampleTranslation: '报告特别强调了可持续城市规划的必要性。', exampleSource: '2020年阅读理解', level: 'high', root: 'pha', synonyms: ['importance', 'stress', 'focus'], antonyms: [], collocations: ['place emphasis on', 'strong emphasis', 'special emphasis'] },
  { id: 'h032', word: 'enhance', phonetic: '/ɪnˈhɑːns/', partOfSpeech: 'v.', meanings: ['提高；增强；改善'], englishDef: 'to improve the quality, amount, or strength of something', example: 'Technology can significantly enhance the efficiency of learning.', exampleTranslation: '技术可以显著提高学习效率。', exampleSource: '2021年翻译', level: 'high', root: 'hanc', affix: 'en-', synonyms: ['improve', 'boost', 'strengthen'], antonyms: ['diminish', 'reduce'], collocations: ['enhance the quality', 'significantly enhance', 'enhance performance'] },
  { id: 'h033', word: 'ensure', phonetic: '/ɪnˈʃʊər/', partOfSpeech: 'v.', meanings: ['确保；保证'], englishDef: 'to make certain that something happens or is the case', example: 'Strict regulations are necessary to ensure food safety.', exampleTranslation: '严格的法规是确保食品安全所必需的。', exampleSource: '2022年完形填空', level: 'high', root: 'sur', affix: 'en-', synonyms: ['guarantee', 'secure', 'assure'], antonyms: ['endanger', 'jeopardize'], collocations: ['ensure that', 'ensure safety', 'take steps to ensure'] },
  { id: 'h034', word: 'establish', phonetic: '/ɪˈstæblɪʃ/', partOfSpeech: 'v.', meanings: ['建立；确立；查实'], englishDef: 'to start or create an organization, system, or set of rules', example: 'The university was established in the early 20th century.', exampleTranslation: '该大学建于20世纪初。', exampleSource: '2018年阅读理解', level: 'high', root: 'stab', affix: 'e-', synonyms: ['found', 'create', 'set up'], antonyms: ['abolish', 'destroy'], collocations: ['establish a system', 'well-established', 'establish standards'] },
  { id: 'h035', word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', partOfSpeech: 'v.', meanings: ['评估；评价'], englishDef: 'to judge or calculate the quality, importance, or value of something', example: 'Teachers should evaluate students\' performance using multiple assessment methods.', exampleTranslation: '教师应使用多种评估方法来评价学生的表现。', exampleSource: '2020年翻译', level: 'high', root: 'valu', affix: 'e-', synonyms: ['assess', 'judge', 'appraise'], antonyms: ['ignore', 'neglect'], collocations: ['evaluate the effectiveness', 'carefully evaluate', 'evaluate performance'] },
  { id: 'h036', word: 'evidence', phonetic: '/ˈevɪdəns/', partOfSpeech: 'n.', meanings: ['证据；证明'], englishDef: 'facts or signs that show clearly that something exists or is true', example: 'There is growing evidence that climate change is accelerating.', exampleTranslation: '越来越多的证据表明气候变化正在加速。', exampleSource: '2021年阅读理解', level: 'high', root: 'vid', affix: 'e-', synonyms: ['proof', 'testimony', 'indication'], antonyms: [], collocations: ['growing evidence', 'scientific evidence', 'compelling evidence'] },
  { id: 'h037', word: 'evolve', phonetic: '/ɪˈvɒlv/', partOfSpeech: 'v.', meanings: ['进化；发展；逐步形成'], englishDef: 'to develop gradually, especially from a simple to a more complicated form', example: 'The internet has evolved from a military tool into an essential part of daily life.', exampleTranslation: '互联网已从军事工具发展成了日常生活中不可或缺的一部分。', exampleSource: '2019年阅读理解', level: 'high', root: 'volve', affix: 'e-', synonyms: ['develop', 'progress', 'advance'], antonyms: ['devolve', 'regress'], collocations: ['evolve over time', 'evolve into', 'evolve from'] },
  { id: 'h038', word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', partOfSpeech: 'v./n.', meanings: ['利用；开发；功绩'], englishDef: 'to use something well in order to gain as much as possible; an achievement', example: 'Companies should exploit new technologies to improve productivity.', exampleTranslation: '公司应该利用新技术来提高生产力。', exampleSource: '2020年完形填空', level: 'high', root: 'ploit', affix: 'ex-', synonyms: ['utilize', 'leverage', 'harness'], antonyms: ['waste', 'neglect'], collocations: ['exploit resources', 'exploit technology', 'fully exploit'] },
  { id: 'h039', word: 'expose', phonetic: '/ɪkˈspəʊz/', partOfSpeech: 'v.', meanings: ['暴露；揭露；使接触'], englishDef: 'to reveal something hidden; to make something known', example: 'Children exposed to diverse cultures tend to be more open-minded.', exampleTranslation: '接触多元文化的孩子往往思想更开放。', exampleSource: '2021年翻译', level: 'high', root: 'pos', affix: 'ex-', synonyms: ['reveal', 'uncover', 'disclose'], antonyms: ['conceal', 'hide'], collocations: ['expose to', 'be exposed to', 'expose the truth'] },
  { id: 'h040', word: 'fundamental', phonetic: '/ˌfʌndəˈmentəl/', partOfSpeech: 'adj.', meanings: ['基本的；根本的；重要的'], englishDef: 'forming the base, from which everything else develops', example: 'Access to quality education is a fundamental right that should be guaranteed.', exampleTranslation: '获得优质教育是一项应该得到保障的基本权利。', exampleSource: '2022年翻译', level: 'high', root: 'fund', affix: '-mental', synonyms: ['basic', 'essential', 'primary'], antonyms: ['secondary', 'peripheral'], collocations: ['fundamental change', 'fundamental principle', 'fundamental role'] },
  { id: 'h041', word: 'generate', phonetic: '/ˈdʒenəreɪt/', partOfSpeech: 'v.', meanings: ['产生；发电；引起'], englishDef: 'to cause something to exist; to produce energy', example: 'The new policy is expected to generate significant economic growth.', exampleTranslation: '新政策预计将带来显著的经济增长。', exampleSource: '2019年阅读理解', level: 'high', root: 'gen', affix: '-ate', synonyms: ['produce', 'create', 'yield'], antonyms: ['destroy', 'consume'], collocations: ['generate revenue', 'generate interest', 'generate energy'] },
  { id: 'h042', word: 'implement', phonetic: '/ˈɪmplɪment/', partOfSpeech: 'v./n.', meanings: ['实施；执行；工具'], englishDef: 'to start using a plan or system; a tool or instrument', example: 'The government has implemented a series of measures to reduce air pollution.', exampleTranslation: '政府已经实施了一系列措施来减少空气污染。', exampleSource: '2020年阅读理解', level: 'high', root: 'ple', affix: 'im-', synonyms: ['execute', 'carry out', 'enforce'], antonyms: ['abandon', 'cancel'], collocations: ['implement policies', 'implement measures', 'successfully implement'] },
  { id: 'h043', word: 'imply', phonetic: '/ɪmˈplaɪ/', partOfSpeech: 'v.', meanings: ['暗示；意味着'], englishDef: 'to communicate an idea or feeling without saying it directly', example: 'The author implies that the current education system needs reform.', exampleTranslation: '作者暗示当前的教育体制需要改革。', exampleSource: '2021年阅读理解', level: 'high', root: 'ply', affix: 'im-', synonyms: ['suggest', 'indicate', 'hint'], antonyms: ['state', 'declare'], collocations: ['imply that', 'strongly imply', 'necessarily imply'] },
  { id: 'h044', word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', partOfSpeech: 'adj.', meanings: ['不可避免的；必然的'], englishDef: 'certain to happen and unable to be avoided or prevented', example: 'Technological change is inevitable in the modern world.', exampleTranslation: '在现代社会中，技术变革是不可避免的。', exampleSource: '2022年阅读理解', level: 'high', root: 'evit', affix: 'in-', synonyms: ['unavoidable', 'inescapable', 'certain'], antonyms: ['avoidable', 'preventable'], collocations: ['inevitable consequence', 'seem inevitable', 'almost inevitable'] },
  { id: 'h045', word: 'interpret', phonetic: '/ɪnˈtɜːprɪt/', partOfSpeech: 'v.', meanings: ['解释；口译；理解'], englishDef: 'to explain the meaning of something; to translate spoken words', example: 'Scholars interpret the historical event from various perspectives.', exampleTranslation: '学者们从不同角度解读这一历史事件。', exampleSource: '2018年翻译', level: 'high', root: 'pret', affix: 'inter-', synonyms: ['explain', 'understand', 'decode'], antonyms: ['misunderstand', 'confuse'], collocations: ['interpret the data', 'interpret as', 'differently interpret'] },
  { id: 'h046', word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', partOfSpeech: 'v.', meanings: ['调查；研究'], englishDef: 'to try to find out the facts about something', example: 'Scientists are investigating the long-term effects of microplastics on human health.', exampleTranslation: '科学家正在研究微塑料对人类健康的长期影响。', exampleSource: '2021年阅读理解', level: 'high', root: 'vestig', affix: 'in-', synonyms: ['examine', 'explore', 'probe'], antonyms: ['ignore', 'overlook'], collocations: ['investigate the cause', 'thoroughly investigate', 'investigate claims'] },
  { id: 'h047', word: 'justify', phonetic: '/ˈdʒʌstɪfaɪ/', partOfSpeech: 'v.', meanings: ['证明...是正当的；为...辩护'], englishDef: 'to give or be a good reason for something', example: 'How can the government justify spending so much on defense?', exampleTranslation: '政府如何证明在国防上花费如此之多是正当的？', exampleSource: '2020年完形填空', level: 'high', root: 'just', affix: '-ify', synonyms: ['defend', 'vindicate', 'warrant'], antonyms: ['condemn', 'criticize'], collocations: ['justify the decision', 'hard to justify', 'cannot justify'] },
  { id: 'h048', word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', partOfSpeech: 'adj.', meanings: ['合法的；正当的；合理的'], englishDef: 'allowed by law; reasonable and acceptable', example: 'Citizens have a legitimate right to express their opinions on public affairs.', exampleTranslation: '公民对公共事务表达意见是正当的权利。', exampleSource: '2019年阅读理解', level: 'high', root: 'leg', affix: '-imate', synonyms: ['lawful', 'valid', 'reasonable'], antonyms: ['illegal', 'illegitimate'], collocations: ['legitimate concern', 'legitimate right', 'perfectly legitimate'] },
  { id: 'h049', word: 'perspective', phonetic: '/pəˈspektɪv/', partOfSpeech: 'n.', meanings: ['视角；观点；透视'], englishDef: 'a particular way of considering something; a point of view', example: 'The study offers a fresh perspective on the relationship between culture and language.', exampleTranslation: '这项研究为文化与语言之间的关系提供了新的视角。', exampleSource: '2022年阅读理解', level: 'high', root: 'spect', affix: 'per-', synonyms: ['viewpoint', 'standpoint', 'angle'], antonyms: [], collocations: ['from the perspective of', 'new perspective', 'broader perspective'] },
  { id: 'h050', word: 'potential', phonetic: '/pəˈtenʃəl/', partOfSpeech: 'adj./n.', meanings: ['潜在的；潜力'], englishDef: 'possible but not yet achieved; abilities that may be developed', example: 'Artificial intelligence has the potential to transform education as we know it.', exampleTranslation: '人工智能有潜力彻底改变我们所知的教育。', exampleSource: '2021年翻译', level: 'high', root: 'pot', affix: '-ential', synonyms: ['possible', 'prospective', 'latent'], antonyms: ['actual', 'realized'], collocations: ['have the potential', 'unlock potential', 'potential impact'] },
  { id: 'h051', word: 'phenomenon', phonetic: '/fɪˈnɒmɪnən/', partOfSpeech: 'n.', meanings: ['现象；非凡的人或事'], englishDef: 'something that exists and can be seen, felt, or experienced', example: 'The phenomenon of globalization has profoundly reshaped the world economy.', exampleTranslation: '全球化这一现象深刻地重塑了世界经济。', exampleSource: '2018年阅读理解', level: 'high', root: 'phen', synonyms: ['event', 'occurrence', 'happening'], antonyms: [], collocations: ['common phenomenon', 'natural phenomenon', 'cultural phenomenon'] },
  { id: 'h052', word: 'predominant', phonetic: '/prɪˈdɒmɪnənt/', partOfSpeech: 'adj.', meanings: ['主要的；占优势的'], englishDef: 'most common or important; having the greatest influence', example: 'Tourism has become the predominant source of income for the region.', exampleTranslation: '旅游业已成为该地区最主要的收入来源。', exampleSource: '2020年阅读理解', level: 'high', root: 'dom', affix: 'pre-', synonyms: ['dominant', 'principal', 'chief'], antonyms: ['minor', 'subordinate'], collocations: ['predominant factor', 'predominant role', 'become predominant'] },
  { id: 'h053', word: 'prospect', phonetic: '/ˈprɒspekt/', partOfSpeech: 'n.', meanings: ['前景；展望；可能性'], englishDef: 'the possibility that something will happen; a wide view of something', example: 'The prospects for economic recovery remain uncertain in the short term.', exampleTranslation: '短期内经济复苏的前景仍不确定。', exampleSource: '2022年完形填空', level: 'high', root: 'spect', affix: 'pro-', synonyms: ['outlook', 'expectation', 'possibility'], antonyms: [], collocations: ['career prospects', 'future prospects', 'good prospect'] },
  { id: 'h054', word: 'pursue', phonetic: '/pəˈsjuː/', partOfSpeech: 'v.', meanings: ['追求；追赶；继续探讨'], englishDef: 'to follow or chase someone or something; to try to achieve something', example: 'More young people are choosing to pursue higher education abroad.', exampleTranslation: '越来越多的年轻人选择出国追求高等教育。', exampleSource: '2019年翻译', level: 'high', synonyms: ['chase', 'follow', 'seek'], antonyms: ['abandon', 'give up'], collocations: ['pursue a career', 'pursue knowledge', 'pursue the goal'] },
  { id: 'h055', word: 'relevant', phonetic: '/ˈreləvənt/', partOfSpeech: 'adj.', meanings: ['相关的；切题的'], englishDef: 'connected with what is happening or being discussed', example: 'The research findings are directly relevant to current policy debates.', exampleTranslation: '研究结果与当前的政策辩论直接相关。', exampleSource: '2021年阅读理解', level: 'high', root: 'lev', affix: 're-', synonyms: ['related', 'pertinent', 'applicable'], antonyms: ['irrelevant', 'unrelated'], collocations: ['relevant to', 'highly relevant', 'directly relevant'] },
  { id: 'h056', word: 'reveal', phonetic: '/rɪˈviːl/', partOfSpeech: 'v.', meanings: ['揭示；透露；展现'], englishDef: 'to make known or show something that was previously hidden or secret', example: 'The survey reveals that public trust in institutions has declined significantly.', exampleTranslation: '调查显示公众对机构的信任显著下降。', exampleSource: '2020年翻译', level: 'high', root: 'veal', affix: 're-', synonyms: ['disclose', 'uncover', 'expose'], antonyms: ['conceal', 'hide'], collocations: ['reveal the truth', 'study reveals', 'reveal that'] },
  { id: 'h057', word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', partOfSpeech: 'adj.', meanings: ['重要的；显著的；有意义的'], englishDef: 'important or noticeable; large enough to have an effect', example: 'There has been a significant increase in online learning enrollment.', exampleTranslation: '在线学习的注册人数有了显著增长。', exampleSource: '2022年阅读理解', level: 'high', root: 'sign', affix: '-ificant', synonyms: ['important', 'notable', 'considerable'], antonyms: ['insignificant', 'trivial'], collocations: ['significant impact', 'significant increase', 'statistically significant'] },
  { id: 'h058', word: 'substantial', phonetic: '/səbˈstænʃəl/', partOfSpeech: 'adj.', meanings: ['大量的；实质的；坚固的'], englishDef: 'large in amount or value; important', example: 'Substantial investment in education is essential for long-term economic growth.', exampleTranslation: '对教育的大量投资对长期经济增长至关重要。', exampleSource: '2018年阅读理解', level: 'high', root: 'stat', affix: 'sub-', synonyms: ['considerable', 'significant', 'ample'], antonyms: ['insubstantial', 'minimal'], collocations: ['substantial amount', 'substantial evidence', 'substantial improvement'] },
  { id: 'h059', word: 'sufficient', phonetic: '/səˈfɪʃənt/', partOfSpeech: 'adj.', meanings: ['足够的；充分的'], englishDef: 'enough for a particular purpose', example: 'The evidence is not sufficient to support the conclusion drawn by the researchers.', exampleTranslation: '证据不足以支持研究人员得出的结论。', exampleSource: '2021年阅读理解', level: 'high', root: 'fic', affix: 'suf-', synonyms: ['enough', 'adequate', 'ample'], antonyms: ['insufficient', 'inadequate'], collocations: ['sufficient evidence', 'sufficient resources', 'deem sufficient'] },
  { id: 'h060', word: 'sustain', phonetic: '/səˈsteɪn/', partOfSpeech: 'v.', meanings: ['维持；支撑；承受'], englishDef: 'to make something continue for a period of time; to support', example: 'Economic growth must be sustained over the long term to reduce poverty effectively.', exampleTranslation: '必须在长期内维持经济增长，才能有效地减少贫困。', exampleSource: '2020年翻译', level: 'high', root: 'tain', affix: 'sus-', synonyms: ['maintain', 'support', 'uphold'], antonyms: ['abandon', 'weaken'], collocations: ['sustain growth', 'sustain the economy', 'sustainable development'] },
  { id: 'h061', word: 'transform', phonetic: '/trænsˈfɔːm/', partOfSpeech: 'v.', meanings: ['转变；改造；变换'], englishDef: 'to change completely the appearance or character of something', example: 'Digital technology has transformed the way we communicate and learn.', exampleTranslation: '数字技术改变了我们交流和学习的方式。', exampleSource: '2022年翻译', level: 'high', root: 'form', affix: 'trans-', synonyms: ['change', 'convert', 'revolutionize'], antonyms: ['maintain', 'preserve'], collocations: ['transform into', 'transform the way', 'fundamentally transform'] },
  { id: 'h062', word: 'utilize', phonetic: '/ˈjuːtɪlaɪz/', partOfSpeech: 'v.', meanings: ['利用；使用'], englishDef: 'to use something in an effective way', example: 'Schools should utilize technology more effectively to enhance learning outcomes.', exampleTranslation: '学校应该更有效地利用技术来提高学习成果。', exampleSource: '2019年翻译', level: 'high', root: 'util', affix: '-ize', synonyms: ['use', 'employ', 'harness'], antonyms: ['waste', 'squander'], collocations: ['utilize resources', 'effectively utilize', 'fully utilize'] },
  { id: 'h063', word: 'valid', phonetic: '/ˈvælɪd/', partOfSpeech: 'adj.', meanings: ['有效的；合理的；有根据的'], englishDef: 'based on truth or reason; legally acceptable', example: 'The researcher raised several valid concerns about the methodology used in the study.', exampleTranslation: '研究人员对该研究中使用的方法提出了几个合理的担忧。', exampleSource: '2021年阅读理解', level: 'high', root: 'val', affix: '-id', synonyms: ['legitimate', 'sound', 'reasonable'], antonyms: ['invalid', 'flawed'], collocations: ['valid argument', 'valid concern', 'legally valid'] },
  { id: 'h064', word: 'variety', phonetic: '/vəˈraɪəti/', partOfSpeech: 'n.', meanings: ['多样性；种类；变化'], englishDef: 'the characteristic of often changing and being different; a type of thing', example: 'A variety of factors contribute to the decline in reading habits among young people.', exampleTranslation: '多种因素导致了年轻人阅读习惯的下降。', exampleSource: '2018年阅读理解', level: 'high', root: 'var', affix: '-iety', synonyms: ['diversity', 'range', 'assortment'], antonyms: ['uniformity', 'monotony'], collocations: ['a variety of', 'wide variety', 'great variety'] },
  { id: 'h065', word: 'vehicle', phonetic: '/ˈviːɪkl/', partOfSpeech: 'n.', meanings: ['车辆；工具；手段'], englishDef: 'a machine used for transporting people or goods; a way of achieving something', example: 'Education serves as a vehicle for social mobility and economic advancement.', exampleTranslation: '教育是社会流动和经济进步的手段。', exampleSource: '2020年翻译', level: 'high', root: 'veh', synonyms: ['car', 'instrument', 'medium'], antonyms: [], collocations: ['motor vehicle', 'vehicle for', 'electric vehicle'] },
  { id: 'h066', word: 'widespread', phonetic: '/ˈwaɪdspred/', partOfSpeech: 'adj.', meanings: ['广泛的；普遍的'], englishDef: 'existing or happening in many places or among many people', example: 'The widespread use of smartphones has changed social interaction patterns.', exampleTranslation: '智能手机的广泛使用改变了社交互动模式。', exampleSource: '2019年阅读理解', level: 'high', synonyms: ['extensive', 'prevalent', 'universal'], antonyms: ['limited', 'rare'], collocations: ['widespread use', 'widespread concern', 'widespread acceptance'] },
  { id: 'h067', word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', partOfSpeech: 'v.', meanings: ['容纳；适应；提供住宿'], englishDef: 'to provide with a place to live or to be stored in; to adjust', example: 'The university has built new dormitories to accommodate the growing number of students.', exampleTranslation: '大学建造了新宿舍楼来容纳不断增长的学生人数。', exampleSource: '2021年完形填空', level: 'high', root: 'mod', affix: 'ac-', synonyms: ['house', 'lodge', 'adjust'], antonyms: ['displace', 'evict'], collocations: ['accommodate the needs', 'accommodate up to', 'accommodate change'] },
  { id: 'h068', word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', partOfSpeech: 'v.', meanings: ['完成；实现；达到'], englishDef: 'to finish something successfully or to achieve something', example: 'The team accomplished their research goals ahead of schedule.', exampleTranslation: '团队提前完成了研究目标。', exampleSource: '2020年完形填空', level: 'high', root: 'compl', affix: 'ac-', synonyms: ['achieve', 'complete', 'fulfill'], antonyms: ['fail', 'forfeit'], collocations: ['accomplish the goal', 'accomplish the task', 'successfully accomplish'] },
  { id: 'h069', word: 'conceive', phonetic: '/kənˈsiːv/', partOfSpeech: 'v.', meanings: ['构想；设想；怀孕'], englishDef: 'to form a plan or idea in the mind; to become pregnant', example: 'It is difficult to conceive of a modern society without the internet.', exampleTranslation: '很难想象一个没有互联网的现代社会。', exampleSource: '2022年翻译', level: 'high', root: 'ceiv', affix: 'con-', synonyms: ['imagine', 'envision', 'devise'], antonyms: ['misunderstand', 'disbelieve'], collocations: ['conceive of', 'conceive the idea', 'difficult to conceive'] },
  { id: 'h070', word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', partOfSpeech: 'n.', meanings: ['结果；后果；重要性'], englishDef: 'a result of a particular action or situation, often one that is bad', example: 'The environmental consequences of rapid industrialization cannot be ignored.', exampleTranslation: '快速工业化的环境后果不容忽视。', exampleSource: '2018年翻译', level: 'high', root: 'sequ', affix: 'con-', synonyms: ['result', 'outcome', 'effect'], antonyms: ['cause', 'origin'], collocations: ['negative consequence', 'as a consequence', 'serious consequence'] },
  { id: 'h071', word: 'constitute', phonetic: '/ˈkɒnstɪtjuːt/', partOfSpeech: 'v.', meanings: ['构成；组成；设立'], englishDef: 'to be or be considered as something; to form or make something', example: 'Women constitute nearly half of the total workforce in many developed countries.', exampleTranslation: '在许多发达国家，女性构成了劳动力总数近一半。', exampleSource: '2021年阅读理解', level: 'high', root: 'stitut', affix: 'con-', synonyms: ['comprise', 'form', 'make up'], antonyms: [], collocations: ['constitute a threat', 'constitute the majority', 'constitute a violation'] },
  { id: 'h072', word: 'contemplate', phonetic: '/ˈkɒntəmpleɪt/', partOfSpeech: 'v.', meanings: ['沉思；凝视；打算'], englishDef: 'to think carefully about something for a long time; to consider', example: 'The author contemplates the meaning of happiness in modern society.', exampleTranslation: '作者在思考现代社会中幸福的意义。', exampleSource: '2019年翻译', level: 'high', root: 'templ', affix: 'con-', synonyms: ['consider', 'ponder', 'reflect'], antonyms: ['ignore', 'disregard'], collocations: ['contemplate the future', 'contemplate change', 'quietly contemplate'] },
  { id: 'h073', word: 'controversy', phonetic: '/ˈkɒntrəvɜːsi/', partOfSpeech: 'n.', meanings: ['争议；论战'], englishDef: 'a lot of disagreement or argument about something', example: 'The new education policy has sparked considerable controversy among parents and teachers.', exampleTranslation: '新的教育政策在家长和教师中引发了相当大的争议。', exampleSource: '2022年阅读理解', level: 'high', root: 'vers', affix: 'contro-', synonyms: ['dispute', 'debate', 'argument'], antonyms: ['agreement', 'consensus'], collocations: ['spark controversy', 'considerable controversy', 'subject of controversy'] },
  { id: 'h074', word: 'coordinate', phonetic: '/kəʊˈɔːdɪneɪt/', partOfSpeech: 'v./n.', meanings: ['协调；配合；坐标'], englishDef: 'to make various different things work effectively as a whole', example: 'International organizations need to coordinate their efforts to address global challenges.', exampleTranslation: '国际组织需要协调努力来应对全球性挑战。', exampleSource: '2020年翻译', level: 'high', root: 'ordin', affix: 'co-', synonyms: ['organize', 'harmonize', 'synchronize'], antonyms: ['disrupt', 'disorganize'], collocations: ['coordinate efforts', 'coordinate with', 'coordinate activities'] },
  { id: 'h075', word: 'deprive', phonetic: '/dɪˈpraɪv/', partOfSpeech: 'v.', meanings: ['剥夺；使丧失'], englishDef: 'to take something away from someone; to prevent someone from having something', example: 'Children deprived of early education often struggle throughout their academic careers.', exampleTranslation: '被剥夺早期教育的孩子往往在整个学术生涯中都在挣扎。', exampleSource: '2021年翻译', level: 'high', root: 'priv', affix: 'de-', synonyms: ['strip', 'dispossess', 'deny'], antonyms: ['provide', 'grant'], collocations: ['deprive of', 'be deprived of', 'deprive someone of'] },

  // ==================== 中频词汇 (mid) ====================
  { id: 'm001', word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', partOfSpeech: 'adj.', meanings: ['模糊的；含糊不清的'], englishDef: 'having more than one possible meaning; unclear', example: 'The instructions were ambiguous, leading to confusion among students.', exampleTranslation: '说明含糊不清，导致学生们困惑不已。', exampleSource: '2018年阅读理解', level: 'mid', root: 'ambi', synonyms: ['vague', 'unclear', 'equivocal'], antonyms: ['clear', 'unambiguous'], collocations: ['ambiguous language', 'ambiguous statement', 'deliberately ambiguous'] },
  { id: 'm002', word: 'analogy', phonetic: '/əˈnælədʒi/', partOfSpeech: 'n.', meanings: ['类比；类推'], englishDef: 'a comparison between things that have similar features', example: 'The author draws an analogy between the human brain and a computer.', exampleTranslation: '作者将人脑与计算机进行了类比。', exampleSource: '2020年翻译', level: 'mid', root: 'log', synonyms: ['comparison', 'parallel', 'similarity'], antonyms: [], collocations: ['draw an analogy', 'by analogy', 'analogy between'] },
  { id: 'm003', word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', partOfSpeech: 'adj.', meanings: ['任意的；武断的'], englishDef: 'based on random choice or personal whim, rather than any reason or system', example: 'The decision seemed arbitrary and lacked any rational basis.', exampleTranslation: '这个决定似乎很武断，缺乏任何理性基础。', exampleSource: '2019年阅读理解', level: 'mid', root: 'arbitr', synonyms: ['random', 'subjective', 'capricious'], antonyms: ['systematic', 'rational'], collocations: ['arbitrary decision', 'arbitrary rules', 'seem arbitrary'] },
  { id: 'm004', word: 'autonomous', phonetic: '/ɔːˈtɒnəməs/', partOfSpeech: 'adj.', meanings: ['自主的；自治的'], englishDef: 'having the ability to act independently; self-governing', example: 'Universities should remain autonomous in their academic decisions.', exampleTranslation: '大学在学术决策上应保持自主。', exampleSource: '2021年阅读理解', level: 'mid', root: 'nom', affix: 'auto-', synonyms: ['independent', 'self-governing', 'sovereign'], antonyms: ['dependent', 'controlled'], collocations: ['autonomous region', 'autonomous decision', 'fully autonomous'] },
  { id: 'm005', word: 'bureaucracy', phonetic: '/bjʊəˈrɒkrəsi/', partOfSpeech: 'n.', meanings: ['官僚主义；官僚体制'], englishDef: 'a system of government in which decisions are made by state officials', example: 'Excessive bureaucracy can hinder innovation and economic growth.', exampleTranslation: '过度的官僚主义会阻碍创新和经济增长。', exampleSource: '2022年阅读理解', level: 'mid', root: 'cracy', affix: 'bureau-', synonyms: ['administration', 'officialdom', 'red tape'], antonyms: [], collocations: ['government bureaucracy', 'reduce bureaucracy', 'excessive bureaucracy'] },
  { id: 'm006', word: 'coherent', phonetic: '/kəʊˈhɪərənt/', partOfSpeech: 'adj.', meanings: ['连贯的；一致的'], englishDef: 'logical and well-organized; easy to understand', example: 'Students should learn to write coherent essays with clear arguments.', exampleTranslation: '学生应该学会写具有清晰论点的连贯文章。', exampleSource: '2018年翻译', level: 'mid', root: 'her', affix: 'co-', synonyms: ['logical', 'consistent', 'systematic'], antonyms: ['incoherent', 'disjointed'], collocations: ['coherent argument', 'coherent policy', 'logically coherent'] },
  { id: 'm007', word: 'compatible', phonetic: '/kəmˈpætəbl/', partOfSpeech: 'adj.', meanings: ['兼容的；能共存的'], englishDef: 'able to exist or be used together without conflict', example: 'Economic growth and environmental protection are not necessarily incompatible.', exampleTranslation: '经济增长与环境保护并不一定不兼容。', exampleSource: '2020年阅读理解', level: 'mid', root: 'pati', affix: 'com-', synonyms: ['consistent', 'harmonious', 'congruous'], antonyms: ['incompatible', 'conflicting'], collocations: ['compatible with', 'fully compatible', 'mutually compatible'] },
  { id: 'm008', word: 'conceive', phonetic: '/kənˈsiːv/', partOfSpeech: 'v.', meanings: ['构想；设想；怀孕'], englishDef: 'to form an idea or plan in the mind', example: 'The project was conceived as a way to bridge the digital divide.', exampleTranslation: '该项目被构想为弥合数字鸿沟的一种方式。', exampleSource: '2019年翻译', level: 'mid', root: 'ceiv', affix: 'con-', synonyms: ['imagine', 'devise', 'formulate'], antonyms: [], collocations: ['conceive of', 'conceive the idea', 'newly conceived'] },
  { id: 'm009', word: 'consensus', phonetic: '/kənˈsensəs/', partOfSpeech: 'n.', meanings: ['共识；一致意见'], englishDef: 'a general agreement among a group of people', example: 'There is a growing consensus that action on climate change cannot be delayed.', exampleTranslation: '人们越来越达成共识，应对气候变化的行动不能再推迟。', exampleSource: '2021年阅读理解', level: 'mid', root: 'sens', affix: 'con-', synonyms: ['agreement', 'accord', 'unanimity'], antonyms: ['disagreement', 'conflict'], collocations: ['reach a consensus', 'broad consensus', 'growing consensus'] },
  { id: 'm010', word: 'contempt', phonetic: '/kənˈtempt/', partOfSpeech: 'n.', meanings: ['轻蔑；藐视'], englishDef: 'a strong feeling of disliking and having no respect for someone or something', example: 'He showed contempt for the traditional methods of teaching.', exampleTranslation: '他对传统的教学方法表现出轻蔑。', exampleSource: '2022年阅读理解', level: 'mid', root: 'tempt', affix: 'con-', synonyms: ['disdain', 'scorn', 'disrespect'], antonyms: ['respect', 'admiration'], collocations: ['hold in contempt', 'show contempt for', 'contempt of court'] },
  { id: 'm011', word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', partOfSpeech: 'v.', meanings: ['恶化；变质'], englishDef: 'to become worse', example: 'The air quality in many cities has deteriorated significantly over the past decade.', exampleTranslation: '过去十年间，许多城市的空气质量显著恶化。', exampleSource: '2019年阅读理解', level: 'mid', root: 'terior', affix: 'de-', synonyms: ['decline', 'worsen', 'degrade'], antonyms: ['improve', 'enhance'], collocations: ['deteriorate rapidly', 'continue to deteriorate', 'significantly deteriorate'] },
  { id: 'm012', word: 'discrepancy', phonetic: '/dɪˈskrepənsi/', partOfSpeech: 'n.', meanings: ['差异；不一致'], englishDef: 'a difference between things that should be the same', example: 'There is a noticeable discrepancy between what politicians promise and what they deliver.', exampleTranslation: '政客们的承诺与实际行动之间存在明显的差异。', exampleSource: '2020年翻译', level: 'mid', root: 'crep', affix: 'dis-', synonyms: ['difference', 'inconsistency', 'variance'], antonyms: ['consistency', 'agreement'], collocations: ['significant discrepancy', 'discrepancy between', 'noticeable discrepancy'] },
  { id: 'm013', word: 'elaborate', phonetic: '/ɪˈlæbərət/', partOfSpeech: 'adj./v.', meanings: ['精心的；详细阐述'], englishDef: 'containing a lot of careful detail; to give more details', example: 'Could you elaborate on your proposal for the new curriculum?', exampleTranslation: '你能详细阐述一下你关于新课程的提案吗？', exampleSource: '2021年完形填空', level: 'mid', root: 'labor', affix: 'e-', synonyms: ['detailed', 'intricate', 'complex'], antonyms: ['simple', 'basic'], collocations: ['elaborate on', 'elaborate plan', 'elaborate design'] },
  { id: 'm014', word: 'endeavor', phonetic: '/ɪnˈdevər/', partOfSpeech: 'n./v.', meanings: ['努力；尝试；事业'], englishDef: 'an attempt to do something, especially something new or difficult', example: 'Scientific endeavor requires patience, dedication, and rigorous methodology.', exampleTranslation: '科学事业需要耐心、奉献精神和严谨的方法论。', exampleSource: '2018年翻译', level: 'mid', root: 'deavor', affix: 'en-', synonyms: ['effort', 'attempt', 'undertaking'], antonyms: [], collocations: ['endeavor to', 'scientific endeavor', 'human endeavor'] },
  { id: 'm015', word: 'facet', phonetic: '/ˈfæsɪt/', partOfSpeech: 'n.', meanings: ['方面；侧面；刻面'], englishDef: 'one part of a subject, situation, etc. that has many parts', example: 'Technology influences almost every facet of modern life.', exampleTranslation: '技术影响着现代生活的几乎每一个方面。', exampleSource: '2022年阅读理解', level: 'mid', root: 'fac', synonyms: ['aspect', 'dimension', 'element'], antonyms: [], collocations: ['every facet of', 'important facet', 'multiple facets'] },
  { id: 'm016', word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', partOfSpeech: 'v.', meanings: ['波动；变动'], englishDef: 'to change or vary frequently in amount or level', example: 'Oil prices fluctuate significantly due to geopolitical events.', exampleTranslation: '由于地缘政治事件，石油价格大幅波动。', exampleSource: '2020年阅读理解', level: 'mid', root: 'fluct', affix: '-uate', synonyms: ['vary', 'oscillate', 'swing'], antonyms: ['stabilize', 'steady'], collocations: ['fluctuate between', 'fluctuate widely', 'prices fluctuate'] },
  { id: 'm017', word: 'gratitude', phonetic: '/ˈɡrætɪtjuːd/', partOfSpeech: 'n.', meanings: ['感激；感谢'], englishDef: 'the feeling or quality of being grateful', example: 'She expressed her gratitude to all the teachers who had supported her.', exampleTranslation: '她对所有支持过她的老师表达了感激之情。', exampleSource: '2019年完形填空', level: 'mid', root: 'grat', affix: '-itude', synonyms: ['thankfulness', 'appreciation'], antonyms: ['ingratitude', 'ungratefulness'], collocations: ['express gratitude', 'deep gratitude', 'with gratitude'] },
  { id: 'm018', word: 'hypothesis', phonetic: '/haɪˈpɒθəsɪs/', partOfSpeech: 'n.', meanings: ['假设；假说'], englishDef: 'an idea or explanation for something that is based on known facts but has not yet been proved', example: 'The researchers tested the hypothesis that sleep deprivation affects decision-making.', exampleTranslation: '研究人员测试了睡眠不足影响决策的假设。', exampleSource: '2021年阅读理解', level: 'mid', root: 'thesis', affix: 'hypo-', synonyms: ['theory', 'assumption', 'proposition'], antonyms: ['fact', 'proof'], collocations: ['test the hypothesis', 'research hypothesis', 'support the hypothesis'] },
  { id: 'm019', word: 'illuminate', phonetic: '/ɪˈluːmɪneɪt/', partOfSpeech: 'v.', meanings: ['照亮；阐明'], englishDef: 'to light something up; to make something clear or easier to understand', example: 'The study illuminates the complex relationship between poverty and educational outcomes.', exampleTranslation: '该研究阐明了贫困与教育成果之间的复杂关系。', exampleSource: '2022年翻译', level: 'mid', root: 'lumin', affix: 'il-', synonyms: ['light up', 'clarify', 'explain'], antonyms: ['darken', 'obscure'], collocations: ['illuminate the issue', 'illuminate the relationship', 'newly illuminate'] },
  { id: 'm020', word: 'imperative', phonetic: '/ɪmˈperətɪv/', partOfSpeech: 'adj./n.', meanings: ['必要的；紧迫的；祈使语气'], englishDef: 'extremely important or urgent; essential', example: 'It is imperative that we take action now to protect the environment.', exampleTranslation: '我们现在就采取行动保护环境是至关重要的。', exampleSource: '2018年翻译', level: 'mid', root: 'per', affix: 'im-', synonyms: ['crucial', 'vital', 'essential'], antonyms: ['optional', 'dispensable'], collocations: ['it is imperative', 'moral imperative', 'absolutely imperative'] },

  // ==================== 低频词汇 (low) ====================
  { id: 'l001', word: 'aberration', phonetic: '/ˌæbəˈreɪʃən/', partOfSpeech: 'n.', meanings: ['偏差；异常行为'], englishDef: 'a temporary change from the typical or usual way of behaving', example: 'The warm winter was an aberration in the region\'s climate pattern.', exampleTranslation: '温暖的冬天是该地区气候模式的一个异常。', exampleSource: '2020年阅读理解', level: 'low', root: 'err', affix: 'ab-', synonyms: ['anomaly', 'deviation', 'irregularity'], antonyms: ['norm', 'standard'], collocations: ['statistical aberration', 'genetic aberration', 'mere aberration'] },
  { id: 'l002', word: 'acquiesce', phonetic: '/ˌækwiˈes/', partOfSpeech: 'v.', meanings: ['默认；勉强同意'], englishDef: 'to accept or agree to something, often reluctantly', example: 'The board acquiesced to the demands of the shareholders.', exampleTranslation: '董事会默认了股东们的要求。', exampleSource: '2019年阅读理解', level: 'low', root: 'quiet', affix: 'ac-', synonyms: ['accept', 'consent', 'comply'], antonyms: ['resist', 'oppose'], collocations: ['acquiesce to', 'acquiesce in', 'reluctantly acquiesce'] },
  { id: 'l003', word: 'bolster', phonetic: '/ˈbəʊlstər/', partOfSpeech: 'v.', meanings: ['支持；加强'], englishDef: 'to support or improve something or make it stronger', example: 'New evidence has bolstered the theory that the universe is expanding at an accelerating rate.', exampleTranslation: '新证据加强了宇宙正在加速膨胀的理论。', exampleSource: '2021年阅读理解', level: 'low', synonyms: ['strengthen', 'support', 'reinforce'], antonyms: ['undermine', 'weaken'], collocations: ['bolster confidence', 'bolster the economy', 'bolster the argument'] },
  { id: 'l004', word: 'cacophony', phonetic: '/kəˈkɒfəni/', partOfSpeech: 'n.', meanings: ['刺耳的声音；不和谐'], englishDef: 'an unpleasant mixture of loud sounds', example: 'The cacophony of city traffic can have negative effects on mental health.', exampleTranslation: '城市交通的嘈杂声可能对心理健康产生负面影响。', exampleSource: '2022年阅读理解', level: 'low', root: 'phon', affix: 'caco-', synonyms: ['noise', 'discord', 'clamor'], antonyms: ['harmony', 'melody'], collocations: ['cacophony of', 'loud cacophony'] },
  { id: 'l005', word: 'delineate', phonetic: '/dɪˈlɪnieɪt/', partOfSpeech: 'v.', meanings: ['描绘；描述；勾画'], englishDef: 'to describe or mark the edge of something; to show its shape', example: 'The report delineates the key challenges facing the education sector.', exampleTranslation: '报告描绘了教育部门面临的关键挑战。', exampleSource: '2020年翻译', level: 'low', root: 'line', affix: 'de-', synonyms: ['outline', 'describe', 'define'], antonyms: [], collocations: ['clearly delineate', 'delineate the boundaries', 'delineate between'] },
  { id: 'l006', word: 'ebullient', phonetic: '/ɪˈbʌliənt/', partOfSpeech: 'adj.', meanings: ['热情洋溢的；兴高采烈的'], englishDef: 'very happy and energetic', example: 'The ebullient response from the crowd showed their support for the initiative.', exampleTranslation: '人群热情洋溢的反应表明他们对这一倡议的支持。', exampleSource: '2018年阅读理解', level: 'low', root: 'bull', affix: 'e-', synonyms: ['enthusiastic', 'exuberant', 'joyful'], antonyms: ['gloomy', 'melancholy'], collocations: ['ebullient mood', 'ebullient personality'] },
  { id: 'l007', word: 'foment', phonetic: '/fəˈment/', partOfSpeech: 'v.', meanings: ['煽动；引发'], englishDef: 'to cause trouble and make people start fighting each other', example: 'Social media can foment discord if not used responsibly.', exampleTranslation: '如果不负责任地使用，社交媒体可能煽动不和。', exampleSource: '2021年阅读理解', level: 'low', root: 'foment', synonyms: ['incite', 'stir up', 'provoke'], antonyms: ['calm', 'pacify'], collocations: ['foment discord', 'foment rebellion', 'foment tension'] },
  { id: 'l008', word: 'gregarious', phonetic: '/ɡrɪˈɡeəriəs/', partOfSpeech: 'adj.', meanings: ['爱交际的；群居的'], englishDef: 'liking to be with other people; sociable', example: 'Humans are naturally gregarious creatures who thrive on social interaction.', exampleTranslation: '人类天生是群居动物，在社交互动中茁壮成长。', exampleSource: '2019年翻译', level: 'low', root: 'greg', affix: '-arious', synonyms: ['sociable', 'outgoing', 'extroverted'], antonyms: ['solitary', 'introverted'], collocations: ['gregarious personality', 'gregarious nature'] },
  { id: 'l009', word: 'hegemony', phonetic: '/hɪˈɡeməni/', partOfSpeech: 'n.', meanings: ['霸权；支配地位'], englishDef: 'leadership or control, especially by one country or organization over others', example: 'The hegemony of English as a global language has both advantages and disadvantages.', exampleTranslation: '英语作为全球语言的霸权既有优势也有劣势。', exampleSource: '2022年翻译', level: 'low', root: 'heg', affix: '-emony', synonyms: ['dominance', 'supremacy', 'authority'], antonyms: [], collocations: ['cultural hegemony', 'political hegemony', 'maintain hegemony'] },
  { id: 'l010', word: 'idiosyncratic', phonetic: '/ˌɪdiəsɪŋˈkrætɪk/', partOfSpeech: 'adj.', meanings: ['独特的；特异的'], englishDef: 'peculiar or individual in nature', example: 'Each culture has its idiosyncratic approach to education and learning.', exampleTranslation: '每种文化都有其独特的教育和学习方法。', exampleSource: '2020年阅读理解', level: 'low', root: 'syncr', affix: 'idio-', synonyms: ['unique', 'distinctive', 'peculiar'], antonyms: ['typical', 'ordinary'], collocations: ['idiosyncratic style', 'idiosyncratic behavior'] },
];

// 合并扩展词库
export const WORDS: Word[] = [..._BASE_WORDS, ...WORDS_H076_H175, ...WORDS_M021_M120, ...WORDS_L011_L110, ...WORDS_H176_H275, ...WORDS_H276_H375, ...WORDS_M121_M220, ...WORDS_M221_M320, ...WORDS_L111_L210, ...WORDS_H376_H500, ...WORDS_M321_M420, ...WORDS_M421_M550, ...WORDS_L211_L310, ...WORDS_L311_L410, ...WORDS_L411_L450, ...WORDS_H501_H540, ...WORDS_H541_H600, ...WORDS_H601_H670, ...WORDS_M551_M650, ...WORDS_M651_M730, ...WORDS_L451_L550, ...WORDS_L551_L600, ...WORDS_H671_H750, ...WORDS_H751_H840, ...WORDS_M731_M820, ...WORDS_M821_M910, ...WORDS_L601_L700, ...WORDS_L701_L750, ...WORDS_H841_H930, ...WORDS_H931_H1022, ...WORDS_M911_M1000, ...WORDS_M1001_M1092, ...WORDS_L750_L840, ...WORDS_L841_L932, ...WORDS_H1023_H1114, ...WORDS_NEW_01, ...WORDS_NEW_02, ...WORDS_NEW_03, ...WORDS_NEW_04, ...WORDS_NEW_05, ...WORDS_NEW_06, ...WORDS_NEW_07, ...WORDS_NEW_08, ...WORDS_NEW_09, ...WORDS_NEW_10, ...WORDS_NEW_11, ...WORDS_NEW_12, ...WORDS_NEW_13];

/** 按等级分组获取单词 */
export function getWordsByLevel(level: 'high' | 'mid' | 'low'): Word[] {
  return WORDS.filter(w => w.level === level);
}

/** 按词根搜索 */
export function getWordsByRoot(root: string): Word[] {
  return WORDS.filter(w => w.root === root);
}

/** 搜索单词 */
export function searchWords(query: string): Word[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return WORDS.filter(w =>
    w.word.toLowerCase().includes(q) ||
    w.meanings.some(m => m.includes(q)) ||
    (w.root && w.root.includes(q))
  );
}

/** 获取所有单词ID集合 */
export function getAllWordIds(): string[] {
  return WORDS.map(w => w.id);
}

/** 按ID获取单词 */
export function getWordById(id: string): Word | undefined {
  return WORDS.find(w => w.id === id);
}

/** 统计各级别词数 */
export function getWordCounts(): { high: number; mid: number; low: number; total: number } {
  return {
    high: WORDS.filter(w => w.level === 'high').length,
    mid: WORDS.filter(w => w.level === 'mid').length,
    low: WORDS.filter(w => w.level === 'low').length,
    total: WORDS.length,
  };
}
