// ============================================================
// 考研英语核心词库 - 高频词汇 h501-h540
// 40个高频考研英语词汇
// ============================================================

import type { Word } from './types';

export const WORDS_H501_H540: Word[] = [
  { id: 'h501', word: 'convention', phonetic: '/kənˈvenʃn/', partOfSpeech: 'n.', meanings: ['惯例；大会；公约'], englishDef: 'a way in which something is usually done; a large meeting; an official agreement', example: 'By convention, the Prime Minister addresses Parliament at the start of each session.', exampleTranslation: '按照惯例，首相在每届议会开始时发表演说。', exampleSource: '2019年翻译', level: 'high', root: 'vent', affix: 'con-', synonyms: ['tradition', 'custom', 'practice'], antonyms: ['innovation', 'deviation'], collocations: ['by convention', 'international convention', 'social convention'] },
  { id: 'h502', word: 'convey', phonetic: '/kənˈveɪ/', partOfSpeech: 'v.', meanings: ['传达；运送；表达'], englishDef: 'to communicate information or feelings; to transport', example: 'The author conveys a deep sense of loss through the use of metaphor and imagery.', exampleTranslation: '作者通过比喻和意象传达了深深的失落感。', exampleSource: '2021年翻译', level: 'high', root: 'vey', affix: 'con-', synonyms: ['communicate', 'express', 'transmit'], antonyms: ['conceal', 'suppress'], collocations: ['convey the message', 'convey meaning', 'clearly convey'] },
  { id: 'h503', word: 'cognitive', phonetic: '/ˈkɒɡnətɪv/', partOfSpeech: 'adj.', meanings: ['认知的；认识的'], englishDef: 'connected with mental processes of understanding, reasoning, and learning', example: 'Research shows that bilingualism can enhance cognitive flexibility in children.', exampleTranslation: '研究表明，双语能力可以增强儿童的认知灵活性。', exampleSource: '2022年阅读理解', level: 'high', root: 'cogn', affix: '-itive', synonyms: ['mental', 'intellectual', 'perceptual'], antonyms: ['physical', 'emotional'], collocations: ['cognitive development', 'cognitive ability', 'cognitive process'] },
  { id: 'h504', word: 'decline', phonetic: '/dɪˈklaɪn/', partOfSpeech: 'v./n.', meanings: ['下降；衰退；婉拒'], englishDef: 'to become smaller or lower; to politely refuse', example: 'The decline in reading habits among young people has raised concerns among educators.', exampleTranslation: '年轻人阅读习惯的下降引起了教育工作者的担忧。', exampleSource: '2020年阅读理解', level: 'high', root: 'clin', affix: 'de-', synonyms: ['decrease', 'deteriorate', 'drop'], antonyms: ['increase', 'improve'], collocations: ['sharp decline', 'decline in', 'steady decline'] },
  { id: 'h505', word: 'proportion', phonetic: '/prəˈpɔːʃn/', partOfSpeech: 'n.', meanings: ['比例；部分；均衡'], englishDef: 'a part or share of a whole; the relationship between different parts', example: 'A large proportion of college graduates find it difficult to secure employment in their field.', exampleTranslation: '很大一部分大学毕业生发现在本专业领域找到工作很困难。', exampleSource: '2019年阅读理解', level: 'high', root: 'port', affix: 'pro-', synonyms: ['ratio', 'percentage', 'fraction'], antonyms: [], collocations: ['large proportion', 'in proportion to', 'disproportionate'] },
  { id: 'h506', word: 'formulate', phonetic: '/ˈfɔːmjuleɪt/', partOfSpeech: 'v.', meanings: ['制定；构想；系统阐述'], englishDef: 'to develop or create a plan, system, or idea carefully', example: 'The government needs to formulate new policies to address the growing housing crisis.', exampleTranslation: '政府需要制定新政策来应对日益严重的住房危机。', exampleSource: '2021年翻译', level: 'high', root: 'form', affix: '-ulate', synonyms: ['develop', 'devise', 'draft'], antonyms: ['abandon', 'discard'], collocations: ['formulate a policy', 'formulate a plan', 'carefully formulate'] },
  { id: 'h507', word: 'indicate', phonetic: '/ˈɪndɪkeɪt/', partOfSpeech: 'v.', meanings: ['表明；暗示；指出'], englishDef: 'to show or point out something; to be a sign of', example: 'Recent studies indicate that remote work can improve employee productivity and satisfaction.', exampleTranslation: '最近的研究表明，远程工作可以提高员工的生产力和满意度。', exampleSource: '2022年阅读理解', level: 'high', root: 'dic', affix: 'in-', synonyms: ['show', 'suggest', 'reveal'], antonyms: ['conceal', 'hide'], collocations: ['indicate that', 'clearly indicate', 'studies indicate'] },
  { id: 'h508', word: 'integrate', phonetic: '/ˈɪntɪɡreɪt/', partOfSpeech: 'v.', meanings: ['整合；融入；使一体化'], englishDef: 'to combine two or more things so that they work together', example: 'Schools should integrate technology into the curriculum to prepare students for the digital age.', exampleTranslation: '学校应将技术融入课程，为学生进入数字时代做好准备。', exampleSource: '2020年翻译', level: 'high', root: 'tegr', affix: 'in-', synonyms: ['incorporate', 'combine', 'unify'], antonyms: ['separate', 'isolate'], collocations: ['integrate into', 'integrate with', 'fully integrate'] },
  { id: 'h509', word: 'massive', phonetic: '/ˈmæsɪv/', partOfSpeech: 'adj.', meanings: ['巨大的；大规模的；严重的'], englishDef: 'extremely large in scale, amount, or degree', example: 'The massive influx of rural workers into cities has transformed the demographic landscape.', exampleTranslation: '大量农村工人涌入城市，改变了人口格局。', exampleSource: '2018年阅读理解', level: 'high', root: 'mass', affix: '-ive', synonyms: ['enormous', 'substantial', 'immense'], antonyms: ['tiny', 'minimal'], collocations: ['massive scale', 'massive change', 'massive investment'] },
  { id: 'h510', word: 'precise', phonetic: '/prɪˈsaɪs/', partOfSpeech: 'adj.', meanings: ['精确的；准确的；严谨的'], englishDef: 'exact and accurate; clearly stated', example: 'The precise reasons for the decline in biodiversity remain a subject of scientific debate.', exampleTranslation: '生物多样性下降的确切原因仍是科学界争论的话题。', exampleSource: '2021年阅读理解', level: 'high', root: 'cis', affix: 'pre-', synonyms: ['exact', 'accurate', 'specific'], antonyms: ['vague', 'approximate'], collocations: ['precise measurement', 'precise definition', 'more precise'] },
  { id: 'h511', word: 'inevitably', phonetic: '/ɪnˈevɪtəbli/', partOfSpeech: 'adv.', meanings: ['不可避免地；必然地'], englishDef: 'in a way that cannot be avoided or prevented', example: 'As populations age, governments will inevitably face increased pressure on healthcare systems.', exampleTranslation: '随着人口老龄化，各国政府不可避免地将面临医疗体系日益增加的压力。', exampleSource: '2022年翻译', level: 'high', root: 'evit', affix: 'in--ably', synonyms: ['unavoidably', 'necessarily', 'inescapably'], antonyms: ['avoidably', 'optionally'], collocations: ['inevitably lead to', 'almost inevitably', 'seem inevitably'] },
  { id: 'h512', word: 'conscience', phonetic: '/ˈkɒnʃəns/', partOfSpeech: 'n.', meanings: ['良知；良心；道德感'], englishDef: 'the part of the mind that tells you whether your actions are right or wrong', example: 'Environmental scientists argue that we have a moral conscience to protect the planet for future generations.', exampleTranslation: '环境科学家认为，为了子孙后代保护地球是我们的道德良知。', exampleSource: '2020年完形填空', level: 'high', root: 'sci', affix: 'con-', synonyms: ['morality', 'sense of right and wrong', 'ethics'], antonyms: ['immorality'], collocations: ['social conscience', 'clear conscience', 'guilty conscience'] },
  { id: 'h513', word: 'dwelling', phonetic: '/ˈdwelɪŋ/', partOfSpeech: 'n.', meanings: ['住所；住宅；居住地'], englishDef: 'a house, apartment, or other place of residence', example: 'The quality of one\'s dwelling has a direct impact on physical and mental well-being.', exampleTranslation: '住所的质量直接影响人的身心健康。', exampleSource: '2019年阅读理解', level: 'high', root: 'dwell', affix: '-ing', synonyms: ['residence', 'habitation', 'accommodation'], antonyms: [], collocations: ['dwelling place', 'human dwelling', 'rural dwelling'] },
  { id: 'h514', word: 'prevalent', phonetic: '/ˈprevələnt/', partOfSpeech: 'adj.', meanings: ['流行的；普遍的；盛行的'], englishDef: 'widespread in a particular area or at a particular time', example: 'Obesity has become increasingly prevalent among children in developed countries.', exampleTranslation: '在发达国家，儿童肥胖问题日益普遍。', exampleSource: '2021年阅读理解', level: 'high', root: 'val', affix: 'pre-', synonyms: ['widespread', 'common', 'prevailing'], antonyms: ['rare', 'uncommon'], collocations: ['increasingly prevalent', 'most prevalent', 'highly prevalent'] },
  { id: 'h515', word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', partOfSpeech: 'v.', meanings: ['减少；削弱；贬低'], englishDef: 'to become or make something smaller or less important', example: 'The role of traditional media has not diminished despite the rise of social platforms.', exampleTranslation: '尽管社交媒体兴起，传统媒体的角色并没有被削弱。', exampleSource: '2022年阅读理解', level: 'high', root: 'min', affix: 'di-', synonyms: ['reduce', 'decrease', 'lessen'], antonyms: ['increase', 'enhance'], collocations: ['diminish the importance', 'significantly diminish', 'gradually diminish'] },
  { id: 'h516', word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', partOfSpeech: 'n.', meanings: ['获取；习得；收购'], englishDef: 'the process of getting something; the learning of a skill or knowledge', example: 'Language acquisition is most effective when learners are immersed in authentic communicative contexts.', exampleTranslation: '当学习者沉浸在真实的交流环境中时，语言习得最为有效。', exampleSource: '2018年翻译', level: 'high', root: 'quire', affix: 'ac-', synonyms: ['obtainment', 'attainment', 'procurement'], antonyms: ['loss', 'forfeiture'], collocations: ['language acquisition', 'knowledge acquisition', 'mergers and acquisitions'] },
  { id: 'h517', word: 'dilemma', phonetic: '/dɪˈlemə/', partOfSpeech: 'n.', meanings: ['困境；两难；进退维谷'], englishDef: 'a situation in which a difficult choice has to be made between two or more alternatives', example: 'Policymakers face a dilemma between promoting economic growth and protecting the environment.', exampleTranslation: '决策者在促进经济增长与保护环境之间面临两难抉择。', exampleSource: '2020年阅读理解', level: 'high', root: 'lemma', affix: 'di-', synonyms: ['predicament', 'quandary', 'impasse'], antonyms: [], collocations: ['face a dilemma', 'ethical dilemma', 'moral dilemma'] },
  { id: 'h518', word: 'deprive', phonetic: '/dɪˈpraɪv/', partOfSpeech: 'v.', meanings: ['剥夺；使丧失'], englishDef: 'to take something away from someone; to prevent someone from having something', example: 'Poverty deprives millions of children of the opportunity to receive a proper education.', exampleTranslation: '贫困剥夺了数百万儿童接受正规教育的机会。', exampleSource: '2019年翻译', level: 'high', root: 'priv', affix: 'de-', synonyms: ['strip', 'dispossess', 'deny'], antonyms: ['provide', 'grant'], collocations: ['deprive of', 'be deprived of', 'deprive someone of'] },
  { id: 'h519', word: 'exceed', phonetic: '/ɪkˈsiːd/', partOfSpeech: 'v.', meanings: ['超过；超越；超出'], englishDef: 'to be greater than a particular number or amount; to go beyond', example: 'Global carbon emissions have exceeded the levels predicted by earlier climate models.', exampleTranslation: '全球碳排放已经超过了早期气候模型预测的水平。', exampleSource: '2022年阅读理解', level: 'high', root: 'ceed', affix: 'ex-', synonyms: ['surpass', 'outstrip', 'transcend'], antonyms: ['fall short', 'underachieve'], collocations: ['exceed expectations', 'exceed the limit', 'significantly exceed'] },
  { id: 'h520', word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', partOfSpeech: 'adj.', meanings: ['邻近的；毗连的'], englishDef: 'next to or near something', example: 'The adjacent neighborhoods experienced dramatically different levels of economic development.', exampleTranslation: '相邻的社区经历了截然不同的经济发展水平。', exampleSource: '2021年阅读理解', level: 'high', root: 'jac', affix: 'ad-', synonyms: ['neighboring', 'nearby', 'adjoining'], antonyms: ['distant', 'remote'], collocations: ['adjacent to', 'adjacent area', 'adjacent region'] },
  { id: 'h521', word: 'conceive', phonetic: '/kənˈsiːv/', partOfSpeech: 'v.', meanings: ['构想；设想；怀孕'], englishDef: 'to form an idea or plan in the mind; to become pregnant', example: 'It is hard to conceive of a future in which artificial intelligence does not play a central role in daily life.', exampleTranslation: '很难想象一个在未来人工智能不在日常生活中扮演核心角色的世界。', exampleSource: '2023年翻译', level: 'high', root: 'ceiv', affix: 'con-', synonyms: ['imagine', 'envision', 'devise'], antonyms: ['disbelieve', 'dismiss'], collocations: ['conceive of', 'conceive the idea', 'difficult to conceive'] },
  { id: 'h522', word: 'complement', phonetic: '/ˈkɒmplɪment/', partOfSpeech: 'v./n.', meanings: ['补充；使完善；补语'], englishDef: 'to add to something to make it better; something that completes', example: 'Practical experience complements theoretical knowledge and prepares students for real-world challenges.', exampleTranslation: '实践经验补充了理论知识，使学生为现实世界的挑战做好准备。', exampleSource: '2020年完形填空', level: 'high', root: 'ple', affix: 'com-', synonyms: ['supplement', 'enhance', 'complete'], antonyms: ['contradict', 'clash'], collocations: ['complement each other', 'complement the theory', 'perfect complement'] },
  { id: 'h523', word: 'constraint', phonetic: '/kənˈstreɪnt/', partOfSpeech: 'n.', meanings: ['约束；限制；强制'], englishDef: 'a limitation or restriction; something that controls what you can do', example: 'Budget constraints have forced many universities to reduce the number of courses they offer.', exampleTranslation: '预算限制迫使许多大学减少课程开设数量。', exampleSource: '2022年阅读理解', level: 'high', root: 'strain', affix: 'con-', synonyms: ['restriction', 'limitation', 'restraint'], antonyms: ['freedom', 'liberty'], collocations: ['budget constraint', 'under constraint', 'time constraint'] },
  { id: 'h524', word: 'devote', phonetic: '/dɪˈvəʊt/', partOfSpeech: 'v.', meanings: ['致力于；奉献；投入'], englishDef: 'to give all of something, especially time or effort, to a particular activity', example: 'The professor devoted his entire career to studying the effects of climate change on marine ecosystems.', exampleTranslation: '这位教授将毕生精力致力于研究气候变化对海洋生态系统的影响。', exampleSource: '2019年翻译', level: 'high', root: 'vot', affix: 'de-', synonyms: ['dedicate', 'commit', 'allocate'], antonyms: ['neglect', 'abandon'], collocations: ['devote to', 'devote time to', 'devote oneself to'] },
  { id: 'h525', word: 'intensive', phonetic: '/ɪnˈtensɪv/', partOfSpeech: 'adj.', meanings: ['密集的；集约的；强化的'], englishDef: 'involving a lot of effort or activity in a short period of time', example: 'Intensive reading programs have proven effective in improving students\' comprehension skills.', exampleTranslation: '强化阅读项目已被证明在提高学生理解能力方面是有效的。', exampleSource: '2021年阅读理解', level: 'high', root: 'tens', affix: 'in-', synonyms: ['concentrated', 'rigorous', 'thorough'], antonyms: ['extensive', 'superficial'], collocations: ['intensive care', 'intensive training', 'labor-intensive'] },
  { id: 'h526', word: 'legislation', phonetic: '/ˌledʒɪsˈleɪʃn/', partOfSpeech: 'n.', meanings: ['立法；法律；法规'], englishDef: 'a law or set of laws suggested by a government and made official by a parliament', example: 'New legislation has been introduced to regulate the use of personal data by technology companies.', exampleTranslation: '新法规已被引入以规范科技公司对个人数据的使用。', exampleSource: '2023年阅读理解', level: 'high', root: 'leg', affix: '-islation', synonyms: ['law', 'statute', 'regulation'], antonyms: [], collocations: ['introduce legislation', 'new legislation', 'environmental legislation'] },
  { id: 'h527', word: 'predict', phonetic: '/prɪˈdɪkt/', partOfSpeech: 'v.', meanings: ['预测；预言；预告'], englishDef: 'to say or estimate that something will happen in the future', example: 'Experts predict that automation will displace millions of jobs within the next two decades.', exampleTranslation: '专家预测，自动化将在未来二十年内取代数以百万计的工作岗位。', exampleSource: '2020年阅读理解', level: 'high', root: 'dict', affix: 'pre-', synonyms: ['forecast', 'foresee', 'project'], antonyms: ['retrospect'], collocations: ['predict that', 'difficult to predict', 'accurately predict'] },
  { id: 'h528', word: 'practically', phonetic: '/ˈpræktɪkli/', partOfSpeech: 'adv.', meanings: ['几乎；实际上； practically'], englishDef: 'almost; in a practical way; virtually', example: 'The new regulation is practically impossible to enforce without significant additional resources.', exampleTranslation: '如果没有大量额外的资源，这项新法规几乎不可能执行。', exampleSource: '2022年完形填空', level: 'high', root: 'pract', affix: '-ically', synonyms: ['almost', 'virtually', 'nearly'], antonyms: ['theoretically'], collocations: ['practically impossible', 'practically every', 'practically all'] },
  { id: 'h529', word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', partOfSpeech: 'v.', meanings: ['补偿；弥补；赔偿'], englishDef: 'to provide something good to balance or reduce the bad effects of something', example: 'The government has introduced measures to compensate workers who lost their jobs due to automation.', exampleTranslation: '政府已出台措施，补偿因自动化而失去工作的工人。', exampleSource: '2021年翻译', level: 'high', root: 'pens', affix: 'com-', synonyms: ['reimburse', 'make up for', 'recompense'], antonyms: ['penalize', 'deprive'], collocations: ['compensate for', 'compensate the loss', 'adequately compensate'] },
  { id: 'h530', word: 'discipline', phonetic: '/ˈdɪsəplɪn/', partOfSpeech: 'n./v.', meanings: ['学科；纪律；训练'], englishDef: 'a branch of knowledge; the practice of training people to obey rules', example: 'Interdisciplinary research that crosses traditional discipline boundaries has become increasingly important.', exampleTranslation: '跨越传统学科边界的跨学科研究变得越来越重要。', exampleSource: '2019年阅读理解', level: 'high', root: 'discip', affix: '-line', synonyms: ['field', 'subject', 'self-control'], antonyms: ['indiscipline'], collocations: ['academic discipline', 'strict discipline', 'self-discipline'] },
  { id: 'h531', word: 'empirical', phonetic: '/ɪmˈpɪrɪkl/', partOfSpeech: 'adj.', meanings: ['经验的；实证的；以经验为依据的'], englishDef: 'based on what is experienced or seen rather than on theory', example: 'The study provides empirical evidence that early childhood education has long-lasting benefits.', exampleTranslation: '该研究提供了实证证据，表明早期儿童教育具有长期益处。', exampleSource: '2022年翻译', level: 'high', root: 'pir', affix: 'em-', synonyms: ['experimental', 'observed', 'practical'], antonyms: ['theoretical', 'hypothetical'], collocations: ['empirical evidence', 'empirical research', 'empirical data'] },
  { id: 'h532', word: 'exclusive', phonetic: '/ɪkˈskluːsɪv/', partOfSpeech: 'adj.', meanings: ['独占的；排他的；专有的'], englishDef: 'limited to only one person or group; not shared with others', example: 'Elite universities have been criticized for being too exclusive and inaccessible to students from disadvantaged backgrounds.', exampleTranslation: '精英大学因过于排他、对弱势背景的学生不够开放而受到批评。', exampleSource: '2020年阅读理解', level: 'high', root: 'clus', affix: 'ex-', synonyms: ['selective', 'restricted', 'sole'], antonyms: ['inclusive', 'accessible'], collocations: ['exclusive right', 'mutually exclusive', 'exclusive access'] },
  { id: 'h533', word: 'conscience', phonetic: '/ˈkɒnʃəns/', partOfSpeech: 'n.', meanings: ['良知；良心；道德感'], englishDef: 'the part of the mind that tells you whether your actions are right or wrong', example: 'Citizens should cultivate a social conscience that extends beyond individual interests.', exampleTranslation: '公民应培养超越个人利益的社会良知。', exampleSource: '2023年完形填空', level: 'high', root: 'sci', affix: 'con-', synonyms: ['morality', 'ethics', 'sense of right'], antonyms: ['indifference'], collocations: ['social conscience', 'moral conscience', 'conscience of society'] },
  { id: 'h534', word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', partOfSpeech: 'v.', meanings: ['夸大；夸张'], englishDef: 'to make something seem larger, better, or worse than it really is', example: 'The media tends to exaggerate the risks associated with new technologies, creating unnecessary public anxiety.', exampleTranslation: '媒体倾向于夸大新技术相关的风险，造成不必要的公众焦虑。', exampleSource: '2021年阅读理解', level: 'high', root: 'agger', affix: 'ex-', synonyms: ['overstate', 'magnify', 'embellish'], antonyms: ['understate', 'minimize'], collocations: ['exaggerate the importance', 'tend to exaggerate', 'greatly exaggerate'] },
  { id: 'h535', word: 'contend', phonetic: '/kənˈtend/', partOfSpeech: 'v.', meanings: ['竞争；争辩；应对'], englishDef: 'to compete or struggle for something; to argue or claim', example: 'Critics contend that the new law will disproportionately affect low-income communities.', exampleTranslation: '批评者争辩说，新法律将对低收入社区产生不成比例的影响。', exampleSource: '2022年阅读理解', level: 'high', root: 'tend', affix: 'con-', synonyms: ['argue', 'assert', 'compete'], antonyms: ['concede', 'yield'], collocations: ['contend that', 'contend with', 'widely contended'] },
  { id: 'h536', word: 'stimulus', phonetic: '/ˈstɪmjələs/', partOfSpeech: 'n.', meanings: ['刺激；激励；刺激物'], englishDef: 'something that causes a reaction in a living thing; something that encourages activity', example: 'Government stimulus packages were introduced to revive the economy after the recession.', exampleTranslation: '经济衰退后，政府推出了刺激计划以振兴经济。', exampleSource: '2020年阅读理解', level: 'high', root: 'stimul', affix: '-us', synonyms: ['incentive', 'catalyst', 'motivation'], antonyms: ['deterrent', 'obstacle'], collocations: ['economic stimulus', 'stimulus package', 'external stimulus'] },
  { id: 'h537', word: 'prestige', phonetic: '/preˈstiːʒ/', partOfSpeech: 'n.', meanings: ['声望；威望；声誉'], englishDef: 'respect and admiration given to someone or something based on their achievements', example: 'A degree from a university of international prestige can significantly enhance one\'s career prospects.', exampleTranslation: '拥有国际声誉的大学学位可以显著提升个人的职业前景。', exampleSource: '2019年翻译', level: 'high', root: 'prestig', affix: '-e', synonyms: ['reputation', 'status', 'esteem'], antonyms: ['disgrace', 'notoriety'], collocations: ['international prestige', 'academic prestige', 'prestige of'] },
  { id: 'h538', word: 'coherent', phonetic: '/kəʊˈhɪərənt/', partOfSpeech: 'adj.', meanings: ['连贯的；一致的；条理清楚的'], englishDef: 'logical and well organized; easy to understand and clear', example: 'A coherent argument requires evidence that supports each of its claims in a logical manner.', exampleTranslation: '一个连贯的论证需要以逻辑方式支持其每一个主张的证据。', exampleSource: '2023年翻译', level: 'high', root: 'her', affix: 'co-', synonyms: ['logical', 'consistent', 'systematic'], antonyms: ['incoherent', 'disjointed'], collocations: ['coherent argument', 'coherent policy', 'logically coherent'] },
  { id: 'h539', word: 'assumption', phonetic: '/əˈsʌmpʃn/', partOfSpeech: 'n.', meanings: ['假设；承担；假定'], englishDef: 'something that you accept as true without question or proof', example: 'The assumption that economic growth automatically leads to improved well-being has been challenged by recent studies.', exampleTranslation: '经济增长自动带来幸福改善的假设已被近期研究质疑。', exampleSource: '2021年阅读理解', level: 'high', root: 'sum', affix: 'as-', synonyms: ['presumption', 'hypothesis', 'supposition'], antonyms: ['fact', 'certainty'], collocations: ['based on the assumption', 'challenge the assumption', 'underlying assumption'] },
  { id: 'h540', word: 'propagate', phonetic: '/ˈprɒpəɡeɪt/', partOfSpeech: 'v.', meanings: ['传播；宣传；繁殖'], englishDef: 'to spread opinions, ideas, or beliefs to many people; to reproduce', example: 'Social media platforms can rapidly propagate both accurate information and misinformation.', exampleTranslation: '社交媒体平台可以迅速传播准确信息和错误信息。', exampleSource: '2022年完形填空', level: 'high', root: 'pag', affix: 'pro-', synonyms: ['spread', 'disseminate', 'promote'], antonyms: ['suppress', 'restrain'], collocations: ['propagate information', 'propagate ideas', 'widely propagated'] },
];
