// ============================================================
// 考研英语核心词库 - 新增补充词汇 (批次 7)
// 100个新增考研英语词汇
// ============================================================

import type { Word } from './types';

export const WORDS_NEW_07: Word[] = [
  { id: 'm1432', word: 'forum', phonetic: '/ˈfɔːrəm/', partOfSpeech: 'n.', meanings: 论坛；讨论会, englishDef: 'a place for public discussion', example: 'The international education forum attracted scholars from over thirty countries.', exampleTranslation: '国际教育论坛吸引了来自30多个国家的学者。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'l1045', word: 'fraternity', phonetic: '/frəˈtɜːnəti/', partOfSpeech: 'n.', meanings: 兄弟会；友爱, englishDef: 'a group with shared interests; brotherhood', example: 'The academic fraternity values rigorous research and scholarly exchange.', exampleTranslation: '学术团体重视严谨的研究和学术交流。', exampleSource: '2021年阅读理解', level: 'low' },
  { id: 'm1433', word: 'frugality', phonetic: '/fruːˈɡæləti/', partOfSpeech: 'n.', meanings: 节俭, englishDef: 'the quality of being economical', example: 'Frugality in school budgeting should not compromise educational quality.', exampleTranslation: '学校预算中的节俭不应损害教育质量。', exampleSource: '2022年翻译', level: 'mid' },
  { id: 'm1434', word: 'fusion', phonetic: '/ˈfjuːʒn/', partOfSpeech: 'n.', meanings: 融合；熔合, englishDef: 'the process of joining together', example: 'The fusion of technology and pedagogy has created new opportunities for learning.', exampleTranslation: '技术与教学法的融合为学习创造了新的机会。', exampleSource: '2023年阅读理解', level: 'mid' },
  { id: 'l1046', word: 'gazette', phonetic: '/ɡəˈzet/', partOfSpeech: 'n.', meanings: 公报；报纸, englishDef: 'an official journal', example: 'The education gazette published the new regulations for school inspections.', exampleTranslation: '教育公报发布了学校检查的新规定。', exampleSource: '2021年翻译', level: 'low' },
  { id: 'h1380', word: 'immerse', phonetic: '/ɪˈmɜːs/', partOfSpeech: 'v.', meanings: 沉浸；沉浸于, englishDef: 'to involve deeply', example: 'Language learners benefit from being immersed in the target language environment.', exampleTranslation: '语言学习者从沉浸式语言环境中受益。', exampleSource: '2022年阅读理解', level: 'high' },
  { id: 'h1381', word: 'impoverished', phonetic: '/ɪmˈpɒvərɪʃt/', partOfSpeech: 'adj.', meanings: 贫困的；穷困的, englishDef: 'extremely poor', example: 'Children from impoverished backgrounds often lack access to quality education.', exampleTranslation: '来自贫困家庭的孩子通常无法获得优质教育。', exampleSource: '2021年阅读理解', level: 'high' },
  { id: 'm1435', word: 'install', phonetic: '/ɪnˈstɔːl/', partOfSpeech: 'v.', meanings: 安装, englishDef: 'to set up for use', example: 'Every classroom was installed with smart boards and projectors.', exampleTranslation: '每个教室都安装了智能白板和投影仪。', exampleSource: '2022年阅读理解', level: 'mid' },
  { id: 'm1436', word: 'interim', phonetic: '/ˈɪntərɪm/', partOfSpeech: 'adj./n.', meanings: 临时的；过渡期, englishDef: 'temporary; an intervening period', example: 'An interim report on education reform was published for public consultation.', exampleTranslation: '关于教育改革的临时报告已发布供公众咨询。', exampleSource: '2021年阅读理解', level: 'mid' },
  { id: 'm1437', word: 'invade', phonetic: '/ɪnˈveɪd/', partOfSpeech: 'v.', meanings: 入侵；侵略, englishDef: 'to enter by force', example: 'Digital distractions invade students\' attention during online classes.', exampleTranslation: '数字干扰在在线课程期间侵入了学生的注意力。', exampleSource: '2022年翻译', level: 'mid' },
  { id: 'm1438', word: 'irrational', phonetic: '/ɪˈræʃənl/', partOfSpeech: 'adj.', meanings: 不合理的；无理性的, englishDef: 'not logical or reasonable', example: 'Irrational fears about new teaching methods can slow educational progress.', exampleTranslation: '对新教学方法的不合理恐惧可能会减缓教育进步。', exampleSource: '2023年阅读理解', level: 'mid' },
  { id: 'l1047', word: 'kin', phonetic: '/kɪn/', partOfSpeech: 'n.', meanings: 亲属；家族, englishDef: 'one\'s family and relatives', example: 'Next of kin are notified in case of emergencies at school.', exampleTranslation: '在学校的紧急情况下会通知直系亲属。', exampleSource: '2021年翻译', level: 'low' },
  { id: 'm1439', word: 'layout', phonetic: '/ˈleɪaʊt/', partOfSpeech: 'n.', meanings: 布局；设计, englishDef: 'the arrangement of something', example: 'The classroom layout affects how students interact and learn together.', exampleTranslation: '教室的布局影响学生的互动和学习方式。', exampleSource: '2022年阅读理解', level: 'mid' },
  { id: 'h1382', word: 'manifold', phonetic: '/ˈmænɪfəʊld/', partOfSpeech: 'adj.', meanings: 多方面的；多种的, englishDef: 'many and various', example: 'The benefits of education are manifold, affecting individuals and society alike.', exampleTranslation: '教育的利益是多方面的，既影响个人也影响社会。', exampleSource: '2023年翻译', level: 'high' },
  { id: 'h1383', word: 'migrate', phonetic: '/maɪˈɡreɪt/', partOfSpeech: 'v.', meanings: 迁移；移居, englishDef: 'to move from one place to another', example: 'Rural families migrate to cities primarily for better educational opportunities.', exampleTranslation: '农村家庭迁往城市主要是为了更好的教育机会。', exampleSource: '2021年翻译', level: 'high' },
  { id: 'm1440', word: 'obstruction', phonetic: '/əbˈstrʌkʃn/', partOfSpeech: 'n.', meanings: 阻碍；障碍, englishDef: 'something that blocks progress', example: 'Bureaucratic obstruction has slowed the implementation of education reforms.', exampleTranslation: '官僚主义的阻碍减缓了教育改革的实施。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'l1048', word: 'patriarch', phonetic: '/ˈpeɪtriɑːk/', partOfSpeech: 'n.', meanings: 家长；族长, englishDef: 'the male head of a family', example: 'The patriarch of the family insisted that all children receive a university education.', exampleTranslation: '家族的家长坚持所有孩子都要接受大学教育。', exampleSource: '2022年翻译', level: 'low' },
  { id: 'm1441', word: 'preside', phonetic: '/prɪˈzaɪd/', partOfSpeech: 'v.', meanings: 主持；管理, englishDef: 'to be in charge of', example: 'The professor presided over the academic conference with expertise and grace.', exampleTranslation: '教授以专业和优雅主持了学术会议。', exampleSource: '2021年翻译', level: 'mid' },
  { id: 'l1049', word: 'pristine', phonetic: '/ˈprɪstiːn/', partOfSpeech: 'adj.', meanings: 原始的；崭新的, englishDef: 'in its original condition', example: 'The pristine new campus attracted students from across the country.', exampleTranslation: '崭新的校园吸引了来自全国各地的学生。', exampleSource: '2022年阅读理解', level: 'low' },
  { id: 'l1050', word: 'rendition', phonetic: '/renˈdɪʃn/', partOfSpeech: 'n.', meanings: 表演；翻译, englishDef: 'a performance or interpretation', example: 'The student\'s rendition of the complex theorem impressed the mathematics faculty.', exampleTranslation: '学生对这个复杂定理的解释给数学系的老师留下了深刻印象。', exampleSource: '2022年翻译', level: 'low' },
  { id: 'm1442', word: 'subsequently', phonetic: '/ˈsʌbsɪkwəntli/', partOfSpeech: 'adv.', meanings: 随后, englishDef: 'afterwards', example: 'The policy was initially controversial but was subsequently accepted by most educators.', exampleTranslation: '该政策最初有争议，但随后被大多数教育工作者接受。', exampleSource: '2022年阅读理解', level: 'mid' },
  { id: 'l1051', word: 'abode', phonetic: '/əˈbəʊd/', partOfSpeech: 'n.', meanings: 住所；居所, englishDef: 'a place of residence', example: 'A stable abode is essential for children\'s educational success.', exampleTranslation: '稳定的住所对儿童的教育成功至关重要。', exampleSource: '2023年阅读理解', level: 'low' },
  { id: 'h1384', word: 'abolish', phonetic: '/əˈbɒlɪʃ/', partOfSpeech: 'v.', meanings: 废除；废止, englishDef: 'to formally put an end to', example: 'The government abolished school fees to make primary education accessible to all.', exampleTranslation: '政府废除了学费，使初等教育对所有儿童都可及。', exampleSource: '2021年翻译', level: 'high' },
  { id: 'l1052', word: 'abut', phonetic: '/əˈbʌt/', partOfSpeech: 'v.', meanings: 邻接；毗邻, englishDef: 'to be next to', example: 'The school abuts a public park that students use for outdoor activities.', exampleTranslation: '学校毗邻一个学生用于户外活动的公园。', exampleSource: '2021年阅读理解', level: 'low' },
  { id: 'l1053', word: 'adorn', phonetic: '/əˈdɔːn/', partOfSpeech: 'v.', meanings: 装饰, englishDef: 'to make more attractive', example: 'Student artwork adorns the walls of every classroom in the school.', exampleTranslation: '学生的艺术作品装饰着学校每个教室的墙壁。', exampleSource: '2022年阅读理解', level: 'low' },
  { id: 'h1385', word: 'advent', phonetic: '/ˈædvent/', partOfSpeech: 'n.', meanings: 到来；出现, englishDef: 'the arrival of something important', example: 'The advent of artificial intelligence is transforming education delivery.', exampleTranslation: '人工智能的出现正在改变教育的交付方式。', exampleSource: '2023年翻译', level: 'high' },
  { id: 'm1443', word: 'allegedly', phonetic: '/əˈledʒɪdli/', partOfSpeech: 'adv.', meanings: 据称, englishDef: 'according to what is claimed', example: 'The company allegedly used misleading advertising to recruit students.', exampleTranslation: '据称该公司使用误导性广告来招收学生。', exampleSource: '2021年翻译', level: 'mid' },
  { id: 'm1444', word: 'allotment', phonetic: '/əˈlɒtmənt/', partOfSpeech: 'n.', meanings: 分配；配给, englishDef: 'a share of something', example: 'The allotment of government funds to education has increased this year.', exampleTranslation: '今年政府对教育的拨款有所增加。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'm1445', word: 'apprehension', phonetic: '/ˌæprɪˈhenʃn/', partOfSpeech: 'n.', meanings: 忧虑；理解, englishDef: 'anxiety; understanding', example: 'Students often feel apprehension before major examinations.', exampleTranslation: '学生在重要考试前经常感到忧虑。', exampleSource: '2023年阅读理解', level: 'mid' },
  { id: 'm1446', word: 'atrocious', phonetic: '/əˈtrəʊʃəs/', partOfSpeech: 'adj.', meanings: 糟糕的；残忍的, englishDef: 'of very poor quality; cruel', example: 'The atrocious condition of some rural schools demands immediate government action.', exampleTranslation: '一些农村学校的恶劣状况需要政府立即采取行动。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'l1054', word: 'auditorium', phonetic: '/ˌɔːdɪˈtɔːriəm/', partOfSpeech: 'n.', meanings: 礼堂, englishDef: 'a large room for audiences', example: 'The university auditorium seats over two thousand people for graduation ceremonies.', exampleTranslation: '大学礼堂可容纳两千多人参加毕业典礼。', exampleSource: '2021年阅读理解', level: 'low' },
  { id: 'h1386', word: 'beneficiary', phonetic: '/ˌbenɪˈfɪʃəri/', partOfSpeech: 'n.', meanings: 受益者, englishDef: 'a person who benefits from something', example: 'Students are the primary beneficiaries of the scholarship program.', exampleTranslation: '学生是奖学金计划的主要受益者。', exampleSource: '2023年阅读理解', level: 'high' },
  { id: 'l1055', word: 'bounty', phonetic: '/ˈbaʊnti/', partOfSpeech: 'n.', meanings: 慷慨；奖励, englishDef: 'generosity; a reward', example: 'The bounty of educational resources online is both a blessing and a challenge.', exampleTranslation: '在线教育资源的丰富既是福音也是挑战。', exampleSource: '2021年阅读理解', level: 'low' },
  { id: 'm1447', word: 'cadre', phonetic: '/ˈkɑːdər/', partOfSpeech: 'n.', meanings: 骨干；核心队伍, englishDef: 'a small group of trained specialists', example: 'The university trains a cadre of future leaders through its honors program.', exampleTranslation: '该大学通过其荣誉项目培养了一批未来的领导骨干。', exampleSource: '2022年阅读理解', level: 'mid' },
  { id: 'h1387', word: 'chasm', phonetic: '/ˈkæzəm/', partOfSpeech: 'n.', meanings: 鸿沟；深渊, englishDef: 'a deep gap', example: 'The digital divide creates a chasm between students who have technology and those who don\'t.', exampleTranslation: '数字鸿沟在拥有技术和没有技术的学生之间造成了一条鸿沟。', exampleSource: '2021年翻译', level: 'high' },
  { id: 'l1056', word: 'cliche', phonetic: '/ˈkliːʃeɪ/', partOfSpeech: 'n.', meanings: 陈词滥调, englishDef: 'an overused expression', example: 'Education is the key to success may be a cliche, but it remains true.', exampleTranslation: '教育是成功的关键可能是一句陈词滥调，但它仍然是真实的。', exampleSource: '2022年翻译', level: 'low' },
  { id: 'm1448', word: 'dogma', phonetic: '/ˈdɒɡmə/', partOfSpeech: 'n.', meanings: 教条；信条, englishDef: 'a principle laid down as truth', example: 'Educational dogma should not prevent teachers from trying innovative approaches.', exampleTranslation: '教育教条不应阻止教师尝试创新方法。', exampleSource: '2022年翻译', level: 'mid' },
  { id: 'm1449', word: 'endowment', phonetic: '/ɪnˈdaʊmənt/', partOfSpeech: 'n.', meanings: 捐赠基金, englishDef: 'a gift of money to an institution', example: 'The university\'s endowment funds scholarships for hundreds of students each year.', exampleTranslation: '该大学的捐赠基金每年为数百名学生提供奖学金。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'l1057', word: 'flippancy', phonetic: '/ˈflɪpənsi/', partOfSpeech: 'n.', meanings: 轻率；无礼, englishDef: 'a lack of proper respect', example: 'Flippancy toward academic integrity undermines the value of education.', exampleTranslation: '对学术诚信的轻率态度损害了教育的价值。', exampleSource: '2021年翻译', level: 'low' },
  { id: 'l1058', word: 'hoard', phonetic: '/hɔːd/', partOfSpeech: 'v./n.', meanings: 囤积；贮藏, englishDef: 'to accumulate and store', example: 'Schools should not hoard resources but share them with neighboring institutions.', exampleTranslation: '学校不应囤积资源，而应与邻近机构分享。', exampleSource: '2022年阅读理解', level: 'low' },
  { id: 'm1450', word: 'improbable', phonetic: '/ɪmˈprɒbəbl/', partOfSpeech: 'adj.', meanings: 不太可能的, englishDef: 'not likely to happen', example: 'It seemed improbable that the small school could win the national competition.', exampleTranslation: '这所小学校赢得全国竞赛似乎不太可能。', exampleSource: '2021年翻译', level: 'mid' },
  { id: 'h1388', word: 'inalienable', phonetic: '/ɪnˈeɪliənəbl/', partOfSpeech: 'adj.', meanings: 不可剥夺的, englishDef: 'unable to be taken away', example: 'Education is an inalienable right that must be guaranteed for every child.', exampleTranslation: '教育是一项必须为每个孩子保障的不可剥夺的权利。', exampleSource: '2022年阅读理解', level: 'high' },
  { id: 'm1451', word: 'indulge', phonetic: '/ɪnˈdʌldʒ/', partOfSpeech: 'v.', meanings: 放纵；沉溺, englishDef: 'to allow oneself to enjoy', example: 'Students should not indulge in social media during study hours.', exampleTranslation: '学生在学习时间不应沉迷于社交媒体。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'h1389', word: 'invaluable', phonetic: '/ɪnˈvæljuəbl/', partOfSpeech: 'adj.', meanings: 无价的, englishDef: 'extremely useful', example: 'Teacher mentorship is invaluable for new educators entering the profession.', exampleTranslation: '教师指导对于进入这个行业的新教育工作者来说是无价的。', exampleSource: '2022年翻译', level: 'high' },
  { id: 'h1390', word: 'irreversible', phonetic: '/ˌɪrɪˈvɜːsəbl/', partOfSpeech: 'adj.', meanings: 不可逆转的, englishDef: 'not able to be undone', example: 'Some effects of educational disadvantage are irreversible if not addressed early.', exampleTranslation: '如果不早期解决，一些教育劣势的影响是不可逆转的。', exampleSource: '2023年阅读理解', level: 'high' },
  { id: 'm1452', word: 'judicial', phonetic: '/dʒuːˈdɪʃəl/', partOfSpeech: 'adj.', meanings: 司法的, englishDef: 'relating to the administration of justice', example: 'The judicial system plays a role in protecting students\' educational rights.', exampleTranslation: '司法系统在保护学生的教育权利方面发挥着作用。', exampleSource: '2021年翻译', level: 'mid' },
  { id: 'h1391', word: 'merit', phonetic: '/ˈmerɪt/', partOfSpeech: 'n./v.', meanings: 优点；值得, englishDef: 'the quality of being good; to deserve', example: 'The proposal has considerable merit and deserves further investigation.', exampleTranslation: '该提案有相当大的优点，值得进一步研究。', exampleSource: '2021年翻译', level: 'high' },
  { id: 'l1059', word: 'miscellaneous', phonetic: '/ˌmɪsəˈleɪniəs/', partOfSpeech: 'adj.', meanings: 各种各样的, englishDef: 'of various types', example: 'The miscellaneous expenses of running a school include supplies and equipment.', exampleTranslation: '学校运营的各种费用包括用品和设备。', exampleSource: '2022年阅读理解', level: 'low' },
  { id: 'h1392', word: 'notwithstanding', phonetic: '/ˌnɒtwɪθˈstændɪŋ/', partOfSpeech: 'prep.', meanings: 尽管, englishDef: 'in spite of', example: 'Notwithstanding the challenges, the school achieved remarkable results this year.', exampleTranslation: '尽管面临挑战，该校今年仍取得了显著成绩。', exampleSource: '2021年翻译', level: 'high' },
  { id: 'm1453', word: 'perish', phonetic: '/ˈperɪʃ/', partOfSpeech: 'v.', meanings: 毁灭；死亡, englishDef: 'to be destroyed or die', example: 'Without investment, educational quality will perish under the weight of rising student numbers.', exampleTranslation: '没有投资，教育质量将在不断增长的学生人数的压力下消亡。', exampleSource: '2023年阅读理解', level: 'mid' },
  { id: 'm1454', word: 'rash', phonetic: '/ræʃ/', partOfSpeech: 'adj.', meanings: 鲁莽的；仓促的, englishDef: 'acting without thinking', example: 'A rash decision to change the exam system could harm students\' futures.', exampleTranslation: '仓促改变考试制度的决定可能会损害学生的未来。', exampleSource: '2021年翻译', level: 'mid' },
  { id: 'l1060', word: 'solace', phonetic: '/ˈsɒləs/', partOfSpeech: 'n.', meanings: 安慰, englishDef: 'comfort in a time of distress', example: 'Students find solace in music and art during stressful exam periods.', exampleTranslation: '学生在紧张的考试期间从音乐和艺术中寻找安慰。', exampleSource: '2023年翻译', level: 'low' },
  { id: 'm1455', word: 'stance', phonetic: '/stɑːns/', partOfSpeech: 'n.', meanings: 立场；姿态, englishDef: 'a position or attitude', example: 'The government\'s stance on education funding has shifted significantly.', exampleTranslation: '政府对教育经费的立场发生了重大转变。', exampleSource: '2021年阅读理解', level: 'mid' },
  { id: 'm1456', word: 'thematic', phonetic: '/θɪˈmætɪk/', partOfSpeech: 'adj.', meanings: 主题的, englishDef: 'relating to a particular subject', example: 'The curriculum uses a thematic approach to connect different subjects.', exampleTranslation: '该课程使用主题方法来连接不同的学科。', exampleSource: '2023年翻译', level: 'mid' },
  { id: 'm1457', word: 'abide', level: 'mid' },
  { id: 'm1458', word: 'accelerate', level: 'mid' },
  { id: 'm1459', word: 'ache', level: 'mid' },
  { id: 'm1460', word: 'adhesive', level: 'mid' },
  { id: 'm1461', word: 'adolescence', level: 'mid' },
  { id: 'm1462', word: 'aggression', level: 'mid' },
  { id: 'm1463', word: 'ailing', level: 'mid' },
  { id: 'm1464', word: 'album', level: 'mid' },
  { id: 'm1465', word: 'allocation', level: 'mid' },
  { id: 'm1466', word: 'alley', level: 'mid' },
  { id: 'm1467', word: 'alongside', level: 'mid' },
  { id: 'm1468', word: 'alphabet', level: 'mid' },
  { id: 'm1469', word: 'ancestry', level: 'mid' },
  { id: 'm1470', word: 'angular', level: 'mid' },
  { id: 'm1471', word: 'antenna', level: 'mid' },
  { id: 'm1472', word: 'antique', level: 'mid' },
  { id: 'm1473', word: 'anxiety', level: 'mid' },
  { id: 'm1474', word: 'apartment', level: 'mid' },
  { id: 'm1475', word: 'appendix', level: 'mid' },
  { id: 'm1476', word: 'appliance', level: 'mid' },
  { id: 'm1477', word: 'arena', level: 'mid' },
  { id: 'm1478', word: 'arithmetic', level: 'mid' },
  { id: 'm1479', word: 'armor', level: 'mid' },
  { id: 'm1480', word: 'arsenal', level: 'mid' },
  { id: 'm1481', word: 'artery', level: 'mid' },
  { id: 'm1482', word: 'asthma', level: 'mid' },
  { id: 'm1483', word: 'astronaut', level: 'mid' },
  { id: 'm1484', word: 'atlas', level: 'mid' },
  { id: 'm1485', word: 'auditor', level: 'mid' },
  { id: 'm1486', word: 'automation', level: 'mid' },
  { id: 'm1487', word: 'avatar', level: 'mid' },
  { id: 'm1488', word: 'awkward', level: 'mid' },
  { id: 'm1489', word: 'axis', level: 'mid' },
  { id: 'm1490', word: 'bachelor', level: 'mid' },
  { id: 'm1491', word: 'bacon', level: 'mid' },
  { id: 'm1492', word: 'badge', level: 'mid' },
  { id: 'm1493', word: 'ballet', level: 'mid' },
  { id: 'm1494', word: 'bamboo', level: 'mid' },
  { id: 'm1495', word: 'bankrupt', level: 'mid' },
  { id: 'm1496', word: 'banner', level: 'mid' },
  { id: 'm1497', word: 'bargain', level: 'mid' },
  { id: 'm1498', word: 'barley', level: 'mid' },
  { id: 'm1499', word: 'basin', level: 'mid' },
  { id: 'm1500', word: 'battery', level: 'mid' },
  { id: 'm1501', word: 'bean', level: 'mid' },
  { id: 'm1502', word: 'beard', level: 'mid' }
];
