// ============================================================
// 考研英语核心词库 - 高频词汇 h541-h600
// 60个高频考研英语词汇
// ============================================================

import type { Word } from './types';

export const WORDS_H541_H600: Word[] = [
  { id: 'h541', word: 'accede', phonetic: '/əkˈsiːd/', partOfSpeech: 'v.', meanings: ['同意；就任；加入'], englishDef: 'to agree to a demand, request, or treaty; to take up a position of authority', example: 'The government refused to accede to the demands of the protesters despite mounting public pressure.', exampleTranslation: '尽管公众压力不断增加，政府仍拒绝同意抗议者的要求。', exampleSource: '2021年阅读理解', level: 'high', root: 'ced', affix: 'ac-', synonyms: ['consent', 'assent', 'agree'], antonyms: ['refuse', 'reject'], collocations: ['accede to demands', 'accede to the throne', 'refuse to accede'] },
  { id: 'h542', word: 'allege', phonetic: '/əˈledʒ/', partOfSpeech: 'v.', meanings: ['声称；宣称；指控'], englishDef: 'to claim or assert that someone has done something wrong without providing proof', example: 'The report alleges that several tech companies have violated user privacy regulations.', exampleTranslation: '报告声称几家科技公司违反了用户隐私法规。', exampleSource: '2023年阅读理解', level: 'high', root: 'leg', affix: 'al-', synonyms: ['claim', 'assert', 'contend'], antonyms: ['deny', 'disprove'], collocations: ['allege that', 'it is alleged', 'widely alleged'] },
  { id: 'h543', word: 'amenable', phonetic: '/əˈmiːnəbl/', partOfSpeech: 'adj.', meanings: ['顺从的；肯接受的；经得起检验的'], englishDef: 'open and responsive to suggestion; easily persuaded or controlled', example: 'Educational policymakers must be amenable to evidence-based reform proposals from researchers.', exampleTranslation: '教育政策制定者必须乐于接受来自研究人员的循证改革建议。', exampleSource: '2022年翻译', level: 'high', root: 'men', affix: 'a--able', synonyms: ['responsive', 'agreeable', 'cooperative'], antonyms: ['resistant', 'obstinate'], collocations: ['amenable to', 'amenable to change', 'amenable to reason'] },
  { id: 'h544', word: 'appease', phonetic: '/əˈpiːz/', partOfSpeech: 'v.', meanings: ['安抚；平息；姑息'], englishDef: 'to pacify or placate someone by acceding to their demands', example: 'Critics argue that appeasing polluting industries will only delay the transition to clean energy.', exampleTranslation: '批评者认为，对污染行业采取姑息政策只会推迟向清洁能源的转型。', exampleSource: '2020年阅读理解', level: 'high', root: 'peas', affix: 'ap-', synonyms: ['pacify', 'placate', 'mollify'], antonyms: ['provoke', 'antagonize'], collocations: ['appease the public', 'appease demands', 'appease by concessions'] },
  { id: 'h545', word: 'assimilate', phonetic: '/əˈsɪməleɪt/', partOfSpeech: 'v.', meanings: ['同化；吸收；融入'], englishDef: 'to absorb and integrate people or ideas into a wider society or culture', example: 'Immigrants often face pressure to assimilate into the dominant culture while preserving their own heritage.', exampleTranslation: '移民通常面临融入主流文化同时保留自身传统的压力。', exampleSource: '2019年阅读理解', level: 'high', root: 'simil', affix: 'as-', synonyms: ['integrate', 'absorb', 'incorporate'], antonyms: ['segregate', 'exclude'], collocations: ['assimilate into', 'assimilate information', 'fully assimilate'] },
  { id: 'h546', word: 'acquit', phonetic: '/əˈkwɪt/', partOfSpeech: 'v.', meanings: ['宣判无罪；表现；履行'], englishDef: 'to free someone from a criminal charge; to conduct oneself or perform', example: 'The CEO was acquitted of charges related to environmental violations due to insufficient evidence.', exampleTranslation: '由于证据不足，这位首席执行官被宣判与环境污染相关的指控不成立。', exampleSource: '2022年阅读理解', level: 'high', root: 'quit', affix: 'ac-', synonyms: ['clear', 'exonerate', 'absolve'], antonyms: ['convict', 'condemn'], collocations: ['acquit of', 'acquit oneself', 'acquit well'] },
  { id: 'h547', word: 'bolster', phonetic: '/ˈbəʊlstə/', partOfSpeech: 'v.', meanings: ['支持；加强；支撑'], englishDef: 'to support or strengthen something; to give a boost to', example: 'The government announced new funding to bolster scientific research in artificial intelligence.', exampleTranslation: '政府宣布了新的资金以支持人工智能领域的科学研究。', exampleSource: '2024年阅读理解', level: 'high', synonyms: ['strengthen', 'reinforce', 'buttress'], antonyms: ['undermine', 'weaken'], collocations: ['bolster confidence', 'bolster the economy', 'bolster efforts'] },
  { id: 'h548', word: 'breach', phonetic: '/briːtʃ/', partOfSpeech: 'n./v.', meanings: ['违反；破坏；裂口'], englishDef: 'an act of breaking a law, agreement, or code of conduct', example: 'The data breach at a major social media platform exposed the personal information of millions of users.', exampleTranslation: '一家主要社交媒体平台的数据泄露暴露了数百万用户的个人信息。', exampleSource: '2021年阅读理解', level: 'high', synonyms: ['violation', 'infringement', 'gap'], antonyms: ['compliance', 'observance'], collocations: ['data breach', 'breach of contract', 'breach of trust'] },
  { id: 'h549', word: 'circumvent', phonetic: '/ˌsɜːkəmˈvent/', partOfSpeech: 'v.', meanings: ['规避；绕过；避开'], englishDef: 'to find a way around an obstacle or restriction', example: 'Multinational corporations often find ways to circumvent local environmental regulations.', exampleTranslation: '跨国公司经常找到规避当地环境法规的方法。', exampleSource: '2023年翻译', level: 'high', root: 'vent', affix: 'circum-', synonyms: ['evade', 'bypass', 'sidestep'], antonyms: ['confront', 'face'], collocations: ['circumvent regulations', 'circumvent the law', 'attempt to circumvent'] },
  { id: 'h550', word: 'cogent', phonetic: '/ˈkəʊdʒənt/', partOfSpeech: 'adj.', meanings: ['令人信服的；有说服力的'], englishDef: 'clear, logical, and convincing', example: 'The author presents a cogent argument for reforming the university admissions process.', exampleTranslation: '作者提出了一个令人信服的关于改革大学招生流程的论点。', exampleSource: '2020年翻译', level: 'high', root: 'cog', synonyms: ['compelling', 'convincing', 'persuasive'], antonyms: ['unconvincing', 'weak'], collocations: ['cogent argument', 'cogent reason', 'perfectly cogent'] },
  { id: 'h551', word: 'commensurate', phonetic: '/kəˈmenʃərət/', partOfSpeech: 'adj.', meanings: ['相称的；成比例的；相当的'], englishDef: 'corresponding in size or degree; in proportion', example: 'Salaries in the technology sector are generally commensurate with the level of expertise required.', exampleTranslation: '科技行业的薪资通常与所需的专业水平相称。', exampleSource: '2022年阅读理解', level: 'high', root: 'mens', affix: 'com-', synonyms: ['proportionate', 'equivalent', 'corresponding'], antonyms: ['disproportionate', 'unequal'], collocations: ['commensurate with', 'commensurate experience', 'commensurate ability'] },
  { id: 'h552', word: 'conducive', phonetic: '/kənˈdjuːsɪv/', partOfSpeech: 'adj.', meanings: ['有益的；有助于…的'], englishDef: 'making a certain situation or outcome likely or possible', example: 'A quiet and well-equipped study environment is conducive to effective learning.', exampleTranslation: '安静且设备齐全的学习环境有助于有效学习。', exampleSource: '2019年阅读理解', level: 'high', root: 'duc', affix: 'con-', synonyms: ['favorable', 'beneficial', 'helpful'], antonyms: ['detrimental', 'harmful'], collocations: ['conducive to', 'conducive environment', 'conducive to learning'] },
  { id: 'h553', word: 'confound', phonetic: '/kənˈfaʊnd/', partOfSpeech: 'v.', meanings: ['使困惑；混淆；挫败'], englishDef: 'to cause surprise or confusion in someone; to mix up with something else', example: 'The unexpected results of the experiment confounded the researchers who had predicted the opposite outcome.', exampleTranslation: '实验的意外结果使预测了相反结果的研究人员感到困惑。', exampleSource: '2024年阅读理解', level: 'high', root: 'found', affix: 'con-', synonyms: ['bewilder', 'baffle', 'perplex'], antonyms: ['clarify', 'explain'], collocations: ['confound expectations', 'confound scientists', 'confound the issue'] },
  { id: 'h554', word: 'constrain', phonetic: '/kənˈstreɪn/', partOfSpeech: 'v.', meanings: ['约束；限制；强迫'], englishDef: 'to compel or force someone to follow a particular course of action; to restrict', example: 'Limited resources constrain the ability of developing nations to invest in cutting-edge scientific research.', exampleTranslation: '有限的资源限制了发展中国家投资前沿科学研究的能力。', exampleSource: '2023年翻译', level: 'high', root: 'strain', affix: 'con-', synonyms: ['restrict', 'limit', 'compel'], antonyms: ['liberate', 'free'], collocations: ['constrain growth', 'constrain the ability', 'tightly constrain'] },
  { id: 'h555', word: 'contempt', phonetic: '/kənˈtempt/', partOfSpeech: 'n.', meanings: ['蔑视；轻视；藐视'], englishDef: 'the feeling that someone or something is beneath consideration or worthless', example: 'The politician expressed contempt for the scientific consensus on climate change, drawing widespread criticism.', exampleTranslation: '这位政治家对气候变化的科学共识表示蔑视，引发了广泛批评。', exampleSource: '2022年阅读理解', level: 'high', root: 'tempt', affix: 'con-', synonyms: ['disdain', 'scorn', 'disrespect'], antonyms: ['respect', 'admiration'], collocations: ['hold in contempt', 'contempt for', 'contempt of court'] },
  { id: 'h556', word: 'curtail', phonetic: '/kɜːˈteɪl/', partOfSpeech: 'v.', meanings: ['缩减；削减；限制'], englishDef: 'to reduce or limit something; to cut short', example: 'Budget cuts have forced many research institutions to curtail their scientific programs.', exampleTranslation: '预算削减迫使许多研究机构缩减其科研项目。', exampleSource: '2023年阅读理解', level: 'high', root: 'tail', affix: 'cur-', synonyms: ['reduce', 'cut', 'restrict'], antonyms: ['expand', 'extend'], collocations: ['curtail spending', 'curtail freedom', 'severely curtail'] },
  { id: 'h557', word: 'deprecate', phonetic: '/ˈdeprəkeɪt/', partOfSpeech: 'v.', meanings: ['反对；不赞成；弃用'], englishDef: 'to express disapproval of something; to declare something obsolete', example: 'Educators deprecate the use of rote memorization as the sole method of language instruction.', exampleTranslation: '教育工作者不赞成将死记硬背作为语言教学的唯一方法。', exampleSource: '2021年翻译', level: 'high', root: 'prec', affix: 'de-', synonyms: ['disapprove', 'denounce', 'discourage'], antonyms: ['endorse', 'approve'], collocations: ['deprecate the use', 'strongly deprecate', 'deprecated method'] },

  { id: 'h558', word: 'displace', phonetic: '/dɪsˈpleɪs/', partOfSpeech: 'v.', meanings: ['取代；迫使离开；转移'], englishDef: 'to take over the place of someone or something; to force to leave', example: 'Automation threatens to displace millions of workers in manufacturing industries over the next decade.', exampleTranslation: '自动化威胁着在未来十年内取代制造业中数百万工人。', exampleSource: '2024年阅读理解', level: 'high', affix: 'dis-', synonyms: ['replace', 'supplant', 'relocate'], antonyms: ['retain', 'restore'], collocations: ['displace workers', 'displace people', 'displace by technology'] },
  { id: 'h559', word: 'elucidate', phonetic: '/ɪˈluːsɪdeɪt/', partOfSpeech: 'v.', meanings: ['阐明；解释；说明'], englishDef: 'to make something clear; to explain', example: 'The professor elucidated the complex relationship between economic inequality and social mobility.', exampleTranslation: '教授阐明了经济不平等与社会流动性之间的复杂关系。', exampleSource: '2021年翻译', level: 'high', root: 'lucid', affix: 'e-', synonyms: ['clarify', 'explain', 'illuminate'], antonyms: ['obscure', 'confuse'], collocations: ['elucidate the relationship', 'help elucidate', 'elucidate on'] },
  { id: 'h560', word: 'embroil', phonetic: '/ɪmˈbrɔɪl/', partOfSpeech: 'v.', meanings: ['使卷入；使陷入'], englishDef: 'to involve someone deeply in a conflict or difficult situation', example: 'The country found itself embroiled in a trade war that disrupted global supply chains.', exampleTranslation: '该国发现自己陷入了一场扰乱全球供应链的贸易战。', exampleSource: '2022年阅读理解', level: 'high', root: 'broil', affix: 'em-', synonyms: ['entangle', 'involve', 'embroiled'], antonyms: ['extricate', 'disentangle'], collocations: ['embroil in', 'embroil in controversy', 'become embroiled'] },
  { id: 'h561', word: 'engender', phonetic: '/ɪnˈdʒendə/', partOfSpeech: 'v.', meanings: ['产生；引起；造成'], englishDef: 'to cause or give rise to a feeling, situation, or condition', example: 'Rising income inequality has engendered widespread public discontent with existing economic policies.', exampleTranslation: '不断加剧的收入不平等引起了公众对现有经济政策的广泛不满。', exampleSource: '2022年阅读理解', level: 'high', root: 'gen', affix: 'en-', synonyms: ['generate', 'produce', 'create'], antonyms: ['destroy', 'eradicate'], collocations: ['engender trust', 'engender controversy', 'engender resentment'] },

  { id: 'h562', word: 'entrench', phonetic: '/ɪnˈtrentʃ/', partOfSpeech: 'v.', meanings: ['使根深蒂固；确立；挖掘壕沟'], englishDef: 'to establish an attitude or belief so firmly that it is not likely to change', example: 'Social inequality has become deeply entrenched in many societies despite decades of policy interventions.', exampleTranslation: '尽管有数十年的政策干预，社会不平等在许多社会中已变得根深蒂固。', exampleSource: '2020年阅读理解', level: 'high', root: 'trench', affix: 'en-', synonyms: ['establish', 'ingrain', 'embed'], antonyms: ['uproot', 'dislodge'], collocations: ['deeply entrenched', 'entrenched interests', 'entrenched inequality'] },
  { id: 'h563', word: 'equivocal', phonetic: '/ɪˈkwɪvəkl/', partOfSpeech: 'adj.', meanings: ['模棱两可的；含糊的；可疑的'], englishDef: 'open to more than one interpretation; ambiguous', example: 'The government issued an equivocal statement on its stance toward carbon taxation, frustrating environmental advocates.', exampleTranslation: '政府就其碳税立场发表了一份模棱两可的声明，令环保倡导者感到失望。', exampleSource: '2023年阅读理解', level: 'high', root: 'quiv', affix: 'equi-', synonyms: ['ambiguous', 'vague', 'noncommittal'], antonyms: ['unequivocal', 'clear'], collocations: ['equivocal answer', 'equivocal response', 'somewhat equivocal'] },
  { id: 'h564', word: 'expend', phonetic: '/ɪkˈspend/', partOfSpeech: 'v.', meanings: ['花费；消耗；支出'], englishDef: 'to spend or use up money, time, or effort on something', example: 'Governments must expend considerable resources to ensure that public health systems can cope with future pandemics.', exampleTranslation: '各国政府必须投入大量资源，以确保公共卫生系统能够应对未来的疫情。', exampleSource: '2022年翻译', level: 'high', root: 'pend', affix: 'ex-', synonyms: ['spend', 'consume', 'utilize'], antonyms: ['save', 'conserve'], collocations: ['expend effort', 'expend resources', 'expend energy'] },

  { id: 'h565', word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', partOfSpeech: 'v./n.', meanings: ['利用；剥削；功绩'], englishDef: 'to make full use of and derive benefit from; to treat someone unfairly for personal gain', example: 'Some corporations exploit natural resources in developing countries without adequate environmental safeguards.', exampleTranslation: '一些公司在发展中国家利用自然资源而没有充分的环境保障措施。', exampleSource: '2021年阅读理解', level: 'high', synonyms: ['utilize', 'abuse', 'leverage'], antonyms: ['conserve', 'protect'], collocations: ['exploit resources', 'exploit workers', 'fully exploit'] },
  { id: 'h566', word: 'extrapolate', phonetic: '/ɪkˈstræpəleɪt/', partOfSpeech: 'v.', meanings: ['推断；推知；外推'], englishDef: 'to extend the application of findings beyond the area of observation to infer unknowns', example: 'Scientists extrapolate from current climate data to predict future temperature increases and their effects.', exampleTranslation: '科学家从当前的气候数据推断未来气温上升及其影响。', exampleSource: '2024年阅读理解', level: 'high', root: 'pol', affix: 'extra-', synonyms: ['infer', 'deduce', 'project'], antonyms: ['observe', 'verify'], collocations: ['extrapolate from', 'extrapolate data', 'extrapolate to'] },
  { id: 'h567', word: 'foment', phonetic: '/fəˈment/', partOfSpeech: 'v.', meanings: ['煽动；挑起；助长'], englishDef: 'to instigate or stir up an undesirable or violent sentiment or course of action', example: 'Economic hardship and political repression can foment social unrest and destabilize governments.', exampleTranslation: '经济困难和政治压迫可能煽动社会动荡并动摇政府的稳定。', exampleSource: '2020年翻译', level: 'high', root: 'foment', synonyms: ['incite', 'stir up', 'provoke'], antonyms: ['calm', 'pacify'], collocations: ['foment unrest', 'foment rebellion', 'foment discord'] },
  { id: 'h568', word: 'foster', phonetic: '/ˈfɒstə/', partOfSpeech: 'v.', meanings: ['培养；促进；养育'], englishDef: 'to encourage or promote the development of something; to raise a child', example: 'Schools should foster critical thinking skills that enable students to evaluate information independently.', exampleTranslation: '学校应培养批判性思维能力，使学生能够独立评估信息。', exampleSource: '2022年翻译', level: 'high', root: 'foster', synonyms: ['promote', 'cultivate', 'nurture'], antonyms: ['hinder', 'stifle'], collocations: ['foster development', 'foster innovation', 'foster growth'] },
  { id: 'h569', word: 'gauge', phonetic: '/ɡeɪdʒ/', partOfSpeech: 'v./n.', meanings: ['测量；评估；标准'], englishDef: 'to estimate or determine the magnitude or amount of; a standard of measurement', example: 'It is difficult to gauge the long-term impact of artificial intelligence on employment patterns.', exampleTranslation: '很难评估人工智能对就业模式的长期影响。', exampleSource: '2024年阅读理解', level: 'high', synonyms: ['measure', 'assess', 'estimate'], antonyms: ['guess', 'ignore'], collocations: ['gauge the impact', 'gauge public opinion', 'difficult to gauge'] },
  { id: 'h570', word: 'hamper', phonetic: '/ˈhæmpə/', partOfSpeech: 'v.', meanings: ['妨碍；阻碍；束缚'], englishDef: 'to hinder or impede the movement or progress of', example: 'Inadequate funding continues to hamper scientific research in many developing nations.', exampleTranslation: '资金不足继续妨碍许多发展中国家的科学研究。', exampleSource: '2019年阅读理解', level: 'high', synonyms: ['hinder', 'impede', 'obstruct'], antonyms: ['facilitate', 'assist'], collocations: ['hamper progress', 'hamper development', 'hamper efforts'] },
  { id: 'h571', word: 'heed', phonetic: '/hiːd/', partOfSpeech: 'v./n.', meanings: ['注意；留心；听从'], englishDef: 'to pay attention to advice or a warning; careful attention', example: 'Policymakers should heed the warnings of climate scientists and take decisive action to reduce emissions.', exampleTranslation: '决策者应听从气候科学家的警告，采取果断行动减少排放。', exampleSource: '2021年阅读理解', level: 'high', synonyms: ['listen to', 'pay attention', 'attend to'], antonyms: ['ignore', 'disregard'], collocations: ['heed warnings', 'heed advice', 'pay heed to'] },
  { id: 'h572', word: 'impair', phonetic: '/ɪmˈpeə/', partOfSpeech: 'v.', meanings: ['损害；削弱；减少'], englishDef: 'to weaken or damage something, especially a faculty or function', example: 'Chronic sleep deprivation can significantly impair a student\'s academic performance and mental health.', exampleTranslation: '长期睡眠不足会显著损害学生的学业表现和心理健康。', exampleSource: '2023年阅读理解', level: 'high', root: 'pair', affix: 'im-', synonyms: ['damage', 'weaken', 'compromise'], antonyms: ['enhance', 'improve'], collocations: ['impair performance', 'impair ability', 'severely impair'] },
  { id: 'h573', word: 'incentive', phonetic: '/ɪnˈsentɪv/', partOfSpeech: 'n.', meanings: ['激励；动机；刺激'], englishDef: 'something that motivates or encourages someone to do something', example: 'Tax incentives for renewable energy companies have accelerated the transition away from fossil fuels.', exampleTranslation: '对可再生能源公司的税收激励加速了从化石燃料的转型。', exampleSource: '2022年阅读理解', level: 'high', root: 'cent', affix: 'in-', synonyms: ['motivation', 'stimulus', 'encouragement'], antonyms: ['disincentive', 'deterrent'], collocations: ['financial incentive', 'provide incentive', 'tax incentive'] },
  { id: 'h574', word: 'invoke', phonetic: '/ɪnˈvəʊk/', partOfSpeech: 'v.', meanings: ['援引；调用；祈求'], englishDef: 'to cite or appeal to someone or something as an authority; to call upon', example: 'The defense lawyer invoked constitutional rights to challenge the legality of the surveillance program.', exampleTranslation: '辩护律师援引宪法权利来质疑监控计划的合法性。', exampleSource: '2020年翻译', level: 'high', root: 'voc', affix: 'in-', synonyms: ['cite', 'appeal to', 'invoke'], antonyms: ['revoke', 'repudiate'], collocations: ['invoke the law', 'invoke a right', 'invoke authority'] },
  { id: 'h575', word: 'laden', phonetic: '/ˈleɪdn/', partOfSpeech: 'adj.', meanings: ['装满的；负载的；充满的'], englishDef: 'heavily loaded or weighed down', example: 'The global economy remains laden with uncertainties stemming from geopolitical tensions and trade disputes.', exampleTranslation: '全球经济仍充满来自地缘政治紧张和贸易争端的不确定性。', exampleSource: '2023年阅读理解', level: 'high', root: 'lade', synonyms: ['burdened', 'loaded', 'fraught'], antonyms: ['empty', 'unburdened'], collocations: ['laden with', 'heavily laden', 'laden with debt'] },
  { id: 'h576', word: 'mandate', phonetic: '/ˈmændeɪt/', partOfSpeech: 'n./v.', meanings: ['授权；命令；委托'], englishDef: 'an official order or commission to do something; to give authority to act', example: 'The new environmental mandate requires all factories to reduce carbon emissions by 30 percent within five years.', exampleTranslation: '新的环保命令要求所有工厂在五年内将碳排放量减少30%。', exampleSource: '2021年阅读理解', level: 'high', root: 'mand', synonyms: ['directive', 'order', 'requirement'], antonyms: ['option', 'suggestion'], collocations: ['government mandate', 'mandate that', 'federal mandate'] },
  { id: 'h577', word: 'negligent', phonetic: '/ˈneɡlɪdʒənt/', partOfSpeech: 'adj.', meanings: ['疏忽的；粗心大意的'], englishDef: 'failing to take proper care in doing something; careless', example: 'The company was found negligent in its handling of hazardous waste, resulting in severe environmental contamination.', exampleTranslation: '该公司被发现在处理危险废物方面存在疏忽，导致严重的环境污染。', exampleSource: '2022年翻译', level: 'high', root: 'neglig', affix: '-ent', synonyms: ['careless', 'remiss', 'lax'], antonyms: ['diligent', 'careful'], collocations: ['negligent in', 'criminally negligent', 'negligent behavior'] },
  { id: 'h578', word: 'norm', phonetic: '/nɔːm/', partOfSpeech: 'n.', meanings: ['规范；标准；常态'], englishDef: 'a standard or pattern regarded as typical; what is considered normal', example: 'Remote work has become the new norm for many professionals since the pandemic.', exampleTranslation: '自疫情以来，远程工作已成为许多专业人士的新常态。', exampleSource: '2024年阅读理解', level: 'high', root: 'norm', synonyms: ['standard', 'convention', 'criterion'], antonyms: ['exception', 'deviation'], collocations: ['social norm', 'become the norm', 'cultural norm'] },
  { id: 'h579', word: 'obsolete', phonetic: '/ˈɒbsəliːt/', partOfSpeech: 'adj.', meanings: ['过时的；废弃的；淘汰的'], englishDef: 'no longer produced or used; out of date', example: 'Many traditional skills risk becoming obsolete as artificial intelligence transforms the labor market.', exampleTranslation: '随着人工智能改变劳动力市场，许多传统技能面临被淘汰的风险。', exampleSource: '2023年阅读理解', level: 'high', root: 'obsole', affix: 'ob-', synonyms: ['outdated', 'antiquated', 'superseded'], antonyms: ['modern', 'current'], collocations: ['become obsolete', 'render obsolete', 'obsolete technology'] },
  { id: 'h580', word: 'overt', phonetic: '/əʊˈvɜːt/', partOfSpeech: 'adj.', meanings: ['公开的；明显的；公然的'], englishDef: 'done or shown openly; without concealment', example: 'There has been an overt shift in public opinion regarding the urgency of addressing climate change.', exampleTranslation: '公众对应对气候变化紧迫性的看法出现了明显的转变。', exampleSource: '2021年阅读理解', level: 'high', root: 'vert', affix: 'o-', synonyms: ['open', 'manifest', 'blatant'], antonyms: ['covert', 'hidden'], collocations: ['overt act', 'overt discrimination', 'overt hostility'] },
  { id: 'h581', word: 'perpetuate', phonetic: '/pəˈpetʃueɪt/', partOfSpeech: 'v.', meanings: ['使持续；使永存；维持'], englishDef: 'to make something continue indefinitely; to preserve from oblivion', example: 'Inadequate education policies can perpetuate social inequality across generations.', exampleTranslation: '不充分的教育政策会使社会不平等在代际间持续存在。', exampleSource: '2022年翻译', level: 'high', root: 'pet', affix: 'per-', synonyms: ['sustain', 'maintain', 'preserve'], antonyms: ['eliminate', 'eradicate'], collocations: ['perpetuate inequality', 'perpetuate stereotypes', 'perpetuate the myth'] },
  { id: 'h582', word: 'plethora', phonetic: '/ˈpleθərə/', partOfSpeech: 'n.', meanings: ['过多；过剩；大量'], englishDef: 'a large or excessive amount of something', example: 'The plethora of information available online has made it increasingly difficult to distinguish fact from fiction.', exampleTranslation: '网上大量的信息使得越来越难以区分事实与虚构。', exampleSource: '2023年阅读理解', level: 'high', root: 'pleth', synonyms: ['abundance', 'excess', 'multitude'], antonyms: ['scarcity', 'dearth'], collocations: ['plethora of', 'plethora of information', 'a plethora of options'] },
  { id: 'h583', word: 'prescribe', phonetic: '/prɪˈskraɪb/', partOfSpeech: 'v.', meanings: ['规定；指定；开处方'], englishDef: 'to state authoritatively or as a rule that something should be done; to advise medicine', example: 'International regulations prescribe strict safety standards for the storage and transport of hazardous materials.', exampleTranslation: '国际法规对危险材料的储存和运输规定了严格的安全标准。', exampleSource: '2021年翻译', level: 'high', root: 'scrib', affix: 'pre-', synonyms: ['stipulate', 'mandate', 'dictate'], antonyms: ['prohibit', 'forbid'], collocations: ['prescribe that', 'prescribe standards', 'prescribe medication'] },

  { id: 'h584', word: 'profound', phonetic: '/prəˈfaʊnd/', partOfSpeech: 'adj.', meanings: ['深刻的；深远的；渊博的'], englishDef: 'very great or intense; having deep insight or understanding', example: 'The transition to a digital economy has had a profound impact on traditional employment structures.', exampleTranslation: '向数字经济的转型对传统就业结构产生了深远的影响。', exampleSource: '2024年阅读理解', level: 'high', root: 'found', affix: 'pro-', synonyms: ['deep', 'significant', 'far-reaching'], antonyms: ['superficial', 'shallow'], collocations: ['profound impact', 'profound effect', 'profound change'] },
  { id: 'h585', word: 'replenish', phonetic: '/rɪˈplenɪʃ/', partOfSpeech: 'v.', meanings: ['补充；重新装满；恢复'], englishDef: 'to fill something up again; to restore to its former level or condition', example: 'Efforts to replenish depleted groundwater reserves have become a priority for governments facing prolonged drought.', exampleTranslation: '对于面临长期干旱的政府来说，补充枯竭的地下水储备已成为一项优先任务。', exampleSource: '2023年阅读理解', level: 'high', root: 'plen', affix: 're-', synonyms: ['refill', 'restock', 'restore'], antonyms: ['deplete', 'drain'], collocations: ['replenish supplies', 'replenish resources', 'replenish the stock'] },
  { id: 'h586', word: 'relegate', phonetic: '/ˈrelɪɡeɪt/', partOfSpeech: 'v.', meanings: ['降级；贬低；委托'], englishDef: 'to consign or dismiss to an inferior rank or position', example: 'Traditional classroom methods have been relegated to a secondary role as online education becomes mainstream.', exampleTranslation: '随着在线教育成为主流，传统的课堂教学方法已被降为次要角色。', exampleSource: '2022年阅读理解', level: 'high', root: 'leg', affix: 're-', synonyms: ['demote', 'downgrade', 'consign'], antonyms: ['promote', 'elevate'], collocations: ['relegate to', 'relegated to the background', 'relegate a role'] },
  { id: 'h587', word: 'repercussion', phonetic: '/ˌriːpəˈkʌʃn/', partOfSpeech: 'n.', meanings: ['后果；反响；影响'], englishDef: 'an unintended consequence of an event or action, especially an unwelcome one', example: 'The decision to withdraw from the international climate agreement had serious economic repercussions.', exampleTranslation: '退出国际气候协议的决定产生了严重的经济后果。', exampleSource: '2023年翻译', level: 'high', root: 'percuss', affix: 're-', synonyms: ['consequence', 'ramification', 'aftermath'], antonyms: ['cause', 'origin'], collocations: ['serious repercussions', 'have repercussions', 'economic repercussions'] },
  { id: 'h588', word: 'robust', phonetic: '/rəʊˈbʌst/', partOfSpeech: 'adj.', meanings: ['强健的；坚固的；强有力的'], englishDef: 'strong and healthy; vigorous; able to withstand difficult conditions', example: 'A robust education system is essential for preparing citizens to navigate the complexities of the modern world.', exampleTranslation: '一个强健的教育体系对于培养公民应对现代世界的复杂性至关重要。', exampleSource: '2020年翻译', level: 'high', root: 'rob', synonyms: ['strong', 'resilient', 'sturdy'], antonyms: ['weak', 'fragile'], collocations: ['robust economy', 'robust system', 'robust growth'] },
  { id: 'h589', word: 'scant', phonetic: '/skænt/', partOfSpeech: 'adj./v.', meanings: ['不足的；缺乏的；减少'], englishDef: 'barely sufficient; very little in amount or quantity', example: 'Despite scant evidence linking screen time to poor academic performance, many parents restrict their children\'s device usage.', exampleTranslation: '尽管将屏幕时间与学业表现不佳联系起来的证据不足，许多家长仍然限制孩子使用电子设备。', exampleSource: '2022年翻译', level: 'high', root: 'scant', synonyms: ['meager', 'insufficient', 'limited'], antonyms: ['abundant', 'ample'], collocations: ['scant attention', 'scant evidence', 'scant resources'] },

  { id: 'h590', word: 'stipulate', phonetic: '/ˈstɪpjuleɪt/', partOfSpeech: 'v.', meanings: ['规定；明确要求；约定'], englishDef: 'to demand or specify a requirement as part of a bargain or agreement', example: 'The international treaty stipulates that member nations must reduce carbon emissions by 40 percent by 2030.', exampleTranslation: '国际条约规定成员国必须在2030年前将碳排放量减少40%。', exampleSource: '2024年阅读理解', level: 'high', root: 'stipul', synonyms: ['specify', 'require', 'mandate'], antonyms: ['waive', 'exempt'], collocations: ['stipulate that', 'clearly stipulate', 'stipulate conditions'] },
  { id: 'h591', word: 'substantiate', phonetic: '/səbˈstænʃieɪt/', partOfSpeech: 'v.', meanings: ['证实；证明；使实体化'], englishDef: 'to provide evidence to support or prove the truth of something', example: 'The journalist was unable to substantiate the allegations of corruption due to a lack of credible sources.', exampleTranslation: '由于缺乏可靠的消息来源，记者无法证实腐败的指控。', exampleSource: '2019年阅读理解', level: 'high', root: 'stan', affix: 'sub-', synonyms: ['verify', 'confirm', 'corroborate'], antonyms: ['contradict', 'refute'], collocations: ['substantiate claims', 'substantiate evidence', 'substantiate allegations'] },
  { id: 'h592', word: 'surpass', phonetic: '/səˈpɑːs/', partOfSpeech: 'v.', meanings: ['超越；胜过；优于'], englishDef: 'to exceed or be greater than', example: 'China\'s investment in renewable energy has surpassed that of any other nation in the world.', exampleTranslation: '中国在可再生能源方面的投资已超过世界上任何其他国家。', exampleSource: '2022年阅读理解', level: 'high', root: 'pass', affix: 'sur-', synonyms: ['exceed', 'outstrip', 'transcend'], antonyms: ['fall behind', 'trail'], collocations: ['surpass expectations', 'surpass the limit', 'far surpass'] },
  { id: 'h593', word: 'tenable', phonetic: '/ˈtenəbl/', partOfSpeech: 'adj.', meanings: ['站得住脚的；合理的；可维持的'], englishDef: 'able to be maintained or defended against attack or objection', example: 'The argument that economic growth alone can solve poverty is no longer tenable in light of recent evidence.', exampleTranslation: '鉴于最近的证据，仅靠经济增长就能解决贫困的论点已站不住脚。', exampleSource: '2023年翻译', level: 'high', root: 'ten', affix: '-able', synonyms: ['defensible', 'justifiable', 'reasonable'], antonyms: ['indefensible', 'untenable'], collocations: ['tenable argument', 'no longer tenable', 'tenable position'] },
  { id: 'h594', word: 'tentative', phonetic: '/ˈtentətɪv/', partOfSpeech: 'adj.', meanings: ['暂时的；试探性的；犹豫的'], englishDef: 'not certain or fixed; provisional; done without confidence', example: 'The government announced a tentative plan to reform the healthcare system over the next five years.', exampleTranslation: '政府宣布了一项在未来五年内改革医疗体系的初步计划。', exampleSource: '2021年阅读理解', level: 'high', root: 'tent', affix: '-ative', synonyms: ['provisional', 'preliminary', 'experimental'], antonyms: ['definitive', 'confirmed'], collocations: ['tentative agreement', 'tentative plan', 'tentative steps'] },
  { id: 'h595', word: 'tenuous', phonetic: '/ˈtenjuəs/', partOfSpeech: 'adj.', meanings: ['薄弱的；脆弱的；含糊的'], englishDef: 'very weak or slight; having little substance or validity', example: 'The link between screen time and declining academic performance remains tenuous at best, according to recent studies.', exampleTranslation: '根据最近的研究，屏幕时间与学业成绩下降之间的联系充其量是薄弱的。', exampleSource: '2022年翻译', level: 'high', root: 'ten', affix: '-uous', synonyms: ['flimsy', 'weak', 'slight'], antonyms: ['strong', 'substantial'], collocations: ['tenuous link', 'tenuous connection', 'at best tenuous'] },
  { id: 'h596', word: 'transient', phonetic: '/ˈtrænziənt/', partOfSpeech: 'adj.', meanings: ['短暂的；暂时的；转瞬即逝的'], englishDef: 'lasting only for a short time; impermanent', example: 'The economic recovery proved to be transient, as the country slipped back into recession within two years.', exampleTranslation: '经济复苏被证明是短暂的，该国在两年内再次陷入衰退。', exampleSource: '2020年阅读理解', level: 'high', root: 'trans', affix: '-ient', synonyms: ['temporary', 'fleeting', 'short-lived'], antonyms: ['permanent', 'enduring'], collocations: ['transient effect', 'transient nature', 'transient phenomenon'] },
  { id: 'h597', word: 'tumultuous', phonetic: '/tjuːˈmʌltʃuəs/', partOfSpeech: 'adj.', meanings: ['动荡的；混乱的；嘈杂的'], englishDef: 'making a loud, confused noise; full of tumult; highly agitated', example: 'The country has experienced a tumultuous period of political reform and social transformation.', exampleTranslation: '该国经历了一段动荡的政治改革和社会转型时期。', exampleSource: '2024年翻译', level: 'high', root: 'tumult', affix: '-uous', synonyms: ['turbulent', 'chaotic', 'stormy'], antonyms: ['peaceful', 'calm'], collocations: ['tumultuous period', 'tumultuous times', 'tumultuous year'] },
  { id: 'h598', word: 'underpin', phonetic: '/ˌʌndəˈpɪn/', partOfSpeech: 'v.', meanings: ['支撑；巩固；构成…的基础'], englishDef: 'to support, justify, or form the basis for an idea or argument', example: 'Solid scientific evidence must underpin any effective public health policy aimed at combating infectious diseases.', exampleTranslation: '扎实的科学证据必须构成任何旨在对抗传染病的有效公共卫生政策的基础。', exampleSource: '2024年阅读理解', level: 'high', affix: 'under-', synonyms: ['support', 'bolster', 'foundation'], antonyms: ['undermine', 'weaken'], collocations: ['underpin the argument', 'underpin the theory', 'strongly underpin'] },
  { id: 'h599', word: 'volatile', phonetic: '/ˈvɒlətaɪl/', partOfSpeech: 'adj.', meanings: ['易变的；动荡的；不稳定的'], englishDef: 'liable to change rapidly and unpredictably, especially for the worse', example: 'The volatile nature of cryptocurrency markets has deterred many institutional investors from participating.', exampleTranslation: '加密货币市场的动荡性质使许多机构投资者望而却步。', exampleSource: '2022年阅读理解', level: 'high', root: 'volat', synonyms: ['unstable', 'fluctuating', 'erratic'], antonyms: ['stable', 'steady'], collocations: ['volatile market', 'volatile situation', 'highly volatile'] },
  { id: 'h600', word: 'wield', phonetic: '/wiːld/', partOfSpeech: 'v.', meanings: ['行使；挥舞；掌握'], englishDef: 'to hold and use a weapon or tool; to exercise power or influence', example: 'Technology companies wield enormous influence over public discourse and the flow of information.', exampleTranslation: '科技公司对公共话语和信息流行使着巨大的影响力。', exampleSource: '2021年阅读理解', level: 'high', root: 'wield', synonyms: ['exercise', 'exert', 'brandish'], antonyms: ['surrender', 'relinquish'], collocations: ['wield influence', 'wield power', 'wield authority'] },
];
