// ============================================================
// 考研英语低频词汇 l411-l450
// 进阶/稀有词汇 - 偶尔出现在考研真题中
// ============================================================

import type { Word } from './types';

export const WORDS_L411_L450: Word[] = [
  { id: 'l411', word: 'scurrilous', phonetic: '/ˈskʌrələs/', partOfSpeech: 'adj.', meanings: ['下流的；粗俗辱骂的；诽谤性的'], englishDef: 'making or spreading scandalous claims about someone with the intention of damaging their reputation', example: 'The tabloid published scurrilous allegations against the politician without any evidence to support them.', exampleTranslation: '该小报发表了对这位政治家的诽谤性指控，没有任何证据支持。', exampleSource: '2020年阅读理解', level: 'low', root: 'scurr', affix: '-ilous', synonyms: ['defamatory', 'libelous', 'slanderous'], antonyms: ['complimentary', 'laudatory'], collocations: ['scurrilous attack', 'scurrilous rumor', 'scurrilous allegations'] },
  { id: 'l412', word: 'seraphic', phonetic: '/səˈræfɪk/', partOfSpeech: 'adj.', meanings: ['天使般的；纯洁的；崇高的'], englishDef: 'characteristic of or resembling a seraph; blissful and angelic', example: 'The child\'s seraphic smile brought a moment of peace to the otherwise tense courtroom.', exampleTranslation: '孩子天使般的微笑给原本紧张的法庭带来了一刻宁静。', exampleSource: '2022年翻译', level: 'low', root: 'seraph', affix: '-ic', synonyms: ['angelic', 'beatific', 'ethereal'], antonyms: ['demonic', 'devilish'], collocations: ['seraphic smile', 'seraphic beauty', 'seraphic expression'] },
  { id: 'l413', word: 'sinecure', phonetic: '/ˈsɪnɪkjʊər/', partOfSpeech: 'n.', meanings: ['闲职；挂名差事'], englishDef: 'a position requiring little or no work but giving the holder status or financial benefit', example: 'Critics described the newly created government post as nothing more than a political sinecure.', exampleTranslation: '批评者将新设立的政府职位描述为不过是一个政治闲职。', exampleSource: '2019年阅读理解', level: 'low', root: 'cur', affix: 'sine-', synonyms: ['cushy job', 'nominal post', 'figurehead position'], antonyms: ['demanding job', 'laborious task'], collocations: ['political sinecure', 'mere sinecure', 'comfortable sinecure'] },
  { id: 'l414', word: 'solecism', phonetic: '/ˈsɒlɪsɪzəm/', partOfSpeech: 'n.', meanings: ['语法错误；失礼；不合礼节的行为'], englishDef: 'a grammatical mistake in speech or writing; a breach of good manners', example: 'The diplomat committed a solecism by addressing the ambassador by the wrong title at the formal dinner.', exampleTranslation: '这位外交官在正式晚宴上以错误的头衔称呼大使，犯了一个失礼的错误。', exampleSource: '2021年翻译', level: 'low', root: 'solec', affix: '-ism', synonyms: ['blunder', 'faux pas', 'impropriety'], antonyms: ['propriety', 'correctness'], collocations: ['commit a solecism', 'grammatical solecism', 'social solecism'] },
  { id: 'l415', word: 'somnolent', phonetic: '/ˈsɒmnələnt/', partOfSpeech: 'adj.', meanings: ['昏昏欲睡的；催眠的；寂静的'], englishDef: 'sleepy or drowsy; inducing drowsiness', example: 'The somnolent atmosphere of the afternoon lecture made it difficult for students to stay awake.', exampleTranslation: '下午讲座的催眠氛围让学生们很难保持清醒。', exampleSource: '2020年阅读理解', level: 'low', root: 'somn', affix: '-olent', synonyms: ['drowsy', 'lethargic', 'sleepy'], antonyms: ['alert', 'vigilant'], collocations: ['somnolent atmosphere', 'somnolent effect', 'feel somnolent'] },
  { id: 'l416', word: 'specious', phonetic: '/ˈspiːʃəs/', partOfSpeech: 'adj.', meanings: ['似是而非的；貌似有理的；华而不实的'], englishDef: 'superficially plausible, but actually wrong; misleading in appearance', example: 'The lawyer\'s specious argument initially swayed the jury, but it collapsed under cross-examination.', exampleTranslation: '律师似是而非的论点最初影响了陪审团，但在交叉询问下不攻自破。', exampleSource: '2022年阅读理解', level: 'low', root: 'spec', affix: '-ious', synonyms: ['deceptive', 'fallacious', 'misleading'], antonyms: ['genuine', 'valid'], collocations: ['specious argument', 'specious reasoning', 'specious claim'] },
  { id: 'l417', word: 'squalid', phonetic: '/ˈskwɒlɪd/', partOfSpeech: 'adj.', meanings: ['肮脏的；破败的；卑劣的'], englishDef: 'extremely dirty and unpleasant, especially as a result of poverty or neglect', example: 'The documentary exposed the squalid living conditions in the overcrowded urban slums.', exampleTranslation: '这部纪录片揭露了过度拥挤的城市贫民窟中肮脏的生活条件。', exampleSource: '2019年阅读理解', level: 'low', root: 'squal', affix: '-id', synonyms: ['filthy', 'degraded', 'wretched'], antonyms: ['clean', 'pristine'], collocations: ['squalid conditions', 'squalid living', 'squalid poverty'] },
  { id: 'l418', word: 'stolid', phonetic: '/ˈstɒlɪd/', partOfSpeech: 'adj.', meanings: ['迟钝的；冷漠的；不动感情的'], englishDef: 'calm, dependable, and showing little emotion or animation', example: 'The stolid expression of the witness revealed nothing about what he had truly witnessed.', exampleTranslation: '证人冷漠的表情没有透露他真正看到了什么。', exampleSource: '2021年翻译', level: 'low', root: 'stolid', affix: '', synonyms: ['impassive', 'phlegmatic', 'unemotional'], antonyms: ['emotional', 'expressive'], collocations: ['stolid expression', 'stolid demeanor', 'stolid character'] },
  { id: 'l419', word: 'stratagem', phonetic: '/ˈstrætədʒəm/', partOfSpeech: 'n.', meanings: ['计谋；策略；诡计'], englishDef: 'a plan or scheme, especially one used to outwit an opponent or achieve an end', example: 'The general employed a clever stratagem to lure the enemy into a vulnerable position.', exampleTranslation: '将军采用了一个巧妙的计谋将敌人引诱到一个脆弱的位置。', exampleSource: '2020年阅读理解', level: 'low', root: 'strat', affix: '-agem', synonyms: ['tactic', 'ploy', 'ruse'], antonyms: ['direct approach'], collocations: ['clever stratagem', 'military stratagem', 'employ a stratagem'] },
  { id: 'l420', word: 'strident', phonetic: '/ˈstraɪdnt/', partOfSpeech: 'adj.', meanings: ['刺耳的；尖锐的；咄咄逼人的'], englishDef: 'loud and harsh; presenting a point of view in an excessively forceful way', example: 'The strident criticism from opposition lawmakers forced the government to reconsider its policy.', exampleTranslation: '反对派议员的尖锐批评迫使政府重新考虑其政策。', exampleSource: '2022年阅读理解', level: 'low', root: 'strid', affix: '-ent', synonyms: ['harsh', 'shrill', 'vociferous'], antonyms: ['soft', 'mellow'], collocations: ['strident voice', 'strident criticism', 'strident tone'] },
  { id: 'l421', word: 'subterfuge', phonetic: '/ˈsʌtəfjuːdʒ/', partOfSpeech: 'n.', meanings: ['托词；诡计；欺骗手段'], englishDef: 'deceit used in order to achieve one\'s goal', example: 'The investigation revealed that the company had used subterfuge to evade environmental regulations.', exampleTranslation: '调查揭示该公司使用了欺骗手段来逃避环境法规。', exampleSource: '2019年翻译', level: 'low', root: 'fug', affix: 'subter-', synonyms: ['deception', 'trickery', 'deceit'], antonyms: ['honesty', 'candor'], collocations: ['resort to subterfuge', 'political subterfuge', 'through subterfuge'] },
  { id: 'l422', word: 'succinct', phonetic: '/səkˈsɪŋkt/', partOfSpeech: 'adj.', meanings: ['简洁的；简明的；言简意赅的'], englishDef: 'briefly and clearly expressed', example: 'The professor gave a succinct summary of the complex theory that even beginners could understand.', exampleTranslation: '教授对这一复杂理论进行了简洁的总结，即使是初学者也能理解。', exampleSource: '2021年阅读理解', level: 'low', root: 'cinct', affix: 'suc-', synonyms: ['concise', 'brief', 'terse'], antonyms: ['verbose', 'lengthy'], collocations: ['succinct summary', 'succinct explanation', 'succinct manner'] },
  { id: 'l423', word: 'surreptitious', phonetic: '/ˌsʌrəpˈtɪʃəs/', partOfSpeech: 'adj.', meanings: ['偷偷摸摸的；暗中的；秘密的'], englishDef: 'kept secret, especially because it would not be approved of', example: 'The surreptitious recording of the private conversation raised serious ethical and legal concerns.', exampleTranslation: '对私人谈话的秘密录音引发了严重的伦理和法律问题。', exampleSource: '2020年翻译', level: 'low', root: 'rept', affix: 'sur-', synonyms: ['covert', 'clandestine', 'secret'], antonyms: ['open', 'overt'], collocations: ['surreptitious glance', 'surreptitious recording', 'surreptitious activity'] },
  { id: 'l424', word: 'sycophant', phonetic: '/ˈsɪkəfænt/', partOfSpeech: 'n.', meanings: ['谄媚者；马屁精'], englishDef: 'a person who acts obsequiously toward someone important in order to gain advantage', example: 'The leader was surrounded by sycophants who shielded him from any criticism or honest feedback.', exampleTranslation: '这位领导人被谄媚者包围，他们使他免受任何批评或诚实的反馈。', exampleSource: '2022年阅读理解', level: 'low', root: 'phant', affix: 'syco-', synonyms: ['flatterer', 'toady', 'yes-man'], antonyms: ['critic', 'straight-talker'], collocations: ['political sycophant', 'surrounded by sycophants', 'act as a sycophant'] },
  { id: 'l425', word: 'tantamount', phonetic: '/ˈtæntəmaʊnt/', partOfSpeech: 'adj.', meanings: ['等同于；相当于'], englishDef: 'equivalent in seriousness to; virtually the same as', example: 'The committee chairman said that refusing to negotiate was tantamount to rejecting compromise altogether.', exampleTranslation: '委员会主席表示，拒绝谈判等同于完全拒绝妥协。', exampleSource: '2019年阅读理解', level: 'low', root: 'mount', affix: 'tanta-', synonyms: ['equivalent', 'comparable', 'equal'], antonyms: [], collocations: ['tantamount to', 'tantamount to a refusal', 'tantamount to an admission'] },
  { id: 'l426', word: 'temerity', phonetic: '/tɪˈmerəti/', partOfSpeech: 'n.', meanings: ['鲁莽；大胆；冒失'], englishDef: 'excessive confidence or boldness; audacity', example: 'She had the temerity to challenge the professor\'s theory in front of the entire faculty.', exampleTranslation: '她竟敢在全体教职员工面前挑战教授的理论。', exampleSource: '2021年翻译', level: 'low', root: 'temer', affix: '-ity', synonyms: ['audacity', 'boldness', 'effrontery'], antonyms: ['timidity', 'caution'], collocations: ['have the temerity', 'sheer temerity', 'remarkable temerity'] },
  { id: 'l427', word: 'tenable', phonetic: '/ˈtenəbl/', partOfSpeech: 'adj.', meanings: ['站得住脚的；可维持的；可防守的'], englishDef: 'able to be maintained or defended against attack or objection', example: 'The researcher\'s hypothesis is no longer tenable in light of the newly discovered evidence.', exampleTranslation: '鉴于新发现的证据，该研究人员的假设已不再站得住脚。', exampleSource: '2020年阅读理解', level: 'low', root: 'ten', affix: '-able', synonyms: ['defensible', 'justifiable', 'sustainable'], antonyms: ['untenable', 'indefensible'], collocations: ['tenable position', 'no longer tenable', 'tenable argument'] },
  { id: 'l428', word: 'tenuous', phonetic: '/ˈtenjuəs/', partOfSpeech: 'adj.', meanings: ['脆弱的；微弱的；牵强的'], englishDef: 'very weak or slight; insubstantial', example: 'The connection between the two events is tenuous at best and should not be overemphasized.', exampleTranslation: '两个事件之间的联系充其量是微弱的，不应被过分强调。', exampleSource: '2022年翻译', level: 'low', root: 'tenu', affix: '-ous', synonyms: ['weak', 'fragile', 'flimsy'], antonyms: ['strong', 'solid'], collocations: ['tenuous link', 'tenuous connection', 'tenuous hold'] },
  { id: 'l429', word: 'tirade', phonetic: '/taɪˈreɪd/', partOfSpeech: 'n.', meanings: ['长篇激烈批评；猛烈的抨击'], englishDef: 'a long, angry speech of criticism or accusation', example: 'The senator launched into a tirade against the proposed budget cuts to education funding.', exampleTranslation: '参议员对拟议的教育经费预算削减进行了猛烈的抨击。', exampleSource: '2019年阅读理解', level: 'low', root: 'tir', affix: '-ade', synonyms: ['diatribe', 'rant', 'harangue'], antonyms: ['praise', 'commendation'], collocations: ['launch a tirade', 'bitter tirade', 'tirade against'] },
  { id: 'l430', word: 'torpid', phonetic: '/ˈtɔːpɪd/', partOfSpeech: 'adj.', meanings: ['迟钝的；麻木的；不活跃的'], englishDef: 'mentally or physically inactive; lethargic', example: 'The torpid response of the bureaucracy to the crisis drew widespread public criticism.', exampleTranslation: '官僚机构对危机的迟钝反应引起了广泛的公众批评。', exampleSource: '2021年阅读理解', level: 'low', root: 'torp', affix: '-id', synonyms: ['lethargic', 'sluggish', 'listless'], antonyms: ['energetic', 'vigorous'], collocations: ['torpid response', 'torpid state', 'remain torpid'] },
  { id: 'l431', word: 'trenchant', phonetic: '/ˈtrentʃənt/', partOfSpeech: 'adj.', meanings: ['尖锐的；一针见血的；有力的'], englishDef: 'vigorous or incisive in expression or style', example: 'The scholar\'s trenchant analysis of the economic policy exposed its fundamental flaws.', exampleTranslation: '该学者对经济政策的尖锐分析揭露了其根本缺陷。', exampleSource: '2020年阅读理解', level: 'low', root: 'trench', affix: '-ant', synonyms: ['incisive', 'sharp', 'penetrating'], antonyms: ['vague', 'dull'], collocations: ['trenchant criticism', 'trenchant analysis', 'trenchant wit'] },
  { id: 'l432', word: 'truculent', phonetic: '/ˈtrʌkjʊlənt/', partOfSpeech: 'adj.', meanings: ['好斗的；凶猛的；尖刻的'], englishDef: 'eager or quick to argue or fight; aggressively defiant', example: 'The truculent tone of the debate made it impossible to reach any constructive agreement.', exampleTranslation: '辩论中好斗的语气使得达成任何建设性协议变得不可能。', exampleSource: '2022年翻译', level: 'low', root: 'truc', affix: '-ulent', synonyms: ['belligerent', 'aggressive', 'combative'], antonyms: ['peaceable', 'docile'], collocations: ['truculent manner', 'truculent tone', 'increasingly truculent'] },
  { id: 'l433', word: 'ubiquitous', phonetic: '/juːˈbɪkwɪtəs/', partOfSpeech: 'adj.', meanings: ['无处不在的；普遍存在的'], englishDef: 'present, appearing, or found everywhere', example: 'Smartphones have become so ubiquitous that it is difficult to imagine life without them.', exampleTranslation: '智能手机已经变得如此普遍，以至于很难想象没有它们的生活。', exampleSource: '2019年阅读理解', level: 'low', root: 'ubiqu', affix: '-itous', synonyms: ['omnipresent', 'pervasive', 'universal'], antonyms: ['rare', 'scarce'], collocations: ['ubiquitous presence', 'seemingly ubiquitous', 'ubiquitous technology'] },
  { id: 'l434', word: 'umbrage', phonetic: '/ˈʌmbrɪdʒ/', partOfSpeech: 'n.', meanings: ['不快；愤怒；冒犯'], englishDef: 'offense or annoyance', example: 'The professor took umbrage at the suggestion that his research methodology was flawed.', exampleTranslation: '教授对有人暗示他的研究方法有缺陷感到不快。', exampleSource: '2021年翻译', level: 'low', root: 'umbr', affix: '-age', synonyms: ['offense', 'resentment', 'displeasure'], antonyms: ['pleasure', 'delight'], collocations: ['take umbrage', 'give umbrage', 'cause umbrage'] },
  { id: 'l435', word: 'unctuous', phonetic: '/ˈʌŋktjuəs/', partOfSpeech: 'adj.', meanings: ['油腔滑调的；过分恭维的；虚情假意的'], englishDef: 'excessively or ingratiatingly flattering; oily', example: 'The salesperson\'s unctuous manner made the customers feel uncomfortable rather than welcomed.', exampleTranslation: '销售人员油腔滑调的态度让顾客感到不舒服而非受欢迎。', exampleSource: '2020年阅读理解', level: 'low', root: 'unct', affix: '-uous', synonyms: ['smarmy', 'oily', 'obsequious'], antonyms: ['sincere', 'genuine'], collocations: ['unctuous manner', 'unctuous voice', 'unctuous flattery'] },
  { id: 'l436', word: 'undulate', phonetic: '/ˈʌndjʊleɪt/', partOfSpeech: 'v.', meanings: ['波动；起伏；呈波浪形'], englishDef: 'to move or be arranged with a wavelike motion or pattern', example: 'The rolling hills undulate gently toward the horizon, creating a picturesque landscape.', exampleTranslation: '连绵起伏的山丘向地平线缓缓起伏，形成了如画的风景。', exampleSource: '2022年翻译', level: 'low', root: 'undul', affix: '-ate', synonyms: ['wave', 'ripple', 'fluctuate'], antonyms: ['flatten', 'stabilize'], collocations: ['undulate gently', 'undulating terrain', 'undulating waves'] },
  { id: 'l437', word: 'unimpeachable', phonetic: '/ˌʌnɪmˈpiːtʃəbl/', partOfSpeech: 'adj.', meanings: ['无可指摘的；无懈可击的；无可置疑的'], englishDef: 'not able to be doubted, questioned, or criticized; entirely trustworthy', example: 'The scholar\'s unimpeachable integrity earned her the respect of colleagues across the world.', exampleTranslation: '这位学者无可指摘的正直品格赢得了全世界同行的尊重。', exampleSource: '2019年阅读理解', level: 'low', root: 'peach', affix: 'un-im-', synonyms: ['irreproachable', 'blameless', 'beyond reproach'], antonyms: ['questionable', 'dubious'], collocations: ['unimpeachable integrity', 'unimpeachable source', 'unimpeachable record'] },
  { id: 'l438', word: 'upbraid', phonetic: '/ʌpˈbreɪd/', partOfSpeech: 'v.', meanings: ['训斥；责骂；谴责'], englishDef: 'to find fault with someone; to scold', example: 'The manager upbraided the team for failing to meet the project deadline for the third time.', exampleTranslation: '经理因团队第三次未能按时完成项目截止日期而训斥了他们。', exampleSource: '2021年翻译', level: 'low', root: 'braid', affix: 'up-', synonyms: ['scold', 'rebuke', 'reprimand'], antonyms: ['praise', 'commend'], collocations: ['upbraid someone for', 'publicly upbraid', 'severely upbraid'] },
  { id: 'l439', word: 'usurp', phonetic: '/juːˈzɜːp/', partOfSpeech: 'v.', meanings: ['篡夺；侵占；夺取'], englishDef: 'to take a position of power or importance illegally or by force', example: 'The faction attempted to usurp the authority of the elected board of directors.', exampleTranslation: '该派系试图篡夺民选董事会的权力。', exampleSource: '2020年阅读理解', level: 'low', root: 'surp', affix: 'us-', synonyms: ['seize', 'overthrow', 'wrest'], antonyms: ['cede', 'surrender'], collocations: ['usurp power', 'usurp the throne', 'usurp authority'] },
  { id: 'l440', word: 'utilitarian', phonetic: '/juːˌtɪlɪˈteəriən/', partOfSpeech: 'adj./n.', meanings: ['功利主义的；实用的；功利主义者'], englishDef: 'designed to be useful or practical rather than attractive; a follower of utilitarianism', example: 'The building\'s utilitarian design prioritized function over aesthetic appeal.', exampleTranslation: '这座建筑的实用主义设计将功能置于美学吸引力之上。', exampleSource: '2022年阅读理解', level: 'low', root: 'util', affix: '-itarian', synonyms: ['practical', 'functional', 'pragmatic'], antonyms: ['aesthetic', 'ornamental'], collocations: ['utilitarian approach', 'utilitarian philosophy', 'utilitarian design'] },
  { id: 'l441', word: 'vacuous', phonetic: '/ˈvækjuəs/', partOfSpeech: 'adj.', meanings: ['空洞的；无意义的；茫然的'], englishDef: 'having or showing a lack of thought or intelligence; mindless', example: 'The politician\'s vacuous promises failed to address any of the substantive issues facing the nation.', exampleTranslation: '这位政治家空洞的承诺未能解决国家面临的任何实质性问题。', exampleSource: '2019年阅读理解', level: 'low', root: 'vacu', affix: '-ous', synonyms: ['empty', 'inane', 'hollow'], antonyms: ['meaningful', 'substantive'], collocations: ['vacuous expression', 'vacuous promises', 'vacuous smile'] },
  { id: 'l442', word: 'vapid', phonetic: '/ˈvæpɪd/', partOfSpeech: 'adj.', meanings: ['乏味的；无趣的；枯燥的'], englishDef: 'offering nothing that is stimulating or challenging; dull', example: 'The critic described the novel as a vapid attempt at social commentary that lacked depth.', exampleTranslation: '评论家将这部小说描述为一次缺乏深度的、乏味的社会评论尝试。', exampleSource: '2021年翻译', level: 'low', root: 'vap', affix: '-id', synonyms: ['bland', 'dull', 'insipid'], antonyms: ['interesting', 'stimulating'], collocations: ['vapid conversation', 'vapid content', 'utterly vapid'] },
  { id: 'l443', word: 'veneer', phonetic: '/vəˈnɪər/', partOfSpeech: 'n./v.', meanings: ['外表；虚饰；薄板'], englishDef: 'a thin decorative covering of fine wood; an attractive appearance that covers something unpleasant', example: 'Beneath the veneer of prosperity, the country was struggling with deep economic inequality.', exampleTranslation: '在繁荣的外表之下，该国正在与深层的经济不平等作斗争。', exampleSource: '2020年阅读理解', level: 'low', root: 'veneer', affix: '', synonyms: ['facade', 'front', 'disguise'], antonyms: ['reality', 'substance'], collocations: ['thin veneer', 'veneer of respectability', 'polished veneer'] },
  { id: 'l444', word: 'veracious', phonetic: '/vəˈreɪʃəs/', partOfSpeech: 'adj.', meanings: ['诚实的；真实的；准确的'], englishDef: 'speaking or representing the truth; truthful', example: 'The journalist was known for her veracious reporting, which earned her several prestigious awards.', exampleTranslation: '这位记者以其真实的报道而闻名，这为她赢得了几个著名奖项。', exampleSource: '2022年翻译', level: 'low', root: 'ver', affix: '-acious', synonyms: ['truthful', 'honest', 'accurate'], antonyms: ['deceitful', 'dishonest'], collocations: ['veracious account', 'veracious report', 'veracious witness'] },
  { id: 'l445', word: 'vestige', phonetic: '/ˈvestɪdʒ/', partOfSpeech: 'n.', meanings: ['遗迹；残余；痕迹'], englishDef: 'a trace or remnant of something that is disappearing or no longer exists', example: 'The ancient ruins are the last vestige of a once-great civilization that dominated the region.', exampleTranslation: '这些古代遗迹是曾经统治该地区的伟大文明的最后遗迹。', exampleSource: '2019年阅读理解', level: 'low', root: 'vestig', affix: '-e', synonyms: ['remnant', 'trace', 'relic'], antonyms: [], collocations: ['last vestige', 'vestige of', 'vestige of hope'] },
  { id: 'l446', word: 'vicissitude', phonetic: '/vɪˈsɪsɪtjuːd/', partOfSpeech: 'n.', meanings: ['变迁；兴衰；世事无常'], englishDef: 'a change of circumstances or fortune, typically one that is unwelcome', example: 'The memoir recounts the vicissitudes of the immigrant family as they adapted to a new country.', exampleTranslation: '回忆录记述了这个移民家庭在适应新国家过程中的种种变迁。', exampleSource: '2021年阅读理解', level: 'low', root: 'viciss', affix: '-itude', synonyms: ['fluctuation', 'change', 'upheaval'], antonyms: ['stability', 'constancy'], collocations: ['vicissitudes of life', 'the vicissitudes of', 'weather the vicissitudes'] },
  { id: 'l447', word: 'vindictive', phonetic: '/vɪnˈdɪktɪv/', partOfSpeech: 'adj.', meanings: ['怀恨的；报复性的；有复仇心的'], englishDef: 'having or showing a strong desire for revenge', example: 'The vindictive policies of the outgoing administration were clearly designed to hinder its successor.', exampleTranslation: '即将离任的政府的报复性政策明显是为了阻碍其继任者。', exampleSource: '2020年翻译', level: 'low', root: 'vindic', affix: '-tive', synonyms: ['vengeful', 'spiteful', 'revengeful'], antonyms: ['forgiving', 'merciful'], collocations: ['vindictive act', 'vindictive nature', 'vindictive behavior'] },
  { id: 'l448', word: 'virulent', phonetic: '/ˈvɪrjʊlənt/', partOfSpeech: 'adj.', meanings: ['恶毒的；致命的；充满敌意的'], englishDef: 'extremely severe or harmful in its effects; bitterly hostile', example: 'The virulent strain of the virus spread rapidly across the densely populated urban areas.', exampleTranslation: '这种致命的病毒毒株在人口密集的城市地区迅速传播。', exampleSource: '2022年阅读理解', level: 'low', root: 'virul', affix: '-ent', synonyms: ['toxic', 'deadly', 'malicious'], antonyms: ['harmless', 'benign'], collocations: ['virulent attack', 'virulent strain', 'virulent form'] },
  { id: 'l449', word: 'vitiate', phonetic: '/ˈvɪʃieɪt/', partOfSpeech: 'v.', meanings: ['损害；使无效；削弱'], englishDef: 'to spoil or impair the quality or efficiency of; to make legally invalid', example: 'The procedural errors vitiated the otherwise strong case presented by the prosecution.', exampleTranslation: '程序上的错误削弱了检方原本有力的案件。', exampleSource: '2019年翻译', level: 'low', root: 'viti', affix: '-ate', synonyms: ['impair', 'undermine', 'invalidate'], antonyms: ['strengthen', 'enhance'], collocations: ['vitiate the process', 'vitiate the contract', 'vitiate the results'] },
  { id: 'l450', word: 'vituperate', phonetic: '/vɪˈtjuːpəreɪt/', partOfSpeech: 'v.', meanings: ['痛骂；辱骂；严厉批评'], englishDef: 'to blame or insult someone in strong language', example: 'The columnist vituperated the government for its failure to protect the rights of the vulnerable.', exampleTranslation: '专栏作家严厉批评政府未能保护弱势群体的权利。', exampleSource: '2021年阅读理解', level: 'low', root: 'vituper', affix: '-ate', synonyms: ['berate', 'condemn', 'castigate'], antonyms: ['praise', 'commend'], collocations: ['vituperate against', 'publicly vituperate', 'bitterly vituperate'] },
];
