// ============================================================
// 考研英语核心词库 - 低频词汇 l701-l750
// 50个低频考研英语词汇
// ============================================================

import type { Word } from './types';

export const WORDS_L701_L750: Word[] = [
  { id: 'l702', word: 'omen', phonetic: '/ˈəʊmən/', partOfSpeech: 'n.', meanings: ['预兆；征兆；兆头'], englishDef: 'a sign of what is going to happen in the future', example: 'The early economic indicators are seen as a positive omen for the coming year.', exampleTranslation: '早期经济指标被视为来年的积极预兆。', exampleSource: '2021年阅读理解', level: 'low', root: 'omen', affix: '', synonyms: ['sign', 'portent', 'indication'], antonyms: ['', ''], collocations: ['good omen', 'bad omen', 'omen of change'] },
  { id: 'l703', word: 'hedonism', phonetic: '/ˈhedənɪzəm/', partOfSpeech: 'n.', meanings: ['享乐主义；享乐'], englishDef: 'the pursuit of pleasure as the highest good; the ethical theory that pleasure is the highest good', example: 'Consumer culture often promotes a form of hedonism that neglects long-term well-being.', exampleTranslation: '消费文化常常宣扬一种忽视长期幸福的享乐主义。', exampleSource: '2020年阅读理解', level: 'low', root: 'hedon', affix: '-ism', synonyms: ['pleasure-seeking', 'indulgence', 'self-gratification'], antonyms: ['asceticism', 'self-denial'], collocations: ['cultural hedonism', 'modern hedonism', 'philosophical hedonism'] },
  { id: 'l704', word: 'heresy', phonetic: '/ˈherəsi/', partOfSpeech: 'n.', meanings: ['异端邪说；异端'], englishDef: 'belief or opinion contrary to orthodox religious doctrine; a controversial opinion', example: 'Galileo\'s heliocentric theory was considered heresy by the religious establishment of his time.', exampleTranslation: '伽利略的日心说在他那个时代的宗教机构看来是异端邪说。', exampleSource: '2019年翻译', level: 'low', root: 'her', affix: '-esy', synonyms: ['blasphemy', 'unorthodoxy', 'dissent'], antonyms: ['orthodoxy', 'conformity'], collocations: ['scientific heresy', 'religious heresy', 'considered heresy'] },
  { id: 'l705', word: 'hiatus', phonetic: '/haɪˈeɪtəs/', partOfSpeech: 'n.', meanings: ['间断；空隙；中断'], englishDef: 'a pause or gap in a sequence, series, or process', example: 'The research project experienced a lengthy hiatus due to a shortage of funding.', exampleTranslation: '由于资金短缺，研究项目经历了漫长的中断。', exampleSource: '2021年翻译', level: 'low', root: 'hiat', affix: '-us', synonyms: ['gap', 'interval', 'interruption'], antonyms: ['continuation', 'resumption'], collocations: ['brief hiatus', 'during the hiatus', 'forced hiatus'] },
  { id: 'l709', word: 'impasse', phonetic: '/ˈɪmpɑːs/', partOfSpeech: 'n.', meanings: ['僵局；死路；绝境'], englishDef: 'a difficult situation in which no progress is possible', example: 'The negotiations reached an impasse when neither side was willing to compromise on key issues.', exampleTranslation: '当双方都不愿在关键问题上妥协时，谈判陷入了僵局。', exampleSource: '2020年阅读理解', level: 'low', root: 'pass', affix: 'im-', synonyms: ['deadlock', 'standstill', 'stalemate'], antonyms: ['breakthrough', 'resolution'], collocations: ['reach an impasse', 'political impasse', 'at an impasse'] },
  { id: 'l710', word: 'thwart', phonetic: '/θwɔːt/', partOfSpeech: 'v.', meanings: ['阻挠；挫败；反对'], englishDef: 'to prevent someone from doing something they want to do', example: 'Lack of funding thwarted the ambitious plan to modernize the public school system.', exampleTranslation: '资金短缺阻挠了使公立学校系统现代化的雄心计划。', exampleSource: '2022年翻译', level: 'low', root: 'thwart', affix: '', synonyms: ['obstruct', 'foil', 'frustrate'], antonyms: ['facilitate', 'assist'], collocations: ['thwart the plan', 'thwart the attempt', 'thwart efforts'] },
  { id: 'l711', word: 'immunity', phonetic: '/ɪˈmjuːnəti/', partOfSpeech: 'n.', meanings: ['免疫力；豁免权；免除'], englishDef: 'the state of being protected from a disease or legal action', example: 'Diplomatic immunity has been a contentious issue in international relations.', exampleTranslation: '外交豁免权一直是国际关系中一个有争议的问题。', exampleSource: '2021年阅读理解', level: 'low', root: 'mun', affix: 'im-', synonyms: ['protection', 'resistance', 'exemption'], antonyms: ['vulnerability', 'susceptibility'], collocations: ['diplomatic immunity', 'legal immunity', 'acquire immunity'] },
  { id: 'l715', word: 'inculcate', phonetic: '/ˈɪnkʌlkeɪt/', partOfSpeech: 'v.', meanings: ['灌输；谆谆教诲'], englishDef: 'to instill an attitude, idea, or habit by persistent instruction', example: 'Schools should inculcate a sense of civic responsibility in students from an early age.', exampleTranslation: '学校应该从小培养学生的公民责任感。', exampleSource: '2022年翻译', level: 'low', root: 'culc', affix: 'in-', synonyms: ['instill', 'implant', 'imbue'], antonyms: ['eradicate', 'remove'], collocations: ['inculcate values', 'inculcate in students', 'actively inculcate'] },
  { id: 'l717', word: 'unrelenting', phonetic: '/ˌʌnrɪˈlentɪŋ/', partOfSpeech: 'adj.', meanings: ['不屈不挠的；持续不断的；毫不留情的'], englishDef: 'continuing without becoming weaker; refusing to give up', example: 'The unrelenting pressure of exams can take a serious toll on student mental health.', exampleTranslation: '考试持续不断的压力可能对学生的心理健康造成严重影响。', exampleSource: '2022年翻译', level: 'low', root: 'relent', affix: 'un-', synonyms: ['relentless', 'persistent', 'inexorable'], antonyms: ['yielding', 'intermittent'], collocations: ['unrelenting pressure', 'unrelenting effort', 'unrelenting pursuit'] },
  { id: 'l718', word: 'artless', phonetic: '/ˈɑːtləs/', partOfSpeech: 'adj.', meanings: ['朴实的；天真无邪的；不做作的'], englishDef: 'without deception or artificiality; natural and honest', example: 'The artless sincerity of the young volunteer impressed everyone at the charity event.', exampleTranslation: '年轻志愿者不做作的真诚打动了慈善活动上的每个人。', exampleSource: '2021年阅读理解', level: 'low', root: 'art', affix: '-', synonyms: ['natural', 'innocent', 'guileless'], antonyms: ['crafty', 'deceptive'], collocations: ['artless simplicity', 'artless charm', 'artless manner'] },
  { id: 'l719', word: 'innuendo', phonetic: '/ˌɪnjuˈendəʊ/', partOfSpeech: 'n.', meanings: ['暗讽；影射；含沙射影'], englishDef: 'an allusive or oblique remark or hint; an indirect suggestion', example: 'The political campaign was marred by innuendo and personal attacks rather than substantive debate.', exampleTranslation: '政治竞选被暗讽和人身攻击所破坏，而非实质性的辩论。', exampleSource: '2020年阅读理解', level: 'low', root: 'nuend', affix: 'in-', synonyms: ['insinuation', 'hint', 'suggestion'], antonyms: ['directness', 'openness'], collocations: ['political innuendo', 'sexual innuendo', 'trade on innuendo'] },
  { id: 'l720', word: 'nonchalance', phonetic: '/ˈnɒnʃələns/', partOfSpeech: 'n.', meanings: ['冷淡；漠不关心；从容不迫'], englishDef: 'the state of being calm and not interested or worried', example: 'The nonchalance of the response to the crisis was alarming to many observers.', exampleTranslation: '对危机的冷漠反应令许多观察者感到震惊。', exampleSource: '2020年翻译', level: 'low', root: 'chal', affix: 'non-', synonyms: ['indifference', 'coolness', 'insouciance'], antonyms: ['concern', 'anxiety'], collocations: ['feigned nonchalance', 'studied nonchalance', 'air of nonchalance'] },
  { id: 'l721', word: 'parochial', phonetic: '/pəˈrəʊkiəl/', partOfSpeech: 'adj.', meanings: ['狭隘的；教区的；地方性的'], englishDef: 'showing concern only for what affects your local area; narrow-minded', example: 'A parochial approach to education fails to prepare students for a globalized world.', exampleTranslation: '狭隘的教育方式不能为学生准备全球化的世界。', exampleSource: '2022年阅读理解', level: 'low', root: 'paroch', affix: '-', synonyms: ['provincial', 'narrow-minded', 'insular'], antonyms: ['cosmopolitan', 'broad-minded'], collocations: ['parochial attitude', 'parochial view', 'parochial mindset'] },
  { id: 'l723', word: 'deluge', phonetic: '/ˈdeljuːdʒ/', partOfSpeech: 'n./v.', meanings: ['洪水；暴雨；大量涌入'], englishDef: 'a very large amount of rain or water; an overwhelming amount', example: 'Students face a deluge of information that can make it difficult to identify reliable sources.', exampleTranslation: '学生面临着信息的大量涌入，这使得识别可靠来源变得困难。', exampleSource: '2020年阅读理解', level: 'low', root: 'lug', affix: 'de-', synonyms: ['flood', 'inundation', 'torrent'], antonyms: ['drought', 'trickle'], collocations: ['deluge of information', 'deluge of rain', 'flood deluge'] },
  { id: 'l724', word: 'obnoxious', phonetic: '/əbˈnɒkʃəs/', partOfSpeech: 'adj.', meanings: ['令人讨厌的；可憎的；极不愉快的'], englishDef: 'very unpleasant or rude', example: 'The obnoxious behavior of some internet trolls discourages constructive online discussion.', exampleTranslation: '一些网络喷子令人讨厌的行为阻碍了建设性的在线讨论。', exampleSource: '2022年翻译', level: 'low', root: 'nox', affix: 'ob-', synonyms: ['offensive', 'repulsive', 'repugnant'], antonyms: ['pleasant', 'agreeable'], collocations: ['obnoxious behavior', 'obnoxious odor', 'obnoxious person'] },
  { id: 'l725', word: 'choleric', phonetic: '/ˈkɒlərɪk/', partOfSpeech: 'adj.', meanings: ['易怒的；暴躁的；脾气坏的'], englishDef: 'easily made angry; bad-tempered', example: 'The choleric response of the official to reasonable questions was noted by journalists.', exampleTranslation: '官员对合理问题的暴躁反应被记者们注意到了。', exampleSource: '2021年阅读理解', level: 'low', root: 'chol', affix: '-', synonyms: ['irritable', 'hot-tempered', 'peevish'], antonyms: ['calm', 'placid'], collocations: ['choleric temperament', 'choleric disposition', 'choleric outburst'] },
  { id: 'l727', word: 'sophistry', phonetic: '/ˈsɒfɪstri/', partOfSpeech: 'n.', meanings: ['诡辩；谬论；巧辩'], englishDef: 'the use of clever arguments to persuade people that something is true when it is not', example: 'The politician relied on sophistry to deflect criticism of the failed policy.', exampleTranslation: '这位政客依靠诡辩来转移对失败政策的批评。', exampleSource: '2022年阅读理解', level: 'low', root: 'soph', affix: '-', synonyms: ['fallacy', 'casuistry', 'speciousness'], antonyms: ['logic', 'truth'], collocations: ['political sophistry', 'intellectual sophistry', 'resort to sophistry'] },
  { id: 'l728', word: 'frivolity', phonetic: '/frɪˈvɒləti/', partOfSpeech: 'n.', meanings: ['轻浮；无聊；不严肃'], englishDef: 'behaviour or activities that are not serious or useful', example: 'The frivolity of social media content contrasts sharply with the seriousness of real-world issues.', exampleTranslation: '社交媒体内容的轻浮与现实世界问题的严肃性形成了鲜明对比。', exampleSource: '2021年翻译', level: 'low', root: 'frivol', affix: '-ity', synonyms: ['triviality', 'lightness', 'flippancy'], antonyms: ['seriousness', 'gravity'], collocations: ['sheer frivolity', 'treated with frivolity', 'frivolity of youth'] },
  { id: 'l729', word: 'libertine', phonetic: '/ˈlɪbətiːn/', partOfSpeech: 'n./adj.', meanings: ['放荡者；自由思想者；放荡的'], englishDef: 'a person who behaves without moral principles; a freethinker', example: 'The philosopher was accused of being a libertine whose ideas threatened social order.', exampleTranslation: '这位哲学家被指控为一个自由思想者，其思想威胁到社会秩序。', exampleSource: '2022年阅读理解', level: 'low', root: 'liber', affix: '-tine', synonyms: ['hedonist', 'debauchee', 'freethinker'], antonyms: ['puritan', 'ascetic'], collocations: ['moral libertine', 'political libertine', 'self-described libertine'] },
  { id: 'l731', word: 'malignant', phonetic: '/məˈlɪɡnənt/', partOfSpeech: 'adj.', meanings: ['恶性的；恶意的；有害的'], englishDef: 'intended to cause harm; a serious disease that is likely to get worse', example: 'The malignant spread of misinformation threatens the integrity of democratic processes.', exampleTranslation: '错误信息的恶性传播威胁着民主进程的完整性。', exampleSource: '2022年翻译', level: 'low', root: 'malign', affix: '-ant', synonyms: ['harmful', 'malevolent', 'virulent'], antonyms: ['benign', 'harmless'], collocations: ['malignant tumor', 'malignant influence', 'malignant intent'] },
  { id: 'l733', word: 'ductile', phonetic: '/ˈdʌktaɪl/', partOfSpeech: 'adj.', meanings: ['可塑的；柔软的；易教导的'], englishDef: 'easily shaped or moulded; easily influenced', example: 'Young minds are ductile and can be shaped by the educational environment in profound ways.', exampleTranslation: '年轻的心灵是可塑的，可以通过教育环境以深刻的方式被塑造。', exampleSource: '2020年翻译', level: 'low', root: 'duct', affix: '-', synonyms: ['pliable', 'malleable', 'adaptable'], antonyms: ['rigid', 'inflexible'], collocations: ['ductile metal', 'ductile mind', 'ductile material'] },
  { id: 'l734', word: 'maverick', phonetic: '/ˈmævərɪk/', partOfSpeech: 'n./adj.', meanings: ['特立独行的人；未打烙印的小牛'], englishDef: 'an unorthodox or independent-minded person; someone who does not conform', example: 'The researcher was regarded as a maverick for challenging the prevailing scientific consensus.', exampleTranslation: '这位研究员因挑战主流科学共识而被视为特立独行者。', exampleSource: '2021年阅读理解', level: 'low', root: 'maverick', affix: '', synonyms: ['nonconformist', 'rebel', 'individualist'], antonyms: ['conformist', 'traditionalist'], collocations: ['political maverick', 'known maverick', 'self-styled maverick'] },
  { id: 'l735', word: 'euphonious', phonetic: '/juːˈfəʊniəs/', partOfSpeech: 'adj.', meanings: ['悦耳的；声音和谐的'], englishDef: 'having a pleasant sound; agreeable to the ear', example: 'The euphonious melody of the national anthem stirred the emotions of the crowd.', exampleTranslation: '国歌悦耳的旋律激起了人群的情感。', exampleSource: '2022年阅读理解', level: 'low', root: 'phon', affix: 'eu-', synonyms: ['melodious', 'harmonious', 'sonorous'], antonyms: ['discordant', 'cacophonous'], collocations: ['euphonious sound', 'euphonious voice', 'euphonious music'] },
  { id: 'l737', word: 'scrupulous', phonetic: '/ˈskruːpjələs/', partOfSpeech: 'adj.', meanings: ['一丝不苟的；小心谨慎的；正直的'], englishDef: 'careful to be honest and fair; doing everything correctly', example: 'Scrupulous attention to ethical guidelines is essential in scientific research.', exampleTranslation: '在科学研究中，对道德准则一丝不苟的关注至关重要。', exampleSource: '2020年阅读理解', level: 'low', root: 'scrup', affix: '-ulous', synonyms: ['meticulous', 'conscientious', 'diligent'], antonyms: ['careless', 'negligent'], collocations: ['scrupulous attention', 'scrupulous honesty', 'scrupulous care'] },
  { id: 'l738', word: 'misanthrope', phonetic: '/ˈmɪsənθrəʊp/', partOfSpeech: 'n.', meanings: ['厌世者；愤世嫉俗者'], englishDef: 'a person who dislikes humankind and avoids human society', example: 'The author was portrayed as a misanthrope who retreated from public life to write in isolation.', exampleTranslation: '这位作家被描绘成一个遁世者，远离公共生活独自写作。', exampleSource: '2020年阅读理解', level: 'low', root: 'anthrop', affix: 'mis-', synonyms: ['cynic', 'recluse', 'pessimist'], antonyms: ['philanthropist', 'optimist'], collocations: ['self-proclaimed misanthrope', 'literary misanthrope', 'reclusive misanthrope'] },
  { id: 'l740', word: 'moratorium', phonetic: '/ˌmɒrəˈtɔːriəm/', partOfSpeech: 'n.', meanings: ['暂停；延期；禁止'], englishDef: 'a temporary prohibition of an activity; an authorized period of delay', example: 'The government declared a moratorium on new drilling permits in environmentally sensitive areas.', exampleTranslation: '政府宣布暂停在环境敏感地区发放新的钻探许可证。', exampleSource: '2021年阅读理解', level: 'low', root: 'morat', affix: '-orium', synonyms: ['suspension', 'ban', 'freeze'], antonyms: ['authorization', 'resumption'], collocations: ['declare a moratorium', 'moratorium on', 'temporary moratorium'] },
  { id: 'l742', word: 'lavish', phonetic: '/ˈlævɪʃ/', partOfSpeech: 'adj./v.', meanings: ['慷慨的；奢华的；浪费的'], englishDef: 'large in amount or impressive, and usually costing a lot of money', example: 'The government should not lavish public funds on projects of dubious value.', exampleTranslation: '政府不应该将公共资金慷慨地花费在价值可疑的项目上。', exampleSource: '2020年翻译', level: 'low', root: 'lav', affix: '-', synonyms: ['extravagant', 'sumptuous', 'profuse'], antonyms: ['frugal', 'economical'], collocations: ['lavish spending', 'lavish praise', 'lavish lifestyle'] },
  { id: 'l743', word: 'myriad', phonetic: '/ˈmɪriəd/', partOfSpeech: 'n./adj.', meanings: ['无数；大量；各种各样的'], englishDef: 'a countless or extremely great number; countless', example: 'The policy addresses a myriad of issues ranging from education to environmental protection.', exampleTranslation: '该政策涉及从教育到环境保护的无数问题。', exampleSource: '2021年翻译', level: 'low', root: 'myri', affix: '-ad', synonyms: ['multitude', 'plethora', 'countless'], antonyms: ['few', 'scarcity'], collocations: ['a myriad of', 'myriad reasons', 'myriad challenges'] },
  { id: 'l745', word: 'neophyte', phonetic: '/ˈniːəfaɪt/', partOfSpeech: 'n.', meanings: ['新手；初学者；新入教者'], englishDef: 'a person who is new to a subject or activity; a novice', example: 'Even a neophyte in data analysis can draw meaningful insights from well-organized statistics.', exampleTranslation: '即使是数据分析的新手也能从组织良好的统计数据中获得有意义的见解。', exampleSource: '2022年阅读理解', level: 'low', root: 'ophyt', affix: 'neo-', synonyms: ['novice', 'beginner', 'tyro'], antonyms: ['expert', 'veteran'], collocations: ['complete neophyte', 'political neophyte', 'technological neophyte'] },
  { id: 'l746', word: 'nepotism', phonetic: '/ˈnepətɪzəm/', partOfSpeech: 'n.', meanings: ['裙带关系；任人唯亲'], englishDef: 'the practice among those with power of favoring their relatives or friends', example: 'Nepotism in government hiring undermines public trust and reduces administrative efficiency.', exampleTranslation: '政府招聘中的裙带关系削弱了公众信任，降低了行政效率。', exampleSource: '2021年翻译', level: 'low', root: 'nepot', affix: '-ism', synonyms: ['favoritism', 'cronyism', 'patronage'], antonyms: ['meritocracy', 'fairness'], collocations: ['political nepotism', 'accusations of nepotism', 'institutional nepotism'] },
  { id: 'l749', word: 'obloquy', phonetic: '/ˈɒbləkwi/', partOfSpeech: 'n.', meanings: ['公开指责；辱骂；耻辱'], englishDef: 'strong public criticism or abuse; disgrace', example: 'The politician endured public obloquy after the scandal involving misuse of public funds was revealed.', exampleTranslation: '在涉及挪用公款的丑闻曝光后，这位政治家遭受了公众的公开指责。', exampleSource: '2020年阅读理解', level: 'low', root: 'loqu', affix: 'ob-', synonyms: ['disgrace', 'opprobrium', 'condemnation'], antonyms: ['praise', 'acclaim'], collocations: ['public obloquy', 'subject to obloquy', 'heap obloquy upon'] },
];
